### ISSUE TITLE
tvOS - Library import/refresh randomly crashes

### ISSUE THREAD

**Issue by chrisjllamb** [Provenance-Emu/Provenance#1006]
When importing roms into the library OR refreshing the library, Provenance crashes

### Expected:  
The library refresh continues without interruption

### Actual:  
Provenance crashes and quits

### Reproduce:  
1. Launch provenance on tvOS
2. IF no ROMS exist, copy over a large number to the imports folder
3. Wait for the import process to happen. If you already had a large number of ROMS, it should start auto importing on launch
4. Wait. Sometimes it takes up to a minute - other times it takes just a second

# 
#### NOTES  

1. There are a large number of Nintendo 64 and SNES games that I am trying to import. It also happened previously when I tried NES games as well.

2. Crash log is as follows:

Date/Time:           2018-10-12 21:50:40.1664 +0100
Launch Time:         2018-10-12 21:50:39.4133 +0100
OS Version:          Apple TVOS 12.0.1 (16J380)
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
abort() called

Last Exception Backtrace:
0   CoreFoundation                	0x24fee1248 __exceptionPreprocess + 228
1   libobjc.A.dylib               	0x24f0bea40 objc_exception_throw + 55
2   CoreFoundation                	0x24fdf5674 +[NSException raise:format:arguments:] + 103
3   Foundation                    	0x2508f3450 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 111
4   UIKitCore                     	0x26ee1e290 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 12839
5   UIKitCore                     	0x26ee254dc -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 91
6   UIKitCore                     	0x26ee25814 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 387
7   UIKitCore                     	0x26ee25670 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 95
8   UIKitCore                     	0x26ee255f4 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 83
9   UIKitCore                     	0x26ee25530 -[UICollectionView performBatchUpdates:completion:] + 63
10  Provenance                    	0x100651340 0x1005d8000 + 496448
11  RealmSwift                    	0x10a69315c 0x10a664000 + 192860
12  RealmSwift                    	0x10a6711f0 0x10a664000 + 53744
13  Realm                         	0x1088062dc 0x1087a0000 + 418524
14  Realm                         	0x1088060dc 0x1087a0000 + 418012
15  Realm                         	0x1087b2994 0x1087a0000 + 76180
16  Realm                         	0x1087b36b8 0x1087a0000 + 79544
17  Realm                         	0x1088cd0cc 0x1087a0000 + 1233100
18  Realm                         	0x1087e2d0c 0x1087a0000 + 273676
19  Realm                         	0x1088a821c 0x1087a0000 + 1081884
20  Realm                         	0x1088d95c0 0x1087a0000 + 1283520
21  CoreFoundation                	0x24fe6fa00 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 23
22  CoreFoundation                	0x24fe6f980 __CFRunLoopDoSource0 + 87
23  CoreFoundation                	0x24fe6f264 __CFRunLoopDoSources0 + 175
24  CoreFoundation                	0x24fe6a130 __CFRunLoopRun + 1039
25  CoreFoundation                	0x24fe69a00 CFRunLoopRunSpecific + 435
26  GraphicsServices              	0x252118584 GSEventRunModal + 99
27  UIKitCore                     	0x26ed6cecc UIApplicationMain + 211
28  Provenance                    	0x100606844 0x1005d8000 + 190532
29  libdyld.dylib                 	0x24f90adfc start + 3

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x000000024fa6d104 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x000000024faec77c pthread_kill + 380
2   libsystem_c.dylib             	0x000000024f9ba130 abort + 140
3   HockeySDK                     	0x0000000100e5df8c -[BITPLCrashReporter generateLiveReportWithThread:] + 0
4   CoreFoundation                	0x000000024fee1584 __handleUncaughtException + 692
5   libobjc.A.dylib               	0x000000024f0bee3c _objc_terminate+ 40508 () + 112
6   HockeySDK                     	0x0000000100e57820 BITCrashUncaughtCXXTerminateHandler() + 227360 (BITCrashCXXExceptionHandler.mm:153)
7   libc++abi.dylib               	0x000000024f0af0fc std::__terminate(void (*)+ 57596 ()) + 16
8   libc++abi.dylib               	0x000000024f0aecec __cxa_rethrow + 144
9   libobjc.A.dylib               	0x000000024f0bec10 objc_exception_rethrow + 44
10  CoreFoundation                	0x000000024fe69a6c CFRunLoopRunSpecific + 544
11  GraphicsServices              	0x0000000252118584 GSEventRunModal + 100
12  UIKitCore                     	0x000000026ed6cecc UIApplicationMain + 212
13  Provenance                    	0x0000000100606844 0x1005d8000 + 190532
14  libdyld.dylib                 	0x000000024f90adfc start + 4

Thread 1:
0   libsystem_pthread.dylib       	0x000000024faf3b98 start_wqthread + 0

Thread 2 name:  Dispatch queue: com.apple.root.background-qos
Thread 2:
0   CoreFoundation                	0x000000024fe8acdc CFStringCreateMutable + 204
1   CoreFoundation                	0x000000024fe8ac5c CFStringCreateMutable + 76
2   Foundation                    	0x0000000250895874 -[NSString lowercaseStringWithLocale:] + 44
3   libswiftCore.dylib            	0x000000010ace9584 0x10a9f0000 + 3118468
4   libswiftCore.dylib            	0x000000010ac58ea8 0x10a9f0000 + 2526888
5   PVLibrary                     	0x00000001031f6e60 0x103134000 + 798304
6   PVLibrary                     	0x00000001031d90b4 0x103134000 + 676020
7   PVLibrary                     	0x00000001031e5214 0x103134000 + 725524
8   PVLibrary                     	0x00000001031d9934 0x103134000 + 678196
9   PVLibrary                     	0x00000001031d9a8c 0x103134000 + 678540
10  PVLibrary                     	0x00000001031d9abc 0x103134000 + 678588
11  PVLibrary                     	0x00000001031d9abc 0x103134000 + 678588
12  PVLibrary                     	0x00000001031d9ae4 0x103134000 + 678628
13  PVLibrary                     	0x00000001031d9abc 0x103134000 + 678588
14  PVLibrary                     	0x00000001031d9ae4 0x103134000 + 678628
15  PVLibrary                     	0x00000001031cfa0c 0x103134000 + 637452
16  PVLibrary                     	0x00000001031c0a88 0x103134000 + 576136
17  Provenance                    	0x000000010065a500 0x1005d8000 + 533760
18  Provenance                    	0x00000001006764dc 0x1005d8000 + 648412
19  Foundation                    	0x000000025097c9fc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
20  Foundation                    	0x000000025097ca44 __24-[NSBlockOperation main]_block_invoke + 64
21  libdispatch.dylib             	0x000000024f8d206c _dispatch_client_callout2 + 16
22  libdispatch.dylib             	0x000000024f8e2f10 _dispatch_apply_invoke + 164
23  libdispatch.dylib             	0x000000024f8d202c _dispatch_client_callout + 16
24  libdispatch.dylib             	0x000000024f8e1280 _dispatch_root_queue_drain + 680
25  libdispatch.dylib             	0x000000024f8e19e8 _dispatch_worker_thread2 + 128
26  libsystem_pthread.dylib       	0x000000024faed7f0 _pthread_wqthread + 472
27  libsystem_pthread.dylib       	0x000000024faf3b9c start_wqthread + 4

Thread 3 name:  Dispatch queue: romImporterWorkQueue (QOS: UNSPECIFIED)
Thread 3:
0   libsystem_kernel.dylib        	0x000000024fa6d9fc __ulock_wait + 8
1   libsystem_platform.dylib      	0x000000024fae5f04 _os_unfair_lock_lock_slow + 220
2   libobjc.A.dylib               	0x000000024f0d1830 objc_sync_enter + 32
3   PVLibrary                     	0x000000010313a2e0 0x103134000 + 25312
4   PVLibrary                     	0x00000001031caff8 0x103134000 + 618488
5   PVLibrary                     	0x00000001031c6e00 0x103134000 + 601600
6   PVLibrary                     	0x00000001031bbcf0 0x103134000 + 556272
7   PVLibrary                     	0x00000001031c3c5c 0x103134000 + 588892
8   PVLibrary                     	0x00000001031c6c80 0x103134000 + 601216
9   PVLibrary                     	0x00000001031c51d0 0x103134000 + 594384
10  PVLibrary                     	0x00000001031e31d4 0x103134000 + 717268
11  PVLibrary                     	0x00000001031e3204 0x103134000 + 717316
12  libswiftObjectiveC.dylib      	0x000000010b47ae34 0x10b474000 + 28212
13  PVLibrary                     	0x00000001031c38ec 0x103134000 + 588012
14  PVLibrary                     	0x00000001031e3134 0x103134000 + 717108
15  PVLibrary                     	0x000000010318ff74 0x103134000 + 376692
16  Foundation                    	0x000000025097c9fc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
17  Foundation                    	0x0000000250886d78 -[NSBlockOperation main] + 72
18  Foundation                    	0x000000025088624c -[__NSOperationInternal _start:] + 740
19  Foundation                    	0x000000025097e8d0 __NSOQSchedule_f + 272
20  libdispatch.dylib             	0x000000024f8d0a88 _dispatch_call_block_and_release + 24
21  libdispatch.dylib             	0x000000024f8d202c _dispatch_client_callout + 16
22  libdispatch.dylib             	0x000000024f8d4fa4 _dispatch_continuation_pop + 412
23  libdispatch.dylib             	0x000000024f8d466c _dispatch_async_redirect_invoke + 600
24  libdispatch.dylib             	0x000000024f8e114c _dispatch_root_queue_drain + 372
25  libdispatch.dylib             	0x000000024f8e19e8 _dispatch_worker_thread2 + 128
26  libsystem_pthread.dylib       	0x000000024faed7f0 _pthread_wqthread + 472
27  libsystem_pthread.dylib       	0x000000024faf3b9c start_wqthread + 4

Thread 4 name:  com.apple.uikit.eventfetch-thread
Thread 4:
0   libsystem_kernel.dylib        	0x000000024fa61ed0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x000000024fa613a8 mach_msg + 72
2   CoreFoundation                	0x000000024fe6f3f8 __CFRunLoopServiceMachPort + 236
3   CoreFoundation                	0x000000024fe6a294 __CFRunLoopRun + 1396
4   CoreFoundation                	0x000000024fe69a00 CFRunLoopRunSpecific + 436
5   Foundation                    	0x000000025086f754 -[NSRunLoop+ 42836 (NSRunLoop) runMode:beforeDate:] + 300
6   Foundation                    	0x000000025086f5c4 -[NSRunLoop+ 42436 (NSRunLoop) runUntilDate:] + 88
7   UIKitCore                     	0x000000026eccdff0 -[UIEventFetcher threadMain] + 136
8   Foundation                    	0x00000002509a0240 __NSThread__start__ + 1040
9   libsystem_pthread.dylib       	0x000000024faeb47c _pthread_body + 128
10  libsystem_pthread.dylib       	0x000000024faeb3dc _pthread_start + 48
11  libsystem_pthread.dylib       	0x000000024faf3ba4 thread_start + 4

Thread 5 name:  Dispatch queue: romImporterWorkQueue (QOS: UNSPECIFIED)
Thread 5:
0   libsystem_malloc.dylib        	0x000000024fab5060 malloc_default_zone + 0
1   CoreFoundation                	0x000000024fe1392c __CFAllocatorSystemDeallocate + 40
2   CoreFoundation                	0x000000024fe71298 _CFRelease + 824
3   CoreFoundation                	0x000000024feb2918 __CFURLDeallocate + 40
4   CoreFoundation                	0x000000024fe71020 _CFRelease + 192
5   Realm                         	0x0000000108876498 0x1087a0000 + 877720
6   Realm                         	0x0000000108875aa0 0x1087a0000 + 875168
7   RealmSwift                    	0x000000010a6832ec 0x10a664000 + 127724
8   RealmSwift                    	0x000000010a683280 0x10a664000 + 127616
9   PVLibrary                     	0x000000010319fb50 0x103134000 + 441168
10  PVLibrary                     	0x00000001031c2d24 0x103134000 + 584996
11  PVLibrary                     	0x00000001031e3134 0x103134000 + 717108
12  PVLibrary                     	0x000000010318ff74 0x103134000 + 376692
13  Foundation                    	0x000000025097c9fc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
14  Foundation                    	0x0000000250886d78 -[NSBlockOperation main] + 72
15  Foundation                    	0x000000025088624c -[__NSOperationInternal _start:] + 740
16  Foundation                    	0x000000025097e8d0 __NSOQSchedule_f + 272
17  libdispatch.dylib             	0x000000024f8d0a88 _dispatch_call_block_and_release + 24
18  libdispatch.dylib             	0x000000024f8d202c _dispatch_client_callout + 16
19  libdispatch.dylib             	0x000000024f8d4fa4 _dispatch_continuation_pop + 412
20  libdispatch.dylib             	0x000000024f8d466c _dispatch_async_redirect_invoke + 600
21  libdispatch.dylib             	0x000000024f8e114c _dispatch_root_queue_drain + 372
22  libdispatch.dylib             	0x000000024f8e19e8 _dispatch_worker_thread2 + 128
23  libsystem_pthread.dylib       	0x000000024faed7f0 _pthread_wqthread + 472
24  libsystem_pthread.dylib       	0x000000024faf3b9c start_wqthread + 4

Thread 6 name:  Dispatch queue: romImporterWorkQueue (QOS: UNSPECIFIED)
Thread 6:
0   libsystem_kernel.dylib        	0x000000024fa6f024 pread + 8
1   libsqlite3.dylib              	0x00000002503a1d58 0x2502e9000 + 757080
2   libsqlite3.dylib              	0x00000002502f3068 0x2502e9000 + 41064
3   libsqlite3.dylib              	0x00000002503158f4 0x2502e9000 + 182516
4   libsqlite3.dylib              	0x00000002503ab478 0x2502e9000 + 795768
5   libsqlite3.dylib              	0x00000002503b3a48 0x2502e9000 + 830024
6   libsqlite3.dylib              	0x000000025033f338 0x2502e9000 + 353080
7   libsqlite3.dylib              	0x00000002503b501c 0x2502e9000 + 835612
8   libsqlite3.dylib              	0x000000025032ebdc 0x2502e9000 + 285660
9   libsqlite3.dylib              	0x000000025032c464 sqlite3_step + 432
10  PVLibrary                     	0x000000010313a530 0x103134000 + 25904
11  PVLibrary                     	0x00000001031caff8 0x103134000 + 618488
12  PVLibrary                     	0x00000001031c6e00 0x103134000 + 601600
13  PVLibrary                     	0x00000001031bbcf0 0x103134000 + 556272
14  PVLibrary                     	0x00000001031c3c5c 0x103134000 + 588892
15  PVLibrary                     	0x00000001031c6c80 0x103134000 + 601216
16  PVLibrary                     	0x00000001031c51d0 0x103134000 + 594384
17  PVLibrary                     	0x00000001031e31d4 0x103134000 + 717268
18  PVLibrary                     	0x00000001031e3204 0x103134000 + 717316
19  libswiftObjectiveC.dylib      	0x000000010b47ae34 0x10b474000 + 28212
20  PVLibrary                     	0x00000001031c38ec 0x103134000 + 588012
21  PVLibrary                     	0x00000001031e3134 0x103134000 + 717108
22  PVLibrary                     	0x000000010318ff74 0x103134000 + 376692
23  Foundation                    	0x000000025097c9fc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
24  Foundation                    	0x0000000250886d78 -[NSBlockOperation main] + 72
25  Foundation                    	0x000000025088624c -[__NSOperationInternal _start:] + 740
26  Foundation                    	0x000000025097e8d0 __NSOQSchedule_f + 272
27  libdispatch.dylib             	0x000000024f8d0a88 _dispatch_call_block_and_release + 24
28  libdispatch.dylib             	0x000000024f8d202c _dispatch_client_callout + 16
29  libdispatch.dylib             	0x000000024f8d4fa4 _dispatch_continuation_pop + 412
30  libdispatch.dylib             	0x000000024f8d466c _dispatch_async_redirect_invoke + 600
31  libdispatch.dylib             	0x000000024f8e114c _dispatch_root_queue_drain + 372
32  libdispatch.dylib             	0x000000024f8e19e8 _dispatch_worker_thread2 + 128
33  libsystem_pthread.dylib       	0x000000024faed7f0 _pthread_wqthread + 472
34  libsystem_pthread.dylib       	0x000000024faf3b9c start_wqthread + 4

Thread 7 name:  RLMRealm notification listener
Thread 7:
0   libsystem_kernel.dylib        	0x000000024fa6e91c kevent + 8
1   Realm                         	0x00000001087b606c 0x1087a0000 + 90220
2   Realm                         	0x00000001087b62a0 0x1087a0000 + 90784
3   Realm                         	0x00000001087b6224 0x1087a0000 + 90660
4   Realm                         	0x00000001087b63e0 0x1087a0000 + 91104
5   libsystem_pthread.dylib       	0x000000024faeb47c _pthread_body + 128
6   libsystem_pthread.dylib       	0x000000024faeb3dc _pthread_start + 48
7   libsystem_pthread.dylib       	0x000000024faf3ba4 thread_start + 4

Thread 8 name:  com.apple.CFSocket.private
Thread 8:
0   libsystem_kernel.dylib        	0x000000024fa6d350 __select + 8
1   CoreFoundation                	0x000000024fe78248 __CFSocketManager + 620
2   libsystem_pthread.dylib       	0x000000024faeb47c _pthread_body + 128
3   libsystem_pthread.dylib       	0x000000024faeb3dc _pthread_start + 48
4   libsystem_pthread.dylib       	0x000000024faf3ba4 thread_start + 4

Thread 9:
0   libsystem_pthread.dylib       	0x000000024faf3b98 start_wqthread + 0

Thread 10 name:  Dispatch queue: com.apple.root.background-qos
Thread 10:
0   libsystem_kernel.dylib        	0x000000024fa6d9fc __ulock_wait + 8
1   libdispatch.dylib             	0x000000024f8d29b0 _dispatch_ulock_wait + 56
2   libdispatch.dylib             	0x000000024f8d2ae8 _dispatch_thread_event_wait_slow + 48
3   libdispatch.dylib             	0x000000024f8e3b28 _dispatch_apply_invoke_and_wait + 292
4   libdispatch.dylib             	0x000000024f8e3538 dispatch_apply_f + 720
5   Foundation                    	0x0000000250886e4c -[NSBlockOperation main] + 284
6   Foundation                    	0x000000025088624c -[__NSOperationInternal _start:] + 740
7   Foundation                    	0x000000025097e8d0 __NSOQSchedule_f + 272
8   libdispatch.dylib             	0x000000024f8d0a88 _dispatch_call_block_and_release + 24
9   libdispatch.dylib             	0x000000024f8d202c _dispatch_client_callout + 16
10  libdispatch.dylib             	0x000000024f8d4fa4 _dispatch_continuation_pop + 412
11  libdispatch.dylib             	0x000000024f8d466c _dispatch_async_redirect_invoke + 600
12  libdispatch.dylib             	0x000000024f8e114c _dispatch_root_queue_drain + 372
13  libdispatch.dylib             	0x000000024f8e19e8 _dispatch_worker_thread2 + 128
14  libsystem_pthread.dylib       	0x000000024faed7f0 _pthread_wqthread + 472
15  libsystem_pthread.dylib       	0x000000024faf3b9c start_wqthread + 4

Thread 11:
0   libsystem_pthread.dylib       	0x000000024faf3b98 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0xffffffffffffffff
    x4: 0x0000000000000010   x5: 0x0000000000000010   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000800   x9: 0x0000000000000000  x10: 0x0000000000003f13  x11: 0x0000000279f46cd5
   x12: 0x0000000279f46cd5  x13: 0x0000000000000016  x14: 0x0000000000000001  x15: 0x0000000000000881
   x16: 0x0000000000000148  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000100b02b80  x21: 0x0000000271c8afe8  x22: 0x0000000000000303  x23: 0x0000000100b02c60
   x24: 0x0000000271c4fcb0  x25: 0x0000000276581000  x26: 0x000000010bdb8aa0  x27: 0x000000026f729080
   x28: 0x000000024ff6d1a6   fp: 0x000000016f827370   lr: 0x000000024faec77c
    sp: 0x000000016f827340   pc: 0x000000024fa6d104 cpsr: 0x00000000

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 10
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (12.0.1)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
This is an existing big

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JoeMatt** [comment]
It should be fine after a restart or two. Closing since this is a known bug (it's a Realm thing, to be maybe fixed with RxRealm)
