### ISSUE TITLE
8bitdo Not working on french iPhone due to bad key mapping

### ISSUE THREAD

**Issue by Canadadry** [Provenance-Emu/Provenance#1008]
8bitdo Not working on french iPhone due to bad key mapping.

See [#601](https://github.com/Provenance-Emu/Provenance/issues/601) It was closed and supposed to be fixed but never was. 

#### APP VERSION
- [x] 1.5 *beta*
- [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [X] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (12)
- [x] 11.x
- [ ] 10.x ( not tested but I don't see why it should work)
- [ ] 9.x ( not tested but I don't see why it should work)
- [ ] 8.x  ( not tested but I don't see why it should work)

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
8bitdo remapping and other iCade issues can be deferred to #741
