### ISSUE TITLE
PSX games not on my library

### ISSUE THREAD

**Issue by reecreateeduardo** [Provenance-Emu/Provenance#1010]
So I followed the guide:

Added the PSX bios to my provenance app (confirmed and it is there)

Then, I downloaded FFVII.

Created the .m3u (like I did for when I added it to my Openmu on my Mac.
Created a folder named **com.provenance.psx** and added the zip file with the .cue .bin and .m3u file there. (via the web browser)

Refreshed the library and the game isn't there.
Added as well to the Import folder and nothing.

If I go to my iPhone storage, the game is indeed on Provenance, just not on the library.

Did I miss something?

Thanks

**Comment by reecreateeduardo** [comment]
It extracted properly since the game now is on the folder **Imports** extracted with all the files there. Been around this for hours.

Can't even play one Disc games. What am I doing wrong? iPhone Xs iOS 12.0.1

**Comment by JoeMatt** [comment]
Zips go into the imports folder, refreshing the library with a zip in the system's rom's folder will be ignored, though unzipped there it would work. 

This isn't a bug, check the guide again (Imports folder you don't need to manually manage anything) and ask on Discord help channel if more help needed.

**Comment by reecreateeduardo** [comment]
I put the zip file on the imports folder. Anything else I need to do?
