### ISSUE TITLE
Crash on save state

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#1011]
Intermittent crashes on save state and/or save & overwrite state. May be related to #991, with auto save on.

### Expected:  
State saved

### Actual:  
Sometimes crashes.

### Reproduce:  
1. Play (ie SNES)
2. Attempt to create manual save state, and/or save & overwrite
3. Repeat until crash…

# 
#### NOTES  
If crash reporter is working, was submitted.
#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by urherenow** [comment]
I have no issue creating a save state on 2.0+
