### ISSUE TITLE
[Core] TGBDual-libretro

### ISSUE THREAD

**Issue by error404-na** [Provenance-Emu/Provenance#1019]
Add libreto port of TGBDual as core to Provenance
https://github.com/libretro/tgbdual-libretro

Could be used so play tetris against each other.

**Comment by error404-na** [comment]
Thanks for already merging the [pull-request](https://github.com/Provenance-Emu/Provenance/pull/1051)! 👍
Makes it easier for me to work on the other topics.

**Comment by JoeMatt** [comment]
Added in #1051
