### ISSUE TITLE
Change Opacity slider minimum value to 0.05 to avoid locking users into Game.

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1023]
Can we maybe set the Opacity Slider Minimum value to 0.05 (or 0.1) to make sure the Controller UI is always visible and Users don't get stuck in a game if they were to take the Controller Opacity to 0.0, as they currently can.

**Comment by mrjschulte** [comment]
Looks like the Controller Opacity slider is gone in the latest develop build so perhaps it's worth closing this issue.

**Comment by jasarien** [comment]
I think the fact that it’s missing is being considered a bug. It should be brought back at some point, and when it does, this enhancement will be relevant. I’d keep it open.

**Comment by mrjschulte** [comment]
Ok, reopening. Looking through the source I see that @JoeMatt has marked the Opacity slider as a to-do. Excuse the noise/

**Comment by JoeMatt** [comment]
The settings table view was replaced with a generic data model for settings of type bool, string, number, multi choice, but there was no cell for a slider. 

It reduced a bunch of duplicated code between iOS and tvOS and got rid of the complicated switch statements and annoying manual editing of the storyboards for any minor addition or change.

Have to just subclass the default cell and add a slider, didn't get a chance to do that..

https://github.com/bcylin/QuickTableViewController this is the project,  if someone just wants to add a cell class for slider that's all that's needed.

**Comment by mrjschulte** [comment]
https://github.com/bcylin/QuickTableViewController/issues/23 here's a stab at adding a slider.

**Comment by getaaron** [comment]
@JoeMatt @jasarien @mrjschulte  I had written a slider cell which I shared in this comment https://github.com/bcylin/QuickTableViewController/issues/23#issuecomment-427616247

I later deleted my Fork since the implementation was unfinished and nobody else had picked it up. Sorry, I didn't know anyone was relying on my fork :). It was never merged into this main project. If you post the code you have from my fork I might be able to help you work on this.

**Comment by getaaron** [comment]
Actually I see it here: [`Settings/Cells/SliderCell.swift`](https://github.com/Provenance-Emu/Provenance/blob/089bce4e4cc25e134ee3843bdceb92976dd5262e/Provenance/Settings/Cells/SliderCell.swift) 

Anyway I can see the opacity is set to minimum of `0.2` here:

https://github.com/Provenance-Emu/Provenance/blob/a5ffa64461f0dde1f93f6c5270c8b34851d25ba2/Provenance/Settings/PVSettingsViewController.swift#L125

So you may want to switch it to `0.5`? I think that should do the trick.
