### ISSUE TITLE
provenance is messing with me with the SCPH-550x bios part

### ISSUE THREAD

**Issue by DarkUmbreon87v3rm** [Provenance-Emu/Provenance#1025]
I was going to play crash bandicoot on my friend, provenance
App told me i need bios (SCPH-5500), i was experimenting a little bit, i had a fearful harmony-corrupted bios, i assumed it was SCPH-5500

I was expecting fearful harmony corruption effect
(if you don't know what that is, here's a video)
https://youtu.be/CxGAhMq_c78?t=45

### Actual:  
Then when i tried to launch crash bandicoot, it said i needed SCPH-5501
then i downloaded non corrupted SCPH-5501, then it said i needed SCPH-5500
### Reproduce:  
1. Get a corrupted/non corrupted psx bios
2. upload to web server
3. then try to launch a psx game

# 
#### NOTES  
(this was a bit of an intentional error.)
#

#### APP VERSION
- [ ] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [x] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

iOS/tvOS VERSION
- [x] Latest (12.0)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x

**Comment by sevdestruct** [comment]
Read the wiki on BIOS requirements. Please read up on Issues Usage while at it.
