### ISSUE TITLE
Did 1.4 changed, I cant manage my library

### ISSUE THREAD

**Issue by falcocerr** [Provenance-Emu/Provenance#1030]
I had not used Provenance And now I cant manage my library directly from my ipad
I used to have the option to see the library, create folders, change files names, things like that, now i dont have that option anymore, i dont know how ill be able to play psx multidisc games..

### Expected:  
I expected to have the option to manage my files as I used to, cant remember the name but its nowhere to be found

### Actual:  
I can do any of those things, settings doesnt have the option anymore

### Reproduce:  
1. Open provenance 1.4
2. Click on settings
3. Look for the manage option

# 
#### NOTES  
Please help out!

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ X] 1.4

#### APP SOURCE
- [ X] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ X] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ X] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [X ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Take these questions to Discord, 1.5 is in development. 1.4 will not be receiving latch upstairs.
