### ISSUE TITLE
PSX games 

### ISSUE THREAD

**Issue by jimiwan** [Provenance-Emu/Provenance#1033]
Hi all

As far as I am aware I am doing everything right according to the instructions. I have managed to play crash bandicoot on ps1, all runs ok and that was a 2 file rom, bin and cue.

However when trying to do any 3 file image no matter what I do it won’t work. Not showing up in the library, not even causing a conflict. When I go into the file structure the files are in the ROMs folder but don’t get moved. To the .com folder. If I move them manually and restart I still don’t get any game in the library. This happens with all 3 file rom sets so it’s something I am doing not the files themselves.

I zip up the img and ccd and then moved the sub across by itself according to the instructions but still will not work. They show again as unzipped once in the rom folder but still no joy.

 I have been at this for days. 

Can anyone help with this as I’m so confused?

Thanks
Jimi

REPLACE_WITH_SUMMARY

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
1.4 is no longer under dev. Multi-disc games have been re-written already in 1.5. If the problem persists in 1.5 built from source you can reopen.
