### ISSUE TITLE
Update installation instructions to recommend recursive clone

### ISSUE THREAD

**Issue by mszaro** [Provenance-Emu/Provenance#1034]
Concerning [the Clone section of the readme](https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance#get-source):

I suggest updating the instructions to suggest a `--recursive` git clone command, e.g. `git clone --recursive https://github.com/Provenance-Emu/Provenance.git`

I suspect there will be a number of non-developers trying to use XCode to sideload this app. The necessity of separately cloning submodules (which appear to exist in the various Cores) is likely non-obvious to them.

**Comment by JoeMatt** [comment]
We have steps for submodules later in the steps either with 'make setup' which does `git submodule update --init --recursive` and in the advanced users section we have this command explicit, but I suppose it doesn't hurt to include it in the clone stage as well to catch ppl who don't read thoroughly.
I went ahead and updated the clone instructions, the .gif will have to be updated later I'm not going to bother.
