### ISSUE TITLE
Official 1.5 fails to load on iPad Air 

### ISSUE THREAD

**Issue by lewis0917** [Provenance-Emu/Provenance#1038]
No official build of 1.5 is working on my iPad Air (model MD789B/A | iOS 11.2.6)

### Expected:  
1.4 signs/installs/loads correctly, so I expected the same for the later versions

### Actual:  
After signing/installing, closes upon launch

# 
#### NOTES  
An unofficial 1.5 build loads just fine…
#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mrjschulte** [comment]
Works fine here when building from source just now, have you followed all of the steps in the Wiki and tried to build this yourself? 

I just did a fresh pull from develop and checked. I'm on iOS 12.1 with a A1474 model iPad Air 1.

**Comment by lewis0917** [comment]
Well it seems to me that every man and his dog is using the “build from source” option, as I’ve been observing on Discord. I don’t have explicit access to a computer. But 1.4 does build successfully via side-loading, as of late.

Perhaps I should share the crash logs?

**Comment by JoeMatt** [comment]
There is no 'official build' of 1.5 and building from source is working fine on iPad Air. Non-issue. Closing.

**Comment by lewis0917** [comment]
Sure! Way to misconstrue the issue I’ve been having…
