### ISSUE TITLE
Snes Super FX games not working

### ISSUE THREAD

**Issue by kyuzumaki** [Provenance-Emu/Provenance#1048]
No SNES games with a super FX chip will load up. All other snes games are working fine.

Not sure if this is just an issue with my build specifically or in general, I've tested all the ones I know of.

**Comment by JoeMatt** [comment]
Why does everyone ignore the fucking issue template.

Which build version?
Which SNES core? (Mednafen or Snes9x)

SuperFX support is compiled into both cores, I'd be surprised if it's not working on both on a valid rom.

**Comment by JoeMatt** [comment]
Did a little troubleshooting,

Mednafen is set to use `snes_faust` via an ifdef. `snes_faust` doesn't seem to support SuperFX. Using regular `snes` module crashes all roms at boot so I need to fix that.

Snes9X runs superfx for Doom but not any others I tested. The difference when init'ing SuperFX is this block of code,
`    if (ROM[0x7FDA] == 0x33)
                SRAMSize = ROM[0x7FBD];
            else
                SRAMSize = 5;
`
Doom triggers the if, the rest go to the else. Not sure what the difference is, I'll have to dig into that.

**Comment by urherenow** [comment]
SRAMSIZE = 5? 5 what? And which sram? Battery-backed saves can be 4, 8, or 16kb. Cartridge sram can be a maximum of 448kb.

No time to look at the code, but just wanted to say that line does look fishy...

**Comment by kyuzumaki** [comment]
Just of note I've tried doom and although it seems to start it hangs after the intro screens have shown

**Comment by robertovg** [comment]
Hey guys, any new information about it? would be nice to be able to play games with Super FX 2 chip like Super Mario World 2 in the Apple TV. Thanks in advance

**Comment by mrjschulte** [comment]
We just merged an updated build of Mednafen and now the Super FX games work again in Provenance when you select Mednafen as the Core to use.

**Comment by robertovg** [comment]
Hey, thank you. I just installed this new version on my AppleTV and `Super Mario World 2` works like a charm!!...

Thanks a lot for this merge, I really appreciate it and your hard work with this project 🙌.

**Comment by mrjschulte** [comment]
Glad it works! Will close this one for now. Feel free to open a new issue if there's a problem.
