### ISSUE TITLE
Some sub-modules missing when doing a clone. 

### ISSUE THREAD

**Issue by Fra-Ktus** [Provenance-Emu/Provenance#1054]
Some sub-modules missing when doing a clone. 

### Expected:  

Some directories are empty:
/Provenance/Cores/Reicast/reicast-emulator

This error message is written in the terminal
Failed to clone 'Carthage/Checkouts/SWCompression/Tests/Test Files'

### Actual:  

After doing make setup and doing the setup in XCode to sign Provenance building fail when compiling Reicast.

### Reproduce:  
1. git clone --recurse-submodules -j4 https://github.com/Provenance-Emu/Provenance.git
2. git clone --recurse-submodules --verbose https://github.com/Provenance-Emu/Provenance.git

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [x] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by fabrijp** [comment]
Looks like this bug comes back
