### ISSUE TITLE
Fix crash in function signature specialization <Arg[0] = Dead> of static PVLibrary.RomDatabase.sharedInstance.getter : PVLibrary.RomDatabase, line 245

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#1060]
### Stacktrace ###

<pre>-;function signature specialization <Arg[0] = Dead> of static PVLibrary.RomDatabase.sharedInstance.getter : PVLibrary.RomDatabase;RomDatabase.swift;245
-;static PVLibrary.PVEmulatorConfiguration.updateSystems(fromPlists: [Foundation.URL]) -> ();<compiler-generated>;0
-;function signature specialization <Arg[0] = Dead> of PVLibrary.GameImporter.(initSystemPlists in _ADD4718E4CBD6D1B016A9D17A2E73A28)() -> ();GameImporter.swift;151
-;PVLibrary.GameImporter.() -> PVLibrary.GameImporter.init() -> PVLibrary.GameImporter;<compiler-generated>;0
-;globalinit_33_ADD4718E4CBD6D1B016A9D17A2E73A28_func155;GameImporter.swift;0
-;PVLibrary.GameImporter.shared.unsafeMutableAddressor : PVLibrary.GameImporter;GameImporter.swift;74
-;Provenance.PVGameLibraryViewController.setupGameImporter() -> ();PVGameLibraryViewController.swift;1427
-;Provenance.PVGameLibraryViewController.viewDidLoad() -> ();PVGameLibraryViewController.swift;1345
-;@objc Provenance.PVGameLibraryViewController.viewDidLoad() -> ();<compiler-generated>;0</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/774573/crash_reasons/257739014](https://rink.hockeyapp.net/manage/apps/774573/crash_reasons/257739014)

**Comment by smpb** [comment]
I can confirm that this crash happens to me on two different devices. One had previous Provenance data, while the other did not. The app does not load on either of them now.
