### ISSUE TITLE
Switch around A/B on Nintendo consoles on bluetooth controllers

### ISSUE THREAD

**Issue by M1staAwesome** [Provenance-Emu/Provenance#1062]
On my SteelSeries Nimbus & iPhone 8 Plus, while playing Nintendo games, B works as A, and vice versa. Any chance that a feature to switch them around for certain system/cores could come in the 1.5 release?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JoeMatt** [comment]
The buttons are mapped to match the original NES control layout on the bottom row and swapped on the top.

https://docs.google.com/spreadsheets/d/1sxgeExnqDg8vdnDHyjjcDbpB0LgOnTwIOFCgaKr2ajU/edit?usp=sharing
