### ISSUE TITLE
MFi Menu Button recalling Pause Menu before dismissing

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#1063]
### Expected:  
Pause Menu is dismissed with MFi Menu dismissed, cleanly.

### Actual:  
Pause Menu dismissal is delayed as it is recalled/refreshed once before dismissing entirely…

### Reproduce:  
1. Connect MFi Controller
2. launch game
3. pause with MFi Menu button
4. dismiss pause menu with MFi button again

# 
#### NOTES  
Witnessed on iPad (iPhone unconfirmed)…
#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

**Comment by dnicolson** [comment]
I think this might be related to the menu/pause button invoking the menu twice and is no longer an issue, can you confirm @cheif?

**Comment by cheif** [comment]
I actually have no idea, I've never seen this issue, but I've also just used MFI controllers with tvOS.

To me this feels safe to close, since it's three years old.
