### ISSUE TITLE
Dreamcast core freezes application

### ISSUE THREAD

**Issue by lifeiscontent** [Provenance-Emu/Provenance#1065]
When exiting a dreamcast game, Provenance freezes

### Expected:  

Provenance doesn't freeze.

### Actual:  

Provenance freezes.

### Reproduce:  
1. load dreamcast game.
2. open Provenance menu to exit game.
3.  exit game and watch it freeze.

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
dreamcast is still wip, we don't need bug tickets until we mark it released.

**Comment by eduo** [comment]
As of two days ago, a libretro core of flycast supporting altjit has been released: https://github.com/flyinghead/flycast/issues/168

**Comment by JoeMatt** [comment]
I'm aware, I already reached out to altstore weeks ago with this same error,
https://github.com/flyinghead/flycast/issues/168#issuecomment-894751294

This ticket is closed and wouldn't have been the right one, either way, there's a ticket just for adding Dreamcast, please don't bump closed tickets.
