### ISSUE TITLE
Upcoming Xcode 10.2 breaks building from source compatibility

### ISSUE THREAD

**Issue by 0Shorty0** [Provenance-Emu/Provenance#1071]
When XCode 10.2 is installed, make setup process fails at compiling dependencies, due to Swift Version 4. Xcode 10.2 requires >= version 5
Make Setup ends with: "Incompatible Swift Version"

 
### Expected: 

No error, no cancellation, valid make-process

 
### Actual: 

Error on compiling dependencies - Invalid Swift version, required >= version 5

 ### Reproduce:  

1. Git clone master 
2. Install Xcode 10.2 beta
3. use cmd-tools of Xcode 10.2 beta
4. Do make setup

# 
#### NOTES  

pls Update Swift Version. 

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
X ode 10.2 and swift 5 are still pre-release betas. They are not public releases. We won’t update the tool chain until it public.
