### ISSUE TITLE
Directional Key on PSX rom stucked on UP button

### ISSUE THREAD

**Issue by highimn8** [Provenance-Emu/Provenance#1072]
### Expected:  
Smooth directional keys on PSX on-screen control

### Actual:  
Stuck on UP button

### Reproduce:  
1. Load PSX rom e.g. Resident Evil 3
2. Start the game
3. Play with directional key stuck on up button

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
this sounds like an old bug that has been fixed. old build? that's my guess.

**Comment by sevdestruct** [comment]
Sounds like #988 and #826. Since fixed. Update your build. Bug reporting against the beta requires being current.
