### ISSUE TITLE
Load state not working

### ISSUE THREAD

**Issue by bishnagels** [Provenance-Emu/Provenance#1075]
I have created a GitHub just for this thread, save states can be created and work fine but I can not load them at all. When I open the load state menu and select the save I want to load nothing happens at all

REPLACE_WITH_SUMMARY

### Expected:  
Load state to function

### Actual:  
Load state doesn’t work

### Reproduce:  
1. Create save state
2. Attempt to load it
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ yes] 1.4

#### APP SOURCE
- [yes ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ yes] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ yes] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ yes] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
we won't be releasing patches to 1.4. this is fixed/working in 1.5.
