### ISSUE TITLE
Fast forward button on ui ?

### ISSUE THREAD

**Issue by Wh0ba** [Provenance-Emu/Provenance#1080]
REPLACE_WITH_SUMMARY

### Expected:  
a button to quickly toggle fast forward mode (unthrottle) 

### Actual:  
you have to open up the menu and then open the sub menu to select the speed to do so 

### Reproduce:  
1. Start a game 
2. open the In game menu 
3. tap on speed 

# 
#### NOTES  

This is OK but it gets really annoying in games like Pokémon and final fantasy (gba,snes) because the slow turn based mechinacs make it really hard to do it keep with the game 
Other emulators like gba4ios also placed the fast forward button in the in game menu but you only have to tap once to activate it 
Also GBA.emu allows for a fast forward button with the game controls which is a time saver 
I wish you can do this in Provenance which will make it really better than the other emulators specialy in the game play experience 
And thanks 

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*
  - [x] Hokey App builds
#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [x] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Please review existing issues before posting: #redesign

**Comment by sevdestruct** [comment]
Please review existing issues before posting: #718,  #999.
