### ISSUE TITLE
Turok 2 N64 crashes every 15-20 mins

### ISSUE THREAD

**Issue by lewis0917** [Provenance-Emu/Provenance#1085]
REPLACE_WITH_SUMMARY

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Closed. Assuming this is an upstream issue unless some data specific to Provenance is submitted.

**Comment by urherenow** [comment]
Don’t crashes based on time indicate a memory leak?

**Comment by james-rantmedia** [comment]
Sometimes, but not always. Also @lewis0917  hasn't provided any crash log or anything to suggest whether the issue is with Provenance itself or the N64 emulator implementation used within Provenance.

**Comment by lewis0917** [comment]
As of build 2770 this is no longer an issue.
