### ISSUE TITLE
Mocute 054 not working on n64 (icade mode)

### ISSUE THREAD

**Issue by cyberphoenix** [Provenance-Emu/Provenance#1086]
The controller mocute 054 are not working on iphone (icade) mode for n64 emulator . It was detected but i think control mapping need to be add. -sorry i’m french-

**Comment by JoeMatt** [comment]
I can't find any documentation that says the 058 supports iCade mode.

**Comment by cyberphoenix** [comment]
Sorry mocute 054

**Comment by sevdestruct** [comment]
@cyberphoenix: isolated to N64 or all systems?
