### ISSUE TITLE
Errors when trying to build

### ISSUE THREAD

**Issue by mattomeara5150** [Provenance-Emu/Provenance#1089]
replaceWithSummaryOrDelete

 
### Expected: 

replaceWithExpectedResults

 
### Actual: 

replaceWithActualResults

 ### Reproduce:  

1. replaceWithSteps
2. 
3. 

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mattomeara5150** [comment]
I'm kinda new to Xcode and sideloading so please bare with me. 
I am getting the below errors when trying to build to my Apple TV device

<img width="1047" alt="Screen Shot 2019-03-20 at 12 57 28 pm" src="https://user-images.githubusercontent.com/29084145/54653794-02337f00-4b10-11e9-8366-d52df54735c6.png">

**Comment by urherenow** [comment]
You’re not following the guide... you need to change signing back to what it was... some gibberish... then go to the capabilities tab and turn off icloud, app groups, siri, and whatever else it’s complaining about. THEN you can change signing to automatic and pick your own account.

**Comment by sevdestruct** [comment]
Thanks @urherenow. Stick to the guide, Hit us up on Discord if you need help.
