### ISSUE TITLE
Correct wiki for Building Source

### ISSUE THREAD

**Issue by urherenow** [Provenance-Emu/Provenance#1093]
The wiki for Installing needs a quick fix, but I don't know how to submit a pull request for a wiki.

Building Source, steps 3 i. and 3 ii. are in reverse order. You must complete ii. before doing i.

**Comment by sevdestruct** [comment]
@urherenow Actually if you reverse that order, free dev users won't be able to see certain Capabilities and won't be able to turn them off. This order was previously changed to avoid that issue.

**Comment by urherenow** [comment]
3 ii is the step to turn off the capabilities. I’m saying that should be done FIRST, because of the reason you already gave.

And perhaps I was confusing changing the name with selecting the team.
