### ISSUE TITLE
1.5 Import Extension errors

### ISSUE THREAD

**Issue by MysticalOS** [Provenance-Emu/Provenance#1096]
using very latest development build, all rom imports fail with same error

Metroid 2 - Return of Samus.gb doesn't matching any known possible extensions and is in Imports directory. Deleting.

Metroid - Zero Mission (U) [!].gba doesn't matching any known possible extensions and is in Imports directory. Deleting.

Metroid-156.nes doesn't matching any known possible extensions and is in Imports directory. Deleting.

Super Metroid (JU) [!].smc doesn't matching any known possible extensions and is in Imports directory. Deleting.

As you can see all 4 of those have valid extensions but as far as 1.5 is concerned it has no idea what any extension is and invalidates all of them. 1.4 stable release doesn't have this problem. It's definitely a 1.5 issue.

Going to test with a 1.5 dev version earlier than https://github.com/Provenance-Emu/Provenance/commit/1e204f7245788adcb995249a86c4183a3f17ff3f and see if that resolves it.

Yep, rolling back to before this commit fixed issue. importing works again. Build 2706 no issues

**Comment by MysticalOS** [comment]
Update, I wiped everything clean and did a clean side load of same ipa and importing worked better (minus dropping first rom every time)

**Comment by JoeMatt** [comment]
The UI doesn't render always on the first imports. Restarting or going to settings and back fixes this, you might have been experiencing that. Or maybe a bug with iCloud file system. Going to close this for now as it seems like it was a single user experience issue since no one else has reported a problem.
