### ISSUE TITLE
SABR Filter Support

### ISSUE THREAD

**Issue by MysticalOS** [Provenance-Emu/Provenance#1099]
The SABR filter is by far the best one in OpenEmu. It's the natural successor to HQ(number)x filters. 

Apple hardware continues to grow in power and honestly the higher demand filters are a no brainer at this point. Creating a new ticket for this since old filter tickets were closed and it was proposed any new filter should be a new ticket if unrelated to an existing ticket.

Existing filters are a start, but they just hold no candle to SABR on most games. There are only a few game exceptions SABR doesn't look good on.

 

If SABR harder to do, HQX would probably be next best alternate

 
Below you can see a comparison that really just makes some games feel like entirely new games. The SABR shot almost looks like a professional remaster.
![no_filter](https://user-images.githubusercontent.com/1899149/55893416-32f25b80-5b86-11e9-9590-db9d35692b30.jpg)
![sabr](https://user-images.githubusercontent.com/1899149/55893432-384fa600-5b86-11e9-937e-e75434ee0263.jpg)

**Comment by JoeMatt** [comment]
We have a filters ticket - #743

**Comment by JoeMatt** [comment]
Not sure what ticket this is in, but there's a ticket somewhere with the plan to try to port the GFX pipeline to use retroarch filters. This depends on a few other tickets.

GitHub's ticket dependency is horrendous. We're probably moving not Jira soon. I don't want a ticket per filter in GitHub. This is now linked to #743 #368 etc. We can add notes to better tickets in the future. I'm taking a week off of work soon I'm going to be working on the app and our tickets then.
