### ISSUE TITLE
Download server not working

### ISSUE THREAD

**Issue by Cubemagnet** [Provenance-Emu/Provenance#1111]
So when i go to the download server to download roms. I tried it out by downloading ocarina of time. I was able to import it, but when i checked the app, it wasn't there. And when i did import it and pressed the download button next to it, this happens
![image](https://user-images.githubusercontent.com/49451504/56853280-8b9a5600-68f3-11e9-900b-c5d2eb542abb.png)

#### APP VERSION
- [ ] 1.5 *beta*
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
We are aware. Not a bug regarding app. Please use Discord. New site will be up. Links to prebuilt prerelease .ipa in Sideloading Install wiki.
