### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by CoderTonyChan** [Provenance-Emu/Provenance#1124]
error: Build input file cannot be found: '/Users/tonychan/Desktop/TonyChan/Provenance/Cores/Reicast/reicast-emulator/core/deps/libzip/zip_unchange_data.c'

**Comment by jasarien** [comment]
Looks like you didn’t update the submodules. Please read (and re-read) the guides in the Wiki, and then join the Discord and ask there before creating issues like this.
