### ISSUE TITLE
PVReicast

### ISSUE THREAD

**Issue by xdccrlz** [Provenance-Emu/Provenance#1126]
Latest working core PVReicast was in the Provenance 2768. Starting with version 2770 PVReicast installs but does not start. Approval is valid for iOS and tvOS.

**Comment by kudoshinka** [comment]
can you help me play soulcalibur in provenance 2768 , it's can boot bios , but after bios done , app crashed

**Comment by xdccrlz** [comment]
Try to edit emu.cfg and use recommended bios.  https://forums.libretro.com/t/download-retroarch-1-7-5-ios-11-ios-12-ipa-extras-updated-v3/18955/18?u=xdccrlz

**Comment by JoeMatt** [comment]
There's a bug in PVReicast where it reads the bios and .cfg from the same folder a the save states for the rom, so you have to copy the bios to each folder, this is why PVReicast is not published as working.

**Comment by JoeMatt** [comment]
Soul Calibar is the rom i use to test with, it does boot and run at full speed but PVReicast is BROKEN all  together. The CPU/GPU timings are all off and there's audio and gfx sync issues, games run too fast etc. 

There have been many updates in reicast in general, but I haven't had time to forward port the imporvement from both the main repo and libretro's, apparantly iOS working, port. Though I haven't tested either of their projects recently either.

There's also an issue that Reicast uses different clocking code for jailbreak vs non jail break, so it's entirely possible that libretro requires a jailbroken device to work, assuming it does. I haven't investigated much. Been way to busy but I'll eventually visit this all.

The plan is to generalize the way we wrap libretro compatible ports and move to sub-packages for cores, probably using the updated Swift Package Manager that now works for iOS in XCode 11.

This should help, but it's months from release so don't hold your breath.

**Comment by JoeMatt** [comment]
This isn't a bug, closing. For help with betas use Discord.
