### ISSUE TITLE
crash ios 13

### ISSUE THREAD

**Issue by saeidselfjoor** [Provenance-Emu/Provenance#1127]
sorry I don’t use github and this is my first report
I use latest beta on ios 13 but when I import roms
they doesn’t appear to library no matter how many times I reinstall provenance I try four version any tip?

**Comment by xoniq** [comment]
For me it helped to open settings on the app and close it again to make it reload the roms overview.

**Comment by saeidselfjoor** [comment]
even I see roms some how 
game crash immediately after I tap on icon

**Comment by saeidselfjoor** [comment]
I try few sega genesis games non of them work

**Comment by xoniq** [comment]
I haven't tried SEGA, only GBA, SNES, PSX and N64.

**Comment by saeidselfjoor** [comment]
can you try one please

**Comment by xoniq** [comment]
I just tried two random games, Sonic and Lion King, both working perfectly. Played them a whole to test, imported one as zip file and one as smd file. No problems.

**Comment by saeidselfjoor** [comment]
good can you send ipa you used please ,

**Comment by xoniq** [comment]
I can't, I build from source, directly to my phone from Xcode. Have you tried a dev build? Or only a release build?

**Comment by saeidselfjoor** [comment]
no I tried latest dev build (1.5 beta latest version )2602 , 2768,2770

**Comment by JoeMatt** [comment]
iOS 13 is in developer-only beta - not tested, not supported.

Unless you're working on patches, you can open a WIP pull request. Otherwise please take the discussion on non-bugs (unsupported iOS versions) to Discord.
