### ISSUE TITLE
Logitech Powershell stops working now and them

### ISSUE THREAD

**Issue by twolfer** [Provenance-Emu/Provenance#1128]
replaceWithSummaryOrDelete

 
### Expected: 

replaceWithExpectedResults

 
### Actual: 

replaceWithActualResults

 ### Reproduce:  

1. replaceWithSteps
2. 
3. 

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
No information. Closing.
