### ISSUE TITLE
Logitech Powershell stops working intermittently

### ISSUE THREAD

**Issue by twolfer** [Provenance-Emu/Provenance#1129]
Controller works intermittently

 
### Expected: 

Controller working during the game for more than 30 seconds.

 
### Actual: 

Stops working suddenly, sometimes resumes after a few seconds (my character dies sometimes during that process)...

 ### Reproduce:  

1. Place iPhone In controller
2. Be on iOS 12.1.2 (Jailbroken in my case)
3. Play any game for more than 60 seconds

# 
#### NOTES  

Tried it on both 1.4 and 1.5 beta.
I’m on iOS 12.1.2, iPhone SE 32gb, latest Unc0ver jailbreak.

It works fine, suddenly in less than 30/60 seconds running, it stops working. I press all the buttons, wait a few seconds and sometimes it works again.

In some cases I have to remove the phone from the controller and place it back again. This doesn’t happen with AppStore games, only with the emu.

PS: thank you for this outstanding emulator, it’s as precious as invaluable for a classic gamer.
( ๑❛._❛ )

#

#### APP VERSION
- [x] 1.5 *beta*
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by twolfer** [comment]
Apologies for my previous post, the checkboxes were not showing up on the phone browser and I took to long to format my text to the bug report format. When I was done, it was already closed.

**Comment by Corey-Evans** [comment]
Is this still an issue? I’m thinking about picking up the controller.

**Comment by twolfer** [comment]
I have a new device (same model) on iOS 12.4 now, will try again.

**Comment by twolfer** [comment]
Just tested it, new bugs. 
Jumps from controlling player 1 to 2 suddenly, keeps player running to the right (handy for Sonic 2, unplayable for anything else). 
;D

But buy the controller, it works flawlessly in some Appstore games (all classic sonics). Under £10 on Amazon/Ebay.

**Comment by sevdestruct** [comment]
I have one of these for testing, will report back on this, but mine has worked fine @twolfer - head to Discord to discuss.

**Comment by JoeMatt** [comment]
closing since this seems like a 1 off. We don't have custom code for these types of controllers.
