### ISSUE TITLE
[FR] iOS 13 XBoxOneS and PS4 controller support.

### ISSUE THREAD

**Issue by yixiang** [Provenance-Emu/Provenance#1130]
Context: 
https://www.apple.com/ios/ios-13-preview/features/
https://www.youtube.com/watch?v=Zfk02F92g5w

**Comment by xoniq** [comment]
PS4 controller is perfectly working with Provenance 1.5 on iOS 13 and tvOS 13.

What do you want to see changed?

**Comment by tosh** [comment]
Xbox One S controller also seems to work for me (tested w/ Provenance 1.4)

**Comment by JoeMatt** [comment]
Seems it's supported through standard MFi extended which we have in 1.5 beta. Closing unless there's additional features to add you can reopen with specific additions.

**Comment by timemaster5** [comment]
Hi, the ps4 controller works fine on tvos13 except entering the menu from a running game. PS button press causes two actions at once. Provenance shows the game menu (save, exit, press select, press start) but at the same time, it triggers the tvos13 user profile selection menu together with application switcher.
Also, as PS4 has many free buttons, some of them could be used as a native start and select buttons if possible.
