### ISSUE TITLE
Not working with iOS 13 beta! (iPAD Pro 10.5)

### ISSUE THREAD

**Issue by Perenis** [Provenance-Emu/Provenance#1132]
The app doesn't work for the iOS 13 beta, for the iPAD Pro 10.5. I mean, even after we upload the files the Provenance (iOS) app doesn't open them, and can't display any of the locally stored files in the list. All we get is a blank screen with the app, as if we had not uploaded anything there. I tried to open manually and even after that it didn't work. Most likely this isn't compatible with iOS 13 beta.

 
### Expected: 

That it would work.

 
### Actual: 

The app doesn't work for the iOS 13 beta, for the iPAD Pro 10.5. I mean, even after we upload the files the Provenance (iOS) app doesn't open them, and can't display any of the locally stored files in the list. All we get is a blank screen with the app, as if we had not uploaded anything there. I tried to open manually and even after that it didn't work. Most likely this isn't compatible with iOS 13 beta.

 ### Reproduce:  

1. Upload your device to iOS 13 beta
2. Upload any rom to Provenance
3. Try to use the app.

# 
#### NOTES  

Explained above.

#

#### APP VERSION
- [ ] 1.5 *beta*
- [X ] 1.4

#### APP SOURCE
- [X ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ X] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ X] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ X] 13 beta
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
iOS 13 is not yet supported.

**Comment by JoeMatt** [comment]
Also iOS 13 will never be supported on 1.4. Dev on 1.4 is no longer being done. And don't open a 1.5, there's already been and closed. We don't make tickets for things that are in beta. It's just clutter
