### ISSUE TITLE
Customizeable Touch/Overlay Control Position/Size

### ISSUE THREAD

**Issue by oliviercharavel** [Provenance-Emu/Provenance#114]
**Redacted/Deprecated:**
~~Right now, it's only possible to move the D-Pad and the main controller buttons (A, B, ... for example). It would be fantastic to also be able to move the shoulder buttons (L & R for example), Start & Select buttons as well as the menu button to make it easier to play on iPad (especially with the new and great portrait mode).~~

Thank you for your great work. 👍

**Comment by jasarien** [comment]
Yeah probably a good idea. Can't remember why I didn't include the other controls before...

**Comment by charlestruluck** [comment]
This would be nice for TV as well, seeing as there is only the DPad and X currently.

**Comment by jasarien** [comment]
AppleTV doesn't have onscreen controls.

**Comment by charlestruluck** [comment]
My mistake, I thought it was customizable controls as in what each button does instead of how they look.

**Comment by T-Will** [comment]
I'm using the Nimbus controller with the Apple TV, but the A/B buttons are swapped from the original NES controller. Would it be possible to add a setting to customize the button mapping?

**Comment by jasarien** [comment]
@T-Will, this issue is about editing the positioning of on-screen controls. There is a separate issue for physical controller mapping: #56

**Comment by goft20** [comment]
Will we ever be able to resize and move the buttons around? Thanks!

**Comment by legomeaker101** [comment]
how do you move and rezise controlls?

**Comment by chileCC** [comment]
Hey I'm extremely curious as it's been two years since this and the button pad schemes haven't been fixed. Any updates to let us know you've been in progress..?
Really disheartening when you don't have a Bluetooth controller to make it easier and the buttons and l and r for snes are disproportionate. Especially on landscape. Not about to play portrait and see a tiny image , worse than the gameboy screen size.

**Comment by sevdestruct** [comment]
I am working on on an overhaul of all overlays(#718 for 2.0) which I aim to improve quite a bit. This reminds me I need to do a pass for iPad at some point, but should work with what I am pursuing. It doesn't include this but might lesson the need a lot, and then we can see about if we still want this.

**Comment by sevdestruct** [comment]
redundant of #25 …
