### ISSUE TITLE
'_ArrayInStructT' does not refer to a value

### ISSUE THREAD

**Issue by dengcqw** [Provenance-Emu/Provenance#1143]
In file included from /Users/dengjinlong/Documents/Provenance/Mednafen/mednafen/tests.cpp:30:

In file included from /Users/dengjinlong/Documents/Provenance/Mednafen/mednafen/hash/sha1.h:4:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/array:254:19: error: '_ArrayInStructT' does not refer to a value

    _ALIGNAS_TYPE(_ArrayInStructT) _CharType __elems_[sizeof(_ArrayInStructT)];
                  ^

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/array:253:13: note: declared here

    struct  _ArrayInStructT { _Tp __data_[1]; };
            ^
------------------------------------------------------------------

compile PVMednafen framework error,   this seems like a c++ lib error

macOS 10.14.3
Xcode 10.2.1

**Comment by tgwaste** [comment]
Any word on this error?  This prevents a successful compile.

**Comment by JoeMatt** [comment]
I haven't had time to look, but we haven't updated mednafen in many months, not sure why a compilation but would show up out of the blue.

**Comment by JoeMatt** [comment]
tests.cpp might not even be required, try deselecting it from the target?

**Comment by tgwaste** [comment]
Apologies, I'm not quite sure where that is.

**Comment by tgwaste** [comment]
![Screen Shot 2019-07-17 at 9 11 11 PM](https://user-images.githubusercontent.com/690918/61428568-7ff97280-a8d7-11e9-9dfe-36b6b00c674b.png)
I also dont see reference to that here.

**Comment by AlexRablau** [comment]
I attempted to compile the master branch today and had the same issue.

**Comment by stdroy** [comment]
I got the same problem,  have you figure it out ?

**Comment by AlexRablau** [comment]
No. I ended up side loading the prebuilt .ipa file. I hope this issue is resolved soon.

**Comment by procommerz** [comment]
That's a bummer... Excluding tests.cpp from the build doesn't help, as the error comes from c++/v1/array Xcode llvm infrastructure include folder via sha256.h. Understandably, sha256 cannot be simply excluded from the build. Since none of the files with errors can be edited under normal circumstances, I can only guess that newer Xcode requires some additional compiler options to compile this properly.

**Comment by procommerz** [comment]
The same code compiles and links without errors on Xcode 9.4.1 (but fails with the cryptic error on Xcode 10+). Obviously, you cannot deploy from Xcode 9 to latest iOS...

**Comment by Sebastianos79** [comment]
Hi.
Some one a solution already?
I'm new with Xcode on my macbook, and also tried to install convenance to my apple tv4. same error.
also tried older versions (10.4 and 11) of Xcode from apple, but same error. 
Hope someone have found the solution, i want to install / use the good old nintendo games.

**Comment by procommerz** [comment]
@Sebastianos79 See above, you need Xcode version 9.4.1 (it can be found somewhere in the depths of their Development Portal), archive the **Release** build (Debug build won't build/deploy still) and then deploy the archive with your latest Xcode.

**Comment by Sebastianos79** [comment]
I did trad that post, because i’m a newbee i dont have any idea how that works. I used a manual to set the good settings earlyer.

**Comment by Sebastianos79** [comment]
Version 9.4.1 doesn’t work @ macOS Catalina version 10.15.2 :(



Please more suggestions?

**Comment by Sebastianos79** [comment]
Hi guys, I googled again en fount a similar error.
I'm not a programmer, but could it be something like this?
https://stackoverflow.com/questions/44417995/c-iterator-error-does-not-refer-to-a-value

look at the bottom of that page ;)

**Comment by Sebastianos79** [comment]
[tests.cpp.zip](https://github.com/Provenance-Emu/Provenance/files/4061361/tests.cpp.zip)
here's the file with (I think) has the issue

**Comment by stevesioli** [comment]
I was able to resolve this issue by editing `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/array` at `line 254`

`struct _ArrayInStructT` is nested and trying to be used directly, which apparently the compiler does not like.  Making the struct a static member with a reference (I just called it `var1`) resolves the issue above.

```c++
static struct  _ArrayInStructT { _Tp __data_[1]; } var1;
_ALIGNAS_TYPE(var1) _CharType __elems_[sizeof(var1)];
```

I had to `sudo` edit this file isn't really advisable, but it worked in a pinch.  I plan on hunting down the source code of this lib and submitting an issue against it.

After doing this, I was able to successfully compile and build using Xcode 11.x and running it on a simulator running tvOS 13.3.  I need to download the 13.4 SDK so I can try building to my physical device.  I will update my comment once I do so.

**Comment by Sebastianos79** [comment]
Perfect! I Will tot it soon! Thx for this awesome update Steve!

**Comment by Sebastianos79** [comment]
butt stil multiple errors.. about opengl.framewok or something, to replace it wit metal.framwork
fixed some of them and after that I receive var1 error :(

**Comment by dnicolson** [comment]
I think this can be closed as the master branch is very out of date, the develop branch does not have this error.
