### ISSUE TITLE
Cannot sideload beta version with impactor?

### ISSUE THREAD

**Issue by Elronnd** [Provenance-Emu/Provenance#1146]
BUG REPORT:
When I try to sideload the beta version (from [here](https://builds.provenance-emu.com/iOS/Latest/Develop/)) with cydia impactor, I get an error of

    Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.eIjBtH/extracted/Payload/Provenance.app : 0xe8008016 (The executable was signed with invalid entitlements.)

The stable version works fine, as do other apps.  It's not because of the three-app limit; this was the first app I tried installing.

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x

**Comment by JoshuaHolme** [comment]
Can confirm I am also having this issue with iOS App signer as well. Am able to sign the stable version fine (1.4) but can sign any of the beta versions.

**Comment by gh0sti** [comment]
it's because Joe's developer account which was used to compile it was banned by apple, you need to use app signer to switch it to using your own dev account and then you can use impactor to sideload.

**Comment by JoshuaHolme** [comment]
Even after resigning it with App Signer and trying to side load it with Xcode through the `Devices and Simulators` window, it doesn't work. Do you have to use impactor specifically to side load it?

**Comment by Elronnd** [comment]
I don't have macos; is there any other way to switch the dev account?  Also, why are those ipas signed at all?

**Comment by JoeMatt** [comment]
That's got nothing to do with it. We can't provide any help for Cydia. Follow the wiki or ask for help on discord. Please leave Bug reports for actual bugs. If we said we supported cydia officially then this would be a bug, but we don't, so this isn't.
