### ISSUE TITLE
After some time Provenance stops working on apple tv and all save files are deleted.

### ISSUE THREAD

**Issue by crookedbard** [Provenance-Emu/Provenance#1163]
After some time Provenance stops working on apple TV. I reinstall it and then it starts working again, but the save files are gone. Is it possible to store save files in the cloud? 

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x

**Comment by gduranon** [comment]
Same here

**Comment by JoeMatt** [comment]
This is a known issue with Apple TV. Everything is stored in caches by default.

App store apps are supposed to sync to iCloud, but we can't. Until we add a 3rd party sync solution, you need to periodically manually backup saves and self restore following instructions in the wiki
