### ISSUE TITLE
Make start button more responsive on iPhone X

### ISSUE THREAD

**Issue by tgwaste** [Provenance-Emu/Provenance#1164]
The start button is extremely hard to press on iPhone X(S). Probably because of the Home Bar. Anyway to move those buttons up a bit?

![6D481BD8-FE40-4352-918B-BEC3D09C4F1D](https://user-images.githubusercontent.com/690918/62993402-01c3b980-be0c-11e9-9a0c-e52a3b0dac54.jpeg)

**Comment by tgwaste** [comment]
PS there is an option somewhere to code the bar away. I forget how though.

**Comment by calfzhou** [comment]
I tried to click the "start" button this whole afternoon. Almost impossible.

**Comment by sobodash** [comment]
I find it slightly easier to click in landscape mode. The bigger problem is L1 and R1. I cannot touch those for the life of me without bringing down one of the docks.

Should have an option to just offset all control elements by n* pixels. That would let people move everything to where their fingers can reach it without triggering iOS UI elements.

**Comment by sevdestruct** [comment]
this is 1.4, which has been completely revised in 1.5 - not relevant.
