### ISSUE TITLE
8bitdo Zero support for 1.4

### ISSUE THREAD

**Issue by Grandtheft430** [Provenance-Emu/Provenance#1166]
As i described in the end of #582 , Provenance 1.4 doesn't support 8bitDo Zero controller correctly - wrong button mapping. However, this was not the case anymore in the following 1.5 betas; it worked fine with right button mapping.

One issue though - it **is** still the case on 1.4 Provenance which is the latest version my older iPad Mini 1st gen supports (well, 1.5 is for iOS 10 and newer i guess, and iOS 9.3.5 is the latest iOS for this iPad). So is there any way to update 1.4 to properly support Zero controller (1.4.1 mb?). Hope it's not as difficult since it's already implemented in newer version.

Thanks in advance and sorry for the language.

**Comment by sevdestruct** [comment]
1.4 will not be getting subsequent updates. Much work has been done to address controller input default remap, etc effort in 1.5 - and will continue in 1.5.x subsequent updates or later: 1.6, 2.0…
