### ISSUE TITLE
Provenance PSX Parasite Eve

### ISSUE THREAD

**Issue by apy1985** [Provenance-Emu/Provenance#1178]
So far, I’ve been playing provenance (on my iPad mini) for about two weeks and it’s been smooth sailing. I downloaded Parasite Eve a few days ago and put it into a m3u and it loaded up. But when the game starts at the main menu I can’t use the dpad at all. The other buttons (start, select, x, circle, triangle, square) work fine. I re-downloaded the rom and re-installed it but the dpad still doesn’t respond. Any help is welcomed!
Thank you!!

#### APP VERSION
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by revo8111** [comment]
Same here. It seems that any psx games is still not playable with provenance at all. That’s because there is an error in the mednafen core for the analog inputs. The only way to obtain a provenance version with the right mednafen core is with cydia impactor, at the moment, because all the 3rd parties installer like app valley and similiar, are using the old mednafen core (1.2.1). Sad

**Comment by silk810** [comment]
> Same here. It seems that any psx games is still not playable with provenance at all. That’s because there is an error in the mednafen core for the analog inputs. The only way to obtain a provenance version with the right mednafen core is with cydia impactor, at the moment, because all the 3rd parties installer like app valley and similiar, are using the old mednafen core (1.2.1). Sad

So where can I get provenance versions with the right mednafen core?

**Comment by sevdestruct** [comment]
Pretty sure this was fixed. #1012 Update to latest beta from official source. Use the install wiki. Discss on Discord.
