### ISSUE TITLE
GameCube/Wii/N64 Virtual Console Core: Dolphin

### ISSUE THREAD

**Issue by Human1895** [Provenance-Emu/Provenance#1180]
https://github.com/dolphin-emu
https://github.com/WilliamLCobb/GC4iOS

**Comment by A-Human-Person** [comment]
as a base GC4iOS is a good start

**Comment by sevdestruct** [comment]
Editing…

**Comment by JoeMatt** [comment]
Closing duplicate of #182 and linked project GC4iOS notes,

> Please note this is an early alpha version. Without JIT, the emulator will not be fast enough to play any games at a playable speed.

That's as of 2016, the last update that project has seen.
