### ISSUE TITLE
Steam Controller not recognized

### ISSUE THREAD

**Issue by aaiezza** [Provenance-Emu/Provenance#1187]
I see great support in the Wiki for Steam Controller support.
I've managed to connect my Steam Controller easily, however, Provenance does not seem to recognize it in the controller selection. Only my Nimbus.

 
### Expected: 

Steam Controller to show up in controller selection if connected via bluetooth.

 
### Actual: 

It was not there.

 ### Reproduce:  

1. Connect Steam Controller to iPhone XS. (Either with Steam+Y via the SteamLink app, or Steam+X for regular bluetooth).
![image](https://user-images.githubusercontent.com/8107121/64707773-1cc03280-d479-11e9-9d66-293338f163cc.png)
I tried both methods and both result in an additional device called `SteamController` in my bluetooth device list on the iPhone.
2. Open Provenance and from Settings, go to Controller Selection.
3. Select a Player (Player 1) and a list should display of bluetooth devices compatible for play. SteamController is absent however.

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [X] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [X] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [X] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [X] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [X] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Have you installed the correct firmware to your steam controller? Worked on this a bit with @zydeco and I've tested mine and all worked, prior to iOS13. Will need to do a current test run. Might be worth checking out the status of the source project https://github.com/zydeco/SteamController.

**Comment by zydeco** [comment]
I've just tested building from the current develop branch (build 2770), and it shows "Steam Controller" by default as Player 1, on iOS 12.1 and 13.3, and I was able to play with it.
If you're using iOS 13, have you enabled bluetooth access for Provenance, in the iOS Settings? It should ask for it the first time you open it.
