### ISSUE TITLE
Crash on launch on Apple TV - HockeySDK

### ISSUE THREAD

**Issue by allemattio** [Provenance-Emu/Provenance#1192]
Hi, me and a friend of Mine have the same problem with Provenance on Apple tv.
We are both using Xcode 11 final, I am on tvOS 12 and he is on tvOS13 GM. The app crashes on launch and the log say this:
```
dyld: Library not loaded: /System/Library/Frameworks/QuickLook.framework/QuickLook
  Referenced from: /private/var/containers/Bundle/Application/CA2C4BED-97FB-4575-9758-537C9EE0C214/Provenance.app/Frameworks/HockeySDK.framework/HockeySDK
```
is this a known issue? I followed the install guide step by step and I was starting from scratch, I cloned the project to build it
I followed the build guide at this page: https://wiki.provenance-emu.com/

**Comment by Shayanzadeh** [comment]
Ah figured it out, you're not able to link QuickLook.framework with tvOS (it's not available) so I had a feeling the HockeyAppSDK being used must be the iOS one (where QuickLook *is* available).

Looks like [this commit](https://github.com/Provenance-Emu/Provenance/commit/13af8ca63eb5d71b487805e38a2ff4cdc3286ae2) 

You need to change the paths from `$(SRCROOT)/Carthage/Build/iOS` to `$(SRCROOT)/Carthage/Build/tvOS` for all the lines in ProvenanceTV-inputPaths.xcfilelist.

Looks like [this](https://github.com/Provenance-Emu/Provenance/commit/13af8ca63eb5d71b487805e38a2ff4cdc3286ae2) regressed [this](https://github.com/Provenance-Emu/Provenance/commit/3e75e6bf8e63a4c8ac4eb9ff7d5aa2b262e844a6)

**Comment by allemattio** [comment]
I confirm that it worked, now the app works on Apple TV with tvOS13 on Xcode 11
