### ISSUE TITLE
Back out to menu from within loaded ROM content?

### ISSUE THREAD

**Issue by peanutismint** [Provenance-Emu/Provenance#1201]
Is there any way to get back out to the main menu from within a ROM?  or do we just have to quit it and re-launch??

**Comment by MemesDank456** [comment]
If you're using a ps4 or xbox one controller with tvOS 13, you can press the Xbox/PS button to enter the control center, which pauses the game. I really wish they added proper Xbox/PS controller support (so start and select actually do something) but for now that will have to do

**Comment by peanutismint** [comment]
Unfortunately I’m not using either of those controllers or tvOS 13, but the controller I am using (an 8bitDo SF30 Pro) does have a home-type button, but it doesn’t do anything… Wish there were some options to configure controls etc.

**Comment by sevdestruct** [comment]
@peanutismint last I recall that controller isnt even supported on tvOS even trying the deprecated drivers for 8bitdo.. would like to know how you got it to work at all. Jump over to discord to discuss. Closing this as it can be added to #741 ticket if needed.
