### ISSUE TITLE
Pre-release build URL is down

### ISSUE THREAD

**Issue by apstygo** [Provenance-Emu/Provenance#1208]
The pre-release URL found in official installation guide has been down for at least a couple of days now. 
URL: https://builds.provenance-emu.com/

**Comment by silk810** [comment]
It’s still down. Can someone recover this? Come on guys...

**Comment by sevdestruct** [comment]
Not an app bug. We're working on it. In meanwhile… Links for prebuilds are in the wiki and on Discord.
