### ISSUE TITLE
Mac Catalyst, mac OS Catalina support

### ISSUE THREAD

**Issue by jlippold** [Provenance-Emu/Provenance#1209]
Since macOS Catalina was released, it also brings the option to run apps built for iPads on the mac. It's called [Mac Catalyst](https://developer.apple.com/mac-catalyst/). I have an iMac in my home, that runs apple arcade with game controller support and thought how great it would be to have Provenance running side by side.

I imagine this could be a big endeavor (although apple makes it sound really easy), but I was curious if the devs would be looking into it.

Thanks :-)

#
 

#
 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
This is never going to happen for a number of technical reasons and apis that are not supported in catalyst. 

Also openemu exists.
