### ISSUE TITLE
ERROR Fail to load game. 

### ISSUE THREAD

**Issue by beowulfkadmus** [Provenance-Emu/Provenance#1232]
Hi, i had and issue with the provenance App. 

Um trying to play Harvest mon Back to nature ROM no IPad Pro. The App os instaled perfectly and already with the BIOS for PS1. When i try to open the game, Reis MessagePad appears: ‘’Fail to load game. Check the file isnt corrupt and supported Mednafen ROM format.

!--- DISCLAIMERS ---------------------------------------------------------------

🛑 STOP! Before posting, make sure you…
✅ …have checked issues for existing bug reports.
✅ …are using the latest development build (may have already been fixed).
✅ …have discussed the issue on our Discord:     https://discord.gg/4TK7PU5

🚫 We DO NOT support unofficial 3rd-party installations (buildstore, iemulators, tweakbox, etc…). 
☠️ Delete and use official install:  https://git.io/vxABg

⚠️ BUG REPORTS ONLY! If you need help, use Discord. If suggesting a feature, use the request form. 
🚦 If you have read the above, please continue…
❌ Reports that do not use the template below will be closed and locked immediately.

----- BUG REPORT: Be clear, concise and thorough, beginning with a summary. --->

replaceWithSummaryOrDelete

 
### Expected: 

replaceWithExpectedResults

 
### Actual: 

replaceWithActualResults

 ### Reproduce:  

1. replaceWithSteps
2. 
3. 

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
This is a bit unreadable and incorrectly formatted. Head to our Discord to discuss there first as noted in the template…
