### ISSUE TITLE
Doens't work?

### ISSUE THREAD

**Issue by meluvalli** [Provenance-Emu/Provenance#1243]
I am not sure how anyone could still be using this.  It simply doesn't work.  If you sideload it to AppleTV, it uploads with a generic icon and when you click on it, it says "Unable to Install "Provenance".  Can't open app.

**Comment by urherenow** [comment]
Did you build it yourself? Is your aTV updated? If it is, did you update xcode, delete your Provenance folder, to build from scratch? You MUST if you’re building to a device with iOS 13, for example, because some of the framework has to be rebuilt with the latest swift version for anything to work.

**Comment by meluvalli** [comment]
I tried building first, and didn't work at all!  I kept getting errors during build.  I am running XCode 11.2.1 and on latest MacOS. 

I gave up and tried starting over, and still got a whole bunch of build errors (3 if I remember correctly).   And I couldn't figure out how to correct them :(

Is there a youtube video or something with the latest build on how to do this?  The only video I found was way old and out dated. :(

**Comment by meluvalli** [comment]
Ok.  I got it down to two errors.   Both which are the same, just for two different parts...

"No Profile for team '[My Name] (Personal Team)' matching 'match Development com.provenance-emu.provenance.topshelf-extension tvos' found: Xcode couldn't find any provisioning profiles matching 'XXXXXXXXX/match Development com.provenance-emu.provenance.topshelf-extension tvos'

This is after I set the "Development Team" to my personal iCloud.

**Comment by meluvalli** [comment]
Well, everything I have read says you don't need to pay the $99 developer fee, just means your cert will expire every 7 days.  However, I'm guessing maybe that's my problem is this isn't true.  I found under "Signing & Capabilities" I selected My Team, but then under status it says "No profiles for 'com.provenance-emu.provenance.topshelf-extension' were found.  Xcode couldn't find any tvOS App Development provisioning profiles matching....'

**Comment by meluvalli** [comment]
Well, figured out it helps to read the WAY OUTDATED WIKI.   It gave me a few pointers, but still doesn't compile.   Dumb.

**Comment by urherenow** [comment]
Figured it out... but doesn’t compile? Which is it? Either way, github isn’t a forum. You should close the issue, and visit the discord channel if you’re still having problems. I only built the iOS version. May try my hand at tvOS tomorrow...

**Comment by meluvalli** [comment]
Agreed.  Sorry.  Closing.
