### ISSUE TITLE
Audio stuttering during Xbox analog stick movement

### ISSUE THREAD

**Issue by chrisballinger** [Provenance-Emu/Provenance#1256]
I'm still not 100% sure of the cause, but when using an Xbox controller analog stick on iOS 13 the audio stutters in PSX games on an iPhone 11 Pro Max. My guess is that the analog stick events are coming in too fast and the audio buffers can't keep up, maybe could be solved by rate limiting MFi controller input? 

Workaround is to use the on-screen controller.

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Uncofirmed> If this is still an issue in 2.0+, please reopen.
