### ISSUE TITLE
tvOS 13.3 Import does not work when compiled with Xcode 11

### ISSUE THREAD

**Issue by hstriepe** [Provenance-Emu/Provenance#1257]
Adding games or artwork to Import folder on v1.5 does not do anything.
This is on ATV 4K running 13.3 beta with the latest Provenance commit.

 
Should be parsed and sorted into appropriate folder.

 
Files stay in Import folder. restarting the app does not change anything.

 1. Open Web Browser
2. Open Import folder
3. Add files.

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by hstriepe** [comment]
This was on tvOS 13.3 beta built with Xcode 11.3.
Sideloading on ATV 4K is not possible.

**Comment by hstriepe** [comment]
Recompiling under Xcode 10, packaging and then installing via Xcode 11 to tvOS 13.3 solved the issue!
This seems a Swift version issue.

**Comment by kikoz** [comment]
NB in the log file it says that the format is not recognized, e.g.

2020/03/21 22:12:32:943  Super Mario World 2 - Yoshi's Island (U) (V1.1).smc doesn't matching any known possible extensions and is in Imports directory. Deleting.
2020/03/21 22:12:32:944  Deleted /var/mobile/Containers/Data/Application/F5AB4B2A-8F9F-45AF-A0C0-2100A1219A09/Library/Caches/Imports/Super Mario World 2 - Yoshi's Island (U) (V1.1).smc.
2020/03/21 22:12:32:944  No system found to match Super Mario World 2 - Yoshi's Island (U) (V1.1).smc
