### ISSUE TITLE
tvOS 13.3 does not fetch or display art work

### ISSUE THREAD

**Issue by hstriepe** [Provenance-Emu/Provenance#1258]
Adding games directly to appropriate folder displays the games making it possible to run them. But the boxes are blanks. Re-importing to rescan for art work does not do anything.

This is on ATV 4K running 13.3 beta with the latest Provenance commit.

 
Games should show art work.

 
Displays are blank boxes

 1. Open Web Browser
2. Open Import folder
3. Add files.
4. Games show after a while or app restart.
5. No graphics.

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by hstriepe** [comment]
tvOS 13.3 beta on ATV 4K built with Xcode 11.3 beta.

**Comment by hstriepe** [comment]
It does display an image of the screen of saved games.

**Comment by hstriepe** [comment]
Recompiling under Xcode 10, packaging and then installing via Xcode 11 to tvOS 13.3 solved the issue of adding cover art manually. It still does not fetch automatically.
This seems a Swift version issue.

**Comment by mrjschulte** [comment]
This is related to issue #1264 .

**Comment by sevdestruct** [comment]
Duplicate.
