### ISSUE TITLE
Video freeze while audio works when mirroring screen via AirPlay

### ISSUE THREAD

**Issue by rursache** [Provenance-Emu/Provenance#1260]
hey guys,

i found a very annoying bug when emulating PSX (and i think all other platforms). my setup is as follows: iPhone 11 pro -> screen mirror to Apple tv 3 -> some projector in my bedroom. whenever i enable screen mirror, sound keeps playing but only the latest frame before enabling airplay is displayed (video stuck). without airplay mirroring, it's all good

 
### Expected: 

i should be able to see the output, not only the latest frame 

 
### Actual: 

only the latest frame before enabling airplay is displayed (video stuck)

 ### Reproduce:  

1. Run a PSX game
2. Enable screen mirroring to any AirPlay device (i used ATV 3 and 4)
3. Hear sound but only see the last frame before enabling mirroring

#

#### APP VERSION
- [x] 1.5 *beta*
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 13.2.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x

**Comment by sevdestruct** [comment]
@rursache Since we have a native AppleTV app, we won't likely be spending time on improving and it will unfortunately be always be at the limitation of network latency as an extra unnecessary layer. Recommend installing native AppleTV app, instead of mirroring. You're welcome to discuss further on our Discord in the meanwhile.
