### ISSUE TITLE
Update OpenVGDB to latest release. Fixes -> Artwork no longer downloading because Url has changed.

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1264]
The current develop commit is trying to source the following url template for downloading the covers: https://img.gamefaqs.net/box/X/X/X/XXXXX_front.jpg

This no longer works as the host name has changed so the automatic cover downloads are no longer showing up correctly in the app.

The new URL template that appears to work is as follows:
https://gamefaqs1.cbsistatic.com/box/X/X/X/XXXXX_front.jpg

This new template has been tested with various titles that have artwork that is not showing up correctly in Pv anymore and results in the correct artwork being shown.

replaceWithSummaryOrDelete

 
### Expected: 

replaceWithExpectedResults

 
### Actual: 

replaceWithActualResults

 ### Reproduce:  

1. replaceWithSteps
2. 
3. 

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mrjschulte** [comment]
Looks like we need to update OPENVGDB as it shows the "URL changed" as the update feature.

https://github.com/OpenVGDB/OpenVGDB/releases/tag/v26.0

**Comment by mrjschulte** [comment]
@jasarien / @JoeMatt Is this one hard to do?

**Comment by mrjschulte** [comment]
Can confirm that it seems like an easy enough update by just replacing openvgdb.sqlite in Provenance/PVLibrary/PVLibrary/Resources with the latest 26.0 release.

**Comment by urherenow** [comment]
What was this merged to? A fresh clone and build of Provenance-emu still uses the old URLs. This issue is NOT fixed.
