### ISSUE TITLE
Crash when opening save state from inside game

### ISSUE THREAD

**Issue by convolutionbbs** [Provenance-Emu/Provenance#1278]
Used 1.5b 2774 on ipados 13.3.  When I save a state and then try to re-open the state (tapping on the picture snapshot) while in game the app crashes.  If I re-open the app and launch the “recent save state” it opens and runs fine.  This happens on multiple games with multiple emulators.

**Comment by sevdestruct** [comment]
Please use the full report form to re-open ticket - need more details or move this to discussion on Discord (recommeneded) to troubleshoot before posting an a new issue.
