### ISSUE TITLE
When you Pause an N64 Rom the emulator automatic switch the music to slow on tvOS

### ISSUE THREAD

**Issue by maussie1811** [Provenance-Emu/Provenance#1288]
Hi Guys, i have a bug, When you Pause an N64 Rom on provenance 1.5 beta build 2774 the emulator automatic switch the speed from the rom to slow on tvOS an i must change the speed manually to normal. 

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x

**Comment by sevdestruct** [comment]
Should be fixed in #1308
