### ISSUE TITLE
When  PS1 game starts mostly no image (screen) the first time

### ISSUE THREAD

**Issue by maussie1811** [Provenance-Emu/Provenance#1289]
Hi Guys, i have another bug. When i start a ps1 game on Provenance 1.5 beta Build 2774 mostly the first time i have sound but no sound. The second time i start the game everything is fine. i hope you can fix this issue.

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
@maussie1811 Known bug, Please check the existing issues before posting: #1066
