### ISSUE TITLE
FF VII & FFVIII weird problem

### ISSUE THREAD

**Issue by NXRevolution** [Provenance-Emu/Provenance#1290]
So I had FFVII working fine, and I later put FFVIII on the emulator, and that worked fine. However, today when I tried to load FFVII, for some reason FFVIII loads. FFVIII loads no matter which of the two games I select. I tried to load a save state on FFVII I had to see if I could bypass this but it just froze when I tried to load it. Anyone have this issue, or know how to fix it?

**Comment by sevdestruct** [comment]
Use Discord for discussions.
