### ISSUE TITLE
signing certificates with private key not found 

### ISSUE THREAD

**Issue by quantum-fusion** [Provenance-Emu/Provenance#1304]
When building provenance for an IOS X device, the build is broken, because it does not find the signing certificate and private key.  

<img width="986" alt="Provenance-license" src="https://user-images.githubusercontent.com/10088099/76306884-14b54400-629e-11ea-8618-89203845b49f.png">

replaceWithSummaryOrDelete

 
### Expected: 

I expected the build to transfer the image that was built to the IOS device. 

replaceWithExpectedResults

 
### Actual: 

the build provided errors, as seen in the picture attached.

replaceWithActualResults

 ### Reproduce:  

build provenance and target an IOS device as shown in the picture.

1. replaceWithSteps
2. 
3. 

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by urherenow** [comment]
1) You clearly did no follow the guide

2) You are clearly NOT building on a device. You’re building for a simulator.

**Comment by quantum-fusion** [comment]
what is the link for the guide to build in Xcode?

**Comment by quantum-fusion** [comment]
instructions are not here (https://wiki.provenance-emu.com) for building in Xcode

**Comment by urherenow** [comment]
It’s also in the very form you filled out to post this issue. Notice how the word “building” is blue? Yea... it’s a link.

**Comment by quantum-fusion** [comment]
I think build from source instructions are here (https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance#build-source)

**Comment by quantum-fusion** [comment]
I am on it, and will see what I find.

**Comment by urherenow** [comment]
Your error tells you the problem. Go to ProvenanceShared, and ProSystem-ios and change the “team” to your own account.

**Comment by quantum-fusion** [comment]
![iosCodeSigning-license](https://user-images.githubusercontent.com/10088099/76310510-4ed61400-62a5-11ea-9662-0629fbb1376d.png)

It is really too bad, but it is requiring an iOS developer set of certificates, and will not accept self signed certificates on MACOS.

**Comment by urherenow** [comment]
Github is not a support forum. It is for collaboration and bug reporting. Please close this issue and seek help at Provenance on Discord, but for heaven’s sake, READ THE DARN GUIDE FIRST! 

You still have not read it. It tells you right off the bat to register a FREE developer account.

**Comment by quantum-fusion** [comment]
I never said this was a support forum, I opened an issue, because I needed my questions answered.  Regarding the free developer account, this is a misnomer, because for those of us, who have had developer accounts, it is no longer free.  (https://9to5mac.com/2016/03/27/how-to-create-free-apple-developer-account-sideload-apps/)

**Comment by quantum-fusion** [comment]
Counter to what this website claims, about being able to create a free account, it is still charging the $99 per year for the appleID developer IOS certificates, to be part of the developer program, which is required to sign this Provenance Xcode build.  Therefore, it is cost prohibitive, and I could instead buy an Xbox with emulator instead.

**Comment by urherenow** [comment]
I’ve never paid a dime. You’re doing it wrong. You don’t know how to read. How sad...
