### ISSUE TITLE
Art cover for games missing

### ISSUE THREAD

**Issue by Nakide** [Provenance-Emu/Provenance#1314]
Any plans to have art covers for the games? At first i thought it may be the roms i'm downloading but that is not the case after testing. This applies to both version 1.4 and 1.5 beta

Thank you for looking into this.

**Comment by urherenow** [comment]
Again, a known issue. If you learn to build it yourself, it’s an easy fix. After you clone the repository, open up the file openvgdb.sqlite with an SQLite editor, and run the vacuum command on it. Building with that, then refreshing image cache and roms, will give you your artwork.

**Comment by dougmcarthur** [comment]
I'd also like to see this issue resolved, without having to fork the app and change code myself. Guess we need to have patience.

**Comment by urherenow** [comment]
Placing the issue where it belongs (openvgdb) would be a good start. I’ve already started one, and perhaps a bunch of “me too” replies may get it noticed...


https://github.com/OpenVGDB/OpenVGDB/issues/40

**Comment by dougmcarthur** [comment]
@urherenow good advice - posting there.

**Comment by urherenow** [comment]
Well, that was a dead-end. The additional post did actually get attention, but the reply was VERY rude. After checking everything again, the author was correct, however. The latest openvgdb.sqlite from that site, does not match the crc32 of the file in this repo.

I tried to fork it to make a pull request myself, but the file is too large, and it will not allow me to upload it from the web interface.

**Comment by sedwo** [comment]
@urherenow Thanks for the updated `openvgdb.sqlite` file, but it didn't seem to make a difference on my end.
![image](https://user-images.githubusercontent.com/1434449/80785614-dd9d3980-8b4e-11ea-9f2f-768421787aeb.png)

**Comment by urherenow** [comment]
As I said before, you have to clear your cache and re-import the roms.

Using the web interface, delete default.realm

**Comment by sedwo** [comment]
Figured it out.  Little Snitch networking monitor was filtering the the connection.
Thanks.

**Comment by dougmcarthur** [comment]
> Figured it out. Little Snitch networking monitor was filtering the the connection.
> Thanks.

curious how long it'll be before this fix is released in a proper build of Provenance. Is it worth going into Xcode and building it myself?

**Comment by sedwo** [comment]
@dougmcarthur Just hacked through some of the same challenges and pushed up my changes.  You can give my branch a try:  https://github.com/sedwo/Provenance

**Comment by dougmcarthur** [comment]
> @dougmcarthur Just hacked through some of the same challenges and pushed up my changes. You can give my branch a try: https://github.com/sedwo/Provenance

Nice!!! This rules. Definitely going to give it a spin. Thanks!

**Comment by JoeMatt** [comment]
Closing, not a Provenance issue.
