### ISSUE TITLE
FULLSCREEN SUPPORT REALLY NEDDED

### ISSUE THREAD

**Issue by Luisgallegoarceiz** [Provenance-Emu/Provenance#1318]
replaceWithProblemOrDelete

 

replaceWithSolutionOrSuggestions

#
 

replaceWithAlternativesOrDelete

#
 

replaceWithAdditionalNotesOrDelete

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by Luisgallegoarceiz** [comment]
You can add fullscreen STRETCH TO FIT SCREEN specially on IOS iPhone XS Max

**Comment by sevdestruct** [comment]
Please check existing issues before posting new ones #639
