### ISSUE TITLE
Adding and removing favourites results in indexing issue

### ISSUE THREAD

**Issue by dnicolson** [Provenance-Emu/Provenance#1327]
### Expected: 
Game info modals to correspond to the selected game.

 
### Actual: 
A game info modal for a different game.

 ### Reproduce:  

1. Add Game A and Game B via web server
2. Favourite Game A and Game B
3. Unfavourite Game A and Game B
4. Select Game A

Options for Game B will be displayed.

![ezgif-6-314f197da286](https://user-images.githubusercontent.com/2276355/81855313-77a5ae80-955f-11ea-8862-eb83cf6866df.gif)

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by cheif** [comment]
This should be fixed by #1377, care to try it out @dnicolson?

**Comment by dnicolson** [comment]
@cheif that pull request seems to do the trick, thanks!
