### ISSUE TITLE
N64 Audio stutters and crackles sometimes on AppleTV 4K

### ISSUE THREAD

**Issue by TheDevDan** [Provenance-Emu/Provenance#1359]
On some games of the N64 using sideloaded v1.5, the audio stutters and crackles sometimes.  It is random.  I have seen this best when playing Rouge Squadron.

### Expected: 

Continuous clear and crisp audio.

### Actual: 

Stuttering and crackling audio.

 ### Reproduce:  

1. Load Rogue Squadron and play.

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
very outdated. Should be fine in 2.x releases.
