### ISSUE TITLE
Jaguar games making the app crash

### ISSUE THREAD

**Issue by llbologll** [Provenance-Emu/Provenance#1375]
The app is instantly crashing when I try to select a Jaguar game (iPhone 11, iOS 13.3). 

 
### Expected: 

Trying to launch a Jaguar game.

 
### Actual: 

The app is crashing when I select a game.

 ### Reproduce:  

1. try to launch a jaguar rom, the app will crash instantly

# 
#### NOTES  

I tried with many Jaguar games (Rayman, Doom, Soccer Kid, Flashback, etc...), but selecting a game always makes the app crash.

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
This is expected. The Jaguar core we use was mostly abandoned years ago. I’ve poked at it a bit over the years, but it’s not much we can do about it.

Per-core options should help, since some Jaguar games need certain core settings flipped, or a BIOS image vs the internal bios emulation.

**Comment by gr33k** [comment]
One year since this was posted - I can't get any games to load up for me (with the BIOS). Any plans to improve the Jaguar core? Great project folks - love it!

**Comment by JoeMatt** [comment]
There's no progress. Please don't bump tickets just for bump's sake. Q&A can be done in the Discord, thanks.

**Comment by gr33k** [comment]
I upgraded to 2.0 that was released (I was on 1.5b) and all my Jaguar games are working now! Thank you and sorry for bumping an old thread.

**Comment by JoeMatt** [comment]
That's, um, very surprising actually. You got lucky I guess.

**Comment by JoeMatt** [comment]
Jaguar was updated in 2.0.2, this should be fine. I've been playing a bunch of jaguar no issues.
