### ISSUE TITLE
Rotating device results in search field collapsing

### ISSUE THREAD

**Issue by dnicolson** [Provenance-Emu/Provenance#1379]
The search field collapses after the device is rotated to landscape and back to portrait.

 
### Expected: 

The search field to remain the same.

 
### Actual: 

The search field now contains no placeholder text and the height is reduced.

 ### Reproduce:  

1. Rotate device to landscape
2. Rotate the device back to portrait

Before:
<img width="280" alt="Screen Shot 2020-06-15 at 20 34 14" src="https://user-images.githubusercontent.com/2276355/84693986-b3f67100-af48-11ea-85ba-8eb311e52662.png">

After:
<img width="280" alt="Screen Shot 2020-06-15 at 20 34 20" src="https://user-images.githubusercontent.com/2276355/84693990-b5c03480-af48-11ea-9275-78575e803385.png">

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
new ui in #1750

**Comment by dnicolson** [comment]
Changing the `navigationItem.hidesSearchBarWhenScrolling` value to `false` appears to resolve the issue, but then the search bar is always visible.
