### ISSUE TITLE
On `make setup`: Dependency "HockeySDK-iOS" has no shared framework schemes for any of the platforms: tvOS

### ISSUE THREAD

**Issue by mymikemiller** [Provenance-Emu/Provenance#1394]
Following the [instructions](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source) with a clean build, I run into this error and the build fails:
```
*** Skipped building RxGesture due to the error:
Dependency "RxGesture" has no shared framework schemes for any of the platforms: tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/RxSwiftCommunity/RxGesture/issues/new
*** Building scheme "RxRealm-tvOS" in RxRealm.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mikem/OneDrive/Projects/iOS/Provenance/Carthage/Checkouts/RxRealm/RxRealm.xcodeproj -scheme RxRealm-tvOS -configuration Release -derivedDataPath /Users/mikem/Library/Caches/org.carthage.CarthageKit/DerivedData/11.5_11E608c/RxRealm/1.0.1 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2n/vn59_vz152vg107rrs53ympc0000gn/T/RxRealm SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/mikem/OneDrive/Projects/iOS/Provenance/Carthage/Checkouts/RxRealm)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2n/vn59_vz152vg107rrs53ympc0000gn/T/carthage-xcodebuild.cNDZvl.log

```

 
### Expected: 

Build succeeds

 
### Actual: 

Build failed

 ### Reproduce:  

https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source#setup

Build fails on the `make setup` step

# 
#### NOTES  

The exact library it complains about varies each time I try.

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by dnicolson** [comment]
Try running the following command:
`carthage update --platform iOS --no-use-binaries`

If that fails you might need to run this beforehand:
`rm -rf ~/Library/Caches/org.carthage.CarthageKit`

**Comment by mymikemiller** [comment]
@dnicolson None of that worked; I'm still getting the same error. What I don't understand is that even when I explicitly try `make setup ios`, I get the same error, complaining about "Dependency [...] has no shared framework schemes for any of the platforms: **tvOS**". Why is anything involving tvOS happening when I run `make setup ios`?

Here are my results of the commands you recommended:

During `carthage update --platform iOS --no-use-binaries`:
```
*** Skipped building HockeySDK-tvOS due to the error:
Dependency "HockeySDK-tvOS" has no shared framework schemes for any of the platforms: iOS
If you believe this to be an error, please file an issue with the maintainers at https://github.com/bitstadium/HockeySDK-tvOS/issues/new
```

Then during `make setup`:
`Dependency "RxGesture" has no shared framework schemes for any of the platforms: tvOS`

Then after `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and during `carthage update --platform iOS --no-use-binaries`:
`Dependency "HockeySDK-tvOS" has no shared framework schemes for any of the platforms: iOS`

Then during `make setup`:
```
*** Skipped building RxGesture due to the error:
Dependency "RxGesture" has no shared framework schemes for any of the platforms: tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/RxSwiftCommunity/RxGesture/issues/new
*** Building scheme "RxRealm-tvOS" in RxRealm.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mikem/OneDrive/Projects/iOS/Provenance/Carthage/Checkouts/RxRealm/RxRealm.xcodeproj -scheme RxRealm-tvOS -configuration Release -derivedDataPath /Users/mikem/Library/Caches/org.carthage.CarthageKit/DerivedData/11.5_11E608c/RxRealm/3.0.1 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2n/vn59_vz152vg107rrs53ympc0000gn/T/RxRealm SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/mikem/OneDrive/Projects/iOS/Provenance/Carthage/Checkouts/RxRealm)
```

**Comment by dnicolson** [comment]
I think you can ignore the HockeySDK warning. You do not need to run the `make` command, just run the `carthage` command.

**Comment by hellertime** [comment]
I am also running into this issue, not with HockeySDK, which the output is safely ignoring, but with RxRealm-tvOS (as the OP's log also is indicating is the error).

Issue happens with `carthage bootstrap --platform tvOS --no-use-binaries` and also with `carthage update --platform tvOS --no-use-binaries` after removing the cache with `rm -rf ~/Library/Caches/org.carthage.CarthageKit`.

No problems with the `--platform iOS` run of carthage.

Using the following version of Xcode:
```
Provenance>>  /usr/bin/xcrun xcodebuild -version
Xcode 11.6
Build version 11E708
Provenance>> carthage version
0.35.0
```
The actual error log isn't all that interesting, the build actually succeeds, its the archive creation that fails:

```
Touch /Users/hellertime/Library/Caches/org.carthage.CarthageKit/DerivedData/11.6_11E708/RxDataSources/4.0.1/Build/Products/Release-appletvsimulator/Differentiator.framework (in target 'Differentiator' from project 'RxDataSources')
    cd /Users/hellertime/code/Provenance/Carthage/Checkouts/RxDataSources
    /usr/bin/touch -c /Users/hellertime/Library/Caches/org.carthage.CarthageKit/DerivedData/11.6_11E708/RxDataSources/4.0.1/Build/Products/Release-appletvsimulator/Differentiator.framework

** BUILD SUCCEEDED **

/usr/bin/xcrun xcodebuild -project /Users/hellertime/code/Provenance/Carthage/Checkouts/RxRealm/RxRealm.xcodeproj -scheme RxRealm-tvOS -configuration Release -derivedDataPath /Users/hellertime/Library/Caches/org.carthage.CarthageKit/DerivedData/11.6_11E708/RxRealm/3.1.0 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/vh/1mpl45xs441gkbsxmdc0mx4m0000gn/T/RxRealm SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/hellertime/code/Provenance/Carthage/Checkouts/RxRealm)Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/hellertime/code/Provenance/Carthage/Checkouts/RxRealm/RxRealm.xcodeproj -scheme RxRealm-tvOS -configuration Release -derivedDataPath /Users/hellertime/Library/Caches/org.carthage.CarthageKit/DerivedData/11.6_11E708/RxRealm/3.1.0 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/vh/1mpl45xs441gkbsxmdc0mx4m0000gn/T/RxRealm SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO

User defaults from command line:
    IDEArchivePathOverride = /var/folders/vh/1mpl45xs441gkbsxmdc0mx4m0000gn/T/RxRealm
    IDEDerivedDataPathOverride = /Users/hellertime/Library/Caches/org.carthage.CarthageKit/DerivedData/11.6_11E708/RxRealm/3.1.0

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos13.4
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: Building for tvOS, but the linked framework 'Realm.framework' was built for iOS + iOS Simulator. (in target 'RxRealm-tvOS' from project 'RxRealm')
error: Building for tvOS, but the linked framework 'RealmSwift.framework' was built for iOS + iOS Simulator. (in target 'RxRealm-tvOS' from project 'RxRealm')
error: Building for tvOS, but the linked framework 'RxSwift.framework' was built for iOS + iOS Simulator. (in target 'RxRealm-tvOS' from project 'RxRealm')

** ARCHIVE FAILED **
```

**Comment by mrjschulte** [comment]
Looks like there is currently an incompatibility of some kind between a RxRealm build for iOS and tvOS when trying to bootstrap the RXRealm-tvOS framework. Best to build out the Provenance tvOS app separately with a new develop pull from the iOS build and you should be fine.

**Comment by hellertime** [comment]
Can you clarify what you mean by doing a tvOS build separately? Is it as simple as not running `carthage bootstrap --platform IOS --no-use-binaries`?

In addition, I am only interested in a tvOS build of the app (my target is Apple TV 4K), so is there no problem in never involving the steps for iOS?

**Comment by dnicolson** [comment]
@hellertime: You just need to run `carthage bootstrap --platform tvOS --no-use-binaries`.

You don't need to run `carthage bootstrap --platform iOS --no-use-binaries` if you're just targeting tvOS.

**Comment by thalter** [comment]
Same problem here. I skipped `carthage bootstrap --platform IOS --no-use-binaries` and just targeted tVOS.
