### ISSUE TITLE
Certain PS1 games are stuck on the top left d pad

### ISSUE THREAD

**Issue by EnderDaniel123** [Provenance-Emu/Provenance#1395]
If I were to play a PS1  game on provenance such as Crash Bandicoot 3, & the 1st 3 Spyro games. The d pad is stuck on the top left side. Which makes the character you’re playing go in circles. I’m using an iPod Touch 7th gen. The iPod Touch is on iOS 12.4.7. Any information & ideas on how to fix it or something? Let me know. Thanks.

**Comment by EnderDaniel123** [comment]
The controller that I use is a Horipad Game Controller. The version on the app is 1.5 Beta. I did forget to mention that last night. (See previous comment)

**Comment by jasarien** [comment]
This has been resolved. Sounds like you're using an older version, likely obtained from an unsupported 3rd party.
