### ISSUE TITLE
Apple TV application is not build with Error mentioned in screenshot (No such module RxRealm)

### ISSUE THREAD

**Issue by reynardh** [Provenance-Emu/Provenance#1396]
So, in the code we have one library and PVLibrary TV OS and inside that library there is one Module RxRealm which is not found.. as per the build log says .. can any one help me on this ?

![Screen Shot 2020-06-30 at 2 28 38 AM](https://user-images.githubusercontent.com/31398281/86315818-39407d80-bbf9-11ea-9ab6-1cd8a806209c.png)

So, in the code we have one library and PVLibrary TV OS and inside that library there is one Module RxRealm which is not found.. as per the build log says .. can any one help me on this ?

 
### Expected: 

This should run in Apple TV without error. 

 
### Actual: 

All mandatory steps are performed and certificates and all but at final stage I am getting this error which is there in screenshot.  

 ### Reproduce:  

1. Just run the app by following all the steps, mentioned over the below URL

https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source#advanced-features 

# 
#### NOTES  

#

#### APP VERSION
**- [ ] 1.5** *beta*
- [ ] 1.4

#### APP SOURCE
**- [ ] Provenance-Emu GitHub  *&nbsp;(Official)***
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
**- [ ] [Building](https://git.io/vpYzv) *from Source***

#### PLATFORM
- [ ] iPhone
- [ ] iPad
**- [ ] Apple TV**

#### iOS/tvOS VERSION
**- [ ] 13.x**
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mrjschulte** [comment]
Did you follow the Provenance Wiki install guide which has switched to using carthage with the bootstrap command to build the needed Apple frameworks?

**Comment by reynardh** [comment]
Yes 
https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source

**Comment by dnicolson** [comment]
Try running just the tvOS command and not the iOS one (https://github.com/Provenance-Emu/Provenance/issues/1394#issuecomment-662794952):
`carthage bootstrap --platform tvOS --no-use-binaries`

**Comment by thalter** [comment]
Confirm that AppleTV build is failing on RxGesture dependency
![Build Error](https://user-images.githubusercontent.com/11202988/89109067-e29ead00-d40b-11ea-8ce3-9cdab235c708.png)

**Comment by reynardh** [comment]
![image](https://user-images.githubusercontent.com/31398281/89128068-f7894800-d4c0-11ea-8b92-537d4d406af8.png)

**Comment by bbeversdorf** [comment]
I had the same issue with Xcode 11.5.
I switched my Xcode command line tools to 11.3.1 and ran
`carthage bootstrap --platform tvOS --no-use-binaries`
then I build the app using Xcode 11.3.1.

Note: I still received a couple of warnings running carthage but I was able to build.

```*** Building scheme "Differentiator" in RxDataSources.xcodeproj
*** Skipped building RxGesture due to the error:
Dependency "RxGesture" has no shared framework schemes for any of the platforms: tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/RxSwiftCommunity/RxGesture/issues/new
*** Building scheme "RxRealm-tvOS" in RxRealm.xcodeproj
*** Building scheme "SQLite tvOS" in SQLite.xcodeproj
*** Building scheme "SteamController-tvOS" in SteamController.xcodeproj
*** Skipped building XLActionController due to the error:
Dependency "XLActionController" has no shared framework schemes for any of the platforms: tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Puasonych/XLActionController/issues/new
*** Building scheme "ZipArchive-tvos" in ZipArchive.xcodeproj```
```

**Comment by thalter** [comment]
This workaround works - I am able to build using Xcode 11.3.1
