### ISSUE TITLE
Audio lag of almost a second when playing DK64 (haven’t tested other titles)

### ISSUE THREAD

**Issue by ale-reyes** [Provenance-Emu/Provenance#1424]
Audio lag of about a second when playing Donkey Kong 64 (haven’t tested with anything else) on iPad Pro 11” 2018.

### Expected:  

Expected perfectly or at least mostly unnoticeable audio delay.

### Actual:  

Audio lags behind by almost a second from the video.

### Reproduce:  

1. Play an n64 game.
2. 
3. 

#
#### NOTES  

#

#### APP VERSION

- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE

- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 

- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] XCode 9.3+
  - [ ] XCode 9.2 *or lower*

#### PLATFORM

- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION

- [ ] Latest (12.x)
- [ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Not reproducable. Device or 3rd party build issue most likely.
