### ISSUE TITLE
My Provenance 1.5b-2774 stop working after updating apple tv to tvOS 14 

### ISSUE THREAD

**Issue by robertovg** [Provenance-Emu/Provenance#1432]
Just wanted to check if someone was able to use Provenance on tvOS 13 as mine stopped working after the update.

**Comment by mrjschulte** [comment]
Fairly safe to say that Provenance isn't quite ready yet for tvOS/iOS 14!

**Comment by robertovg** [comment]
Guys something on this? Is now possible to install it on TVOS 14?

**Comment by cheif** [comment]
AFAIK it should be possible to run on iOS14/tvOS14, there's some problems with the new XCode right now, but you should be able to use XCode11.7 instead. 
You might need to add device support files for the new iOS/tvOS, you should be able to find info about how to do that by googling.
