### ISSUE TITLE
Insta-crash when selecting "Choose Cover"

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1436]
Provenance will insta-crash if you try to assign a custom cover to a title. Hold down on the game you want to apply a Cover to and select "Choose Cover", note how Provenance will instantly crash. 

_PvAppDelegate.swift #17 final class PVAppDelegate: UIResponder, UIApplicationDelegate {

"Thread 1: Exception: "Your application has presented a UIAlertController (<UIAlertController: 0x125857400>) of style UIAlertControllerStyleActionSheet from UINavigationController (<UINavigationController: 0x124015c00>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.""_

**Comment by dnicolson** [comment]
I'm unable to reproduce on iOS 14.2, is it still reproducible?

**Comment by marcelvoss** [comment]
This is a funny tidbit when using UIImagePicker on iPads (and how action sheets are being presented on iPad). Unlike on iPhones, on iPads it is being presented within a popover and popovers need certain information about the environment they're being presented in (where should the arrow point to, which view is the source of the interaction...). Here's an excerpt from the [UIImagePicker](https://developer.apple.com/documentation/uikit/uiimagepickercontroller) documentation:

<img width="750" alt="Bildschirmfoto 2021-01-02 um 21 44 52" src="https://user-images.githubusercontent.com/5435925/103466273-c220a900-4d43-11eb-96d4-7feaf147791d.png">

Feel free to review my fix here. 1476

**Comment by mrjschulte** [comment]
Thanks for the work on this @marcelvoss ! We're going to close this issue out!
