### ISSUE TITLE
tvOS - MFI Menu button doesn't bring up Menu in-game

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1442]
Pressing the Menu button on a MFI controller when using tvOS doesn't bring up the in Game Menu. The menu will show up for an instant and then proceed to go away and continue playing the core in question.

**Comment by mrjschulte** [comment]
Tested on the Nimbus and Horripad!

**Comment by mrjschulte** [comment]
Looks like the MFi Controller support is pretty busked for tvOS at the moment. Pairing a M30, and whilst the buttons aren't mapped correctly, I get the full functionality of the Menu button and other buttons as expected.

**Comment by mrjschulte** [comment]
More investigative work, after a DualShock controller has been connected and used with Pv the MFi Controller works. DS4 works straight out of the box, MFI does not.

**Comment by mrjschulte** [comment]
Doing a clean pull and build to the appleTV allows for the Controller to work, still trying to track down when it decides to no longer listen to the MFI controller.

**Comment by LeSongz** [comment]
Hello guys,
Im not sure if i have the same problem here After updating my Appletv to 14 and while trying to play any ps game using provenance, the moment i press O in DS controller i go back to apple tv main screen ..
Things i tried to fix this,
Deleting and reinstalling provenance latest update 1.5
Unpairing and repairing my controller
Borrowing and trying Nimbuss+ and a different DS controller
Still no matter what i try the issue isn't fixed

No way to go back to 13 as i have the apple tv 4k

Please help!

**Comment by LeSongz** [comment]
> Doing a clean pull and build to the appleTV allows for the Controller to work, still trying to track down when it decides to no longer listen to the MFI controller.

Im not a programmer but I’m in this forum looking for a fix to his problem.
And since this is a common issue to lots of other users who used to enjoy this app in their Apple tv, 
Any other way of updating the .ipa app file with the fixed coded source without bulding the app from scratch ?

Or for those who built it! Can you share your fixed .ipa updated file ?

**Comment by mrjschulte** [comment]
#1473 closes this Issue.
