### ISSUE TITLE
TVos PlayStation controller keeps taking me to menu

### ISSUE THREAD

**Issue by jawa31** [Provenance-Emu/Provenance#1445]
Every time I push the O button it keeps taking me to the menu of the Apple TV.  Any fix for this ?

**Comment by cheif** [comment]
I have experienced this, and it seems to be a problem when building with XCode11 for tvOS14. Using this branch https://github.com/Provenance-Emu/Provenance/pull/1441 and building from XCode12 fixed the problems for me at least
