### ISSUE TITLE
On screen controls stuck moving up 

### ISSUE THREAD

**Issue by Crager0619** [Provenance-Emu/Provenance#1447]
### Expected: 

To be able to control my character

 
### Actual: 

Stuck running up. Doesn’t do it at opening menu of game. Once you watch the scenes and gain control of your character it does it there and the menu

 ### Reproduce:  

1. Play The Legend of Dragoon
2. Watch opening scenes
3. Wait to gain control of main character

# 
#### NOTES  

Doesn’t do it on the original menu when you open game. Only starts after you gain control of character

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
This is fixed based on the fact that no one has reported this issue in any release for a year.
