### ISSUE TITLE
Loss of sound when switching apps on tvOS14

### ISSUE THREAD

**Issue by joolay** [Provenance-Emu/Provenance#1449]
Running Checkra!n 0.12.1 on tvOS 14.2

Installed Latest Provenance from Nitotv

Only using NES roms with the FCEU core

when exiting provenance by pressing B button on Xbox one s controller and then returning to provenance the sound is lost on the game until the game is exited and restarted

replaceWithSummaryOrDelete

 
### Expected: 

replaceWithExpectedResults

 
### Actual: 

replaceWithActualResults

 ### Reproduce:  

1. replaceWithSteps
2. 
3. 

# 
#### NOTES  

replaceWithNotesOrDelete

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [x] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by MrBlackthorne** [comment]
I am having this same issue with official build 1.5b-2774 using tvOS 14.

**Comment by cheif** [comment]
I'm pretty sure this is fixed by https://github.com/Provenance-Emu/Provenance/pull/1441

**Comment by joolay** [comment]
I don’t understand what to do.. is there no easy way of inputting a nito repo with a precompiled fixed version of provenance to install?

**Comment by urherenow** [comment]
The wiki has instructions on how to build from source. If you're a Windows user, install VMware player (free) and Google how to create a macOS VM (this is actually the most troublesome part, unless you actually have a Mac).

Follow the wiki until you fail (and it will fail) then run ./carthage.sh build ==platform tvOS (or iOS), then continue following the wiki from "make open"

**Comment by MrBlackthorne** [comment]
I built from the latest merged source, and that fixed the issue for me. @urherenow, thanks for the tip on building from the source.

**Comment by cheif** [comment]
@MrBlackthorne Nice! Then that was fixed by #1441, so we should be able to close this! (I don't have permissions to do that though)

**Comment by mrjschulte** [comment]
Closing, thanks all!
