### ISSUE TITLE
iPadOS Files.app hangs unless Provenance is running in background

### ISSUE THREAD

**Issue by chinarut** [Provenance-Emu/Provenance#1455]
iPadOS 14.2 Files.app hangs unless Provenance is active in the background (screencast: https://youtu.be/VbKbzdavUBw)

 
### Expected: 

browse folders in Files.app

 
### Actual: 

Files.app hangs

workaround: make Provenance app active

 ### Reproduce:  

0) force quit Provenance (if running)
1) go to Files.app
2) observe Files.app is hung on “On My iPad”
3) make Provenance app active
4) go back to Files.app
5) observe Files.app is able to browse

# 
#### NOTES  

iPad Pro (2018) 256GB LTE
iPadOS 14.2
Provenance 1.5 beta build 2774

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

**Comment by GCPDetective** [comment]
I can confirm I run into the same issue with the same build on iOS 14.3 on my iPad Air 3

**Comment by JoeMatt** [comment]
That's an iOS issue. Not existing on current versions. Closing.

**Comment by chinarut** [comment]
thanks for letting us know.

It's been a bit of a hassle maintaining sideloaded apps unfortunately so I had to move onto Batocera & OpenEmu.  Thanks for all the initial inspiration that an app could be a one-stop retro museum with a great interface & less tinkering! 👾
