### ISSUE TITLE
Pressing O takes me to main screen

### ISSUE THREAD

**Issue by iyousefmb** [Provenance-Emu/Provenance#1469]
Hello guys,
Im not sure if i this been reported before but after updating my Appletv to 14 and while trying to play any ps game using provenance, the moment i press O in DS controller i jump back to apple tv main screen ..
Not sure if the tvOS 14 is designed now this way by pressing O means going back regardless of your controller ..

Things i tried to fix this,
Deleting and reinstalling provenance latest update 1.5
Unpairing and repairing my controller
Borrowing and trying Nimbuss+ and a different DS controller
Still no matter what i try the issue isn't fixed

No way to go back to 13 as i have the apple tv 4k

Please help!

**Comment by urherenow** [comment]
GitHub has a search function, and yes, it's been reported several times and already fixed. Until a new release is done you'll simply have to clone the repo and build it yourself.

**Comment by Rysken** [comment]
@urherenow I have the same issue. Tried different controllers (Nimbus, SN30 Pro). Reinstalled everything etc. Tried all settings. How is it fixed? "Until a new release is done you'll simply have to clone the repo and build it yourself." What does that mean? Sorry I'm slow and know nothing about programming.

**Comment by LeSongz** [comment]
Truly sorry if I’m wasting anyone time here, but I'm not a coder and wont be able to build it myself for sure.

But since this is a common issue, Any other way of updating the .ipa app file with the fixed code source without bulding the app from scratch ?

Or for those who built it! Can you share your fixed .ipa updated file ?

**Comment by urherenow** [comment]
I'd love to help, but I can't figure out how to get an .ipa that can be sideloaded without a paid developer account. Took forever to figure out how to make an .ipa with a free account, but it can't be side-loaded.

Now if someone wants to give me access to their paid account, I'd be happy ti make one!

But... The wiki does give pretty instructions on how to build it yourself. If you don't have a mac, the hard part is getting a Mac VM up and running. But Google has guides for that too...

**Comment by mrjschulte** [comment]
This has been fixed and merged.
