### ISSUE TITLE
Provenance AltStore Source

### ISSUE THREAD

**Issue by noah978** [Provenance-Emu/Provenance#1470]
----- FEATURE REQUEST: Be clear and concise. -----------------------------------
 

 

So I've been trying to get more of the open-source iOS app developers to consider making their own [AltStore Source](https://noah978.github.io/AltStore-Docs/Sources) before the feature eventually releases to the public build (No ETA) of [AltStore.](https://altstore.io)

But if you are interested in generating an AltStore Source, the devs behind UTM put together a combination of a github workflow and Node.js to convert github releases into the complete AltStore Source.

You can check out the [repo for it](https://github.com/osy/altstore-github) and the [UTM app it's used with](https://github.com/utmapp/altstore-repo/tree/gh-pages).

#
 

At the very least, I think it would be quite convenient for Provenance to have an AltStore Source since that makes handling updates and communication to users quite nice.

#
 

Thanks for the consideration!

**Comment by ideologysec** [comment]
This would probably be more helpful if a release had been cut + built any time in the last two and a half years...

**Comment by JoeMatt** [comment]
Will do it on the next releaase.

**Comment by eduo** [comment]
This is now done as part of 2.0 release. Thank you so much.

**Comment by JoeMatt** [comment]
Https://provenance-emu.com/apps.json

FYI. I'll be updating with screenshots soon but it works to install as-is.
