### ISSUE TITLE
Xbox Wireless Controller [B] button exits game

### ISSUE THREAD

**Issue by WeeJeWel** [Provenance-Emu/Provenance#1472]
Pressing the [B] button on a Xbox One Wireless Controller (Bluetooth), the game exits. It behaves as if the [Menu] button was pressed on an Apple TV Remote.

 
### Expected: 

Make Mario jump and rotate :)

 
### Actual: 

The Homescreen was shown.

 ### Reproduce:  

1. Connect an Xbox Wireless Controller
2. Start a game
3. Press the [B] Button

# 
#### NOTES  

Version: `Provenance-tvOS-1.5b-2774.ipa`

#

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by urherenow** [comment]
I lost count of how many times this issue has been reported already. It’s already fixed in the source. You’ll have to build it yourself if you want it now.

**Comment by LeSongz** [comment]
> I lost count of how many times this issue has been reported already. It’s already fixed in the source. You’ll have to build it yourself if you want it now.

Truly sorry if I’m wasting anyone time here, but I'm not a coder and wont be able to build it myself for sure.

But since this is a common issue, Any other way of updating the .ipa app file with the fixed code source without bulding the app from scratch ?

Or for those who built it! Can you share your fixed .ipa updated file ?

**Comment by Goldy412** [comment]
Can anybody share with me the ipa where this is fixed?

**Comment by iyousefmb** [comment]
> Can anybody share with me the ipa where this is fixed?

Oh, sorry body if you're not a programmer or know how to code then you're gonna have to wait like the rest of us for an official update.

**Comment by urherenow** [comment]
You don't need to be a programmer and you don't need to know anything about coding. You need to learn how to follow directions. The wiki tells you step by step, how to build the current source yourself. If you don't have a Mac, there is no shortage of tutorials that tell you how to make a VM. This is all free.

In contrast, to have the ability to create an ipa that you can then side load, would cost me $99 for a paid developer license.

**Comment by laptevme** [comment]
It's not hard to build from source.
But it's uncomfortable with free account - you have to rebuild it every 7 days.

I bought certificate for one UDID, it's easier and more comfortable for me ($8 for a year).
Why no one considers this option? I guess I'm not the only one who uses it.

I  haven't  developer account, thats why I can't create an .ipa file.
I don't ask anyone to buy a developer account,  but maybe someone already has one and could help us.

Or maybe the author will pay attention and also could help.

Translated with www.DeepL.com/Translator (free version)

**Comment by mrjschulte** [comment]
This has been fixed and available when compiling from source.
