### ISSUE TITLE
Crash on launch. Var gameLibrary nil on PVGameLibraryViewController:816

### ISSUE THREAD

**Issue by xtianstone** [Provenance-Emu/Provenance#1488]
PVGameLibraryViewController.:816 Var gameLibrary is not initialized. It looks to upgrade the database and hard crash.

I tried deleting the app and reinstall with a fresh build. Same issue. It looks like the view is getting launched from the catch block in PVAppDelegate, before gameLibrary is assigned in the AppDelegate. I am uncertain if one gets assigned from the other.

 
### Expected: 

not crash.

 
### Actual: 

hard crash and return to springboard

 ### Reproduce:  

1. Possibly need to install 1.4 with working BIOS files (such as PS1).
2. Install/Upgrade to latest code.
3. Crash on launch. Before window asking to reinstall.
4. Note: Possibly you do not need step 1. I deleted the app, expecting no residual data, and cleared my XCode cache. Same result on build with latest code. Hard crash. That leads me to believe that a fresh install should show similar results.

# 
#### NOTES  

PVGameLibraryViewController is called on the alert from PVAppDelegate. I reason likely the gameLibrary is not instantiated before the alert is posted. Changing the timeout to 10 seconds does not change the fail on the alert. So this may be a red herring.

#

#### APP VERSION
- [X ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [ X] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ X] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ X] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ X] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mrjschulte** [comment]
I'm not seeing this crash on vanilla builds using Xcode 11.6 on iOS 13.3. Do you have any more details? What version of Xcode and exact iOS version are you using?

**Comment by JoeMatt** [comment]
resolved or not existant based on lack of reports on 2.0
