### ISSUE TITLE
iCloud Drive and Files App support

### ISSUE THREAD

**Issue by fancyham** [Provenance-Emu/Provenance#1494]
Would love if ROM file folders could be accessible via / exposed to the Files app for easy management. 

Even better if it could use iCloud Drive as well.

also, detecting changes to the directory, or an easy to access button to rebuild the catalog.

**Comment by fancyham** [comment]
MAME4iOS does this, as an example:
https://github.com/yoshisuga/MAME4iOS

**Comment by urherenow** [comment]
There already is a button to refresh your rom library.

**Comment by mrjschulte** [comment]
You can use the + button in the upper right Corner on iOS to access the files that are local on your device, or on a iCloud share already. Can you provide some more context as to what you think you're missing?

**Comment by fancyham** [comment]
Ah, I was using the 1.4 version!  

Okay, using the 1.5 beta: 
I see the folders are exposed now to the Files app, but in Provenance itself, it’s not showing the ROMs list properly (none of the games are visible) after I import them from + > Cloud + Local Files.

The files are in the proper directories according to the Files app, but nothing shows properly, even after rebuilding the library.

<img width="1366" alt="Screenshot 2021-01-26 at 11 09 31 AM" src="https://user-images.githubusercontent.com/3376957/105905806-fbf17200-5fc6-11eb-81c0-5a0edfb15392.png">

**Comment by urherenow** [comment]
Do you see how old the last beta release is? Or check how many times that issue has been reported (and closed)? It's already fixed in the code. You just need to compile it yourself.

**Comment by fancyham** [comment]
My apologies — wasn't using the latest.
