### ISSUE TITLE
8bitdo M30 support

### ISSUE THREAD

**Issue by jdelomenie** [Provenance-Emu/Provenance#1499]
Hi

I'm trying to use my new 6 buttons M30 controller from 8bitdo on iOS.
It's properly connected under Accessibility switch under the proper name.

When I use it in any games, D-pad is correct, A & B as well, however C key is mapped to X !
looks like the C and Z keys are ignored and only map 4 keys as any major 8bitdo controllers except the M30 (megadrive style)

Any options to map the M30 keys to Provenance sega MD games as expected ?

Many thanks
Julien

**Comment by mrjschulte** [comment]
Hi, I don't think this is should really be tagged as a bug and the issue you are facing is due to the fact that the M30 doesn't officially map into any of the current buttons schemes available inside of iOS/Provenance. 

I'm going to change this Issue to a feature request, and as a fellow M30 owner, I can't wait for the day when we can re-assign our buttons inside of Provenance (or have a special M30 enable option under the control section).

**Comment by mrjschulte** [comment]
I started building out a new Provenance branch that allows you to select the 8BitDo M30 as a special controller mapping to be used with the Sega Genesis/MD core. When enabled, it maps the 6button Sega Controller 1:1 to the 8BitDo M30. 
It hasn't been tested on iOS yet but works as expected on tvOS.

**Comment by mrjschulte** [comment]
Doing some iOS testing called for a revert of the "Start" on the M30 to be relocated to the original R-Shoulder trigger due to an overlap with the Provenance in-game Menu. tvOS is fine and works as expected.

**Comment by jdelomenie** [comment]
Sounds great ! As I'm not a developper to rebuild any sources, would you update me when this M30 support will be released in any ipa build file ? If doable, can you please share which one it will be (ie 1.5b xxxxx.ipa) ? Many thanks in advance

**Comment by mrjschulte** [comment]
We'll keep this ticket going and once the M30 changes are in, and this Issue is closed, you should get a notification but I won't be able to tell you about the .ipa build or build number that will have this feature.

**Comment by mrjschulte** [comment]
Here's a screenshot on tvOS showing the supported M30 mapping option under Settings, it's disabled by default of course:

![Screen Shot 2021-01-31 at 4 01 42 PM](https://user-images.githubusercontent.com/30782821/106402311-c4773100-63dd-11eb-8567-d6d8d46f0304.png)

**Comment by mrjschulte** [comment]
PR #1500 is in.

**Comment by jdelomenie** [comment]
Awesome ! Maybe you can generate an ipa file to test it as an early adopter ? :)
It might be helpful to get it tested on iOS as well, not only tvOS.

**Comment by mrjschulte** [comment]
This has now been merged. Tested as working on both tvOS and iOS. Perhaps other cores will get M30 support in the future as well but closing this for now! Thanks.

**Comment by jdelomenie** [comment]
@mrjschulte How to build iOS ipa file with your code changes ? as shared I'm not dev specialist and dont have any Mac available to perform code build. Would love to test before 1.5 official release
