### ISSUE TITLE
Which 8bitdo controller is compatible with Provenance 1.4?

### ISSUE THREAD

**Issue by jb355** [Provenance-Emu/Provenance#1519]
Hello, I apologize in advance if I put my question in the wrong place.

I installed Provenance 1.4 on a 16GB ipad 2 with ios 8.1. I did not install the 1.5 because it is not compatible with the version of ios installed.

Provenance 1.4 works great on iPad 2. For me it is the perfect way to recycle an iPad 2.

I bought a first model 8bitdo Zero controller but it doesn’t work as soon as I press the directional pad on the left side, Provenance starts bugging. This controller is not compatible with Provenance 1.4. I searched the forums and understood that I was not the only one and that Provenance 1.4 will never be updated to support an 8bitdo Zero controller. It’s okay, I’ll sell it.

In the Provenance options, it is marked that the emulator could be compatible with an 8bitdo controller.

My question is: I want to buy a new 8bitdo controller but this time I don't want to make a mistake and end up with a new controller which is incompatible with version 1.4. What are the 8bitdo controllers that are 100% compatible with the Provenance 1.4 emulator?

**Comment by JoeMatt** [comment]
check the wiki or ask on discord, link also in wiki. https://wiki.provnenance-emu.com
