### ISSUE TITLE
Super Mario World 2: Yoshi's Island (SNES) doesn't work in Provenance 1.5b

### ISSUE THREAD

**Issue by eSmus1c** [Provenance-Emu/Provenance#1523]
Super Mario World 2: Yoshi's Island (SNES) doesn't work in Provenance 1.5 beta (build 2774), it just shows black screen after loading the ROM. I've tried different ROM versions taken from [here](https://www.emu-land.net/consoles/snes/roms?act=showonly&id=1516), and none of them work. I've tried different Provenance settings with no luck. However, Provenance 1.4 works fine with this game. Tested on iPad Pro 10.5, iOS 14.5.1 with jailbreak.

 
### Expected: 

Super Mario World 2: Yoshi's Island (SNES) ROM works as it should.

 
### Actual: 

Super Mario World 2: Yoshi's Island (SNES) doesn't work and shows black screen. 

 ### Reproduce:  

1. Download any Super Mario World 2: Yoshi's Island SNES ROM.
2. Import ROM into Provenance 1.5 beta (build 2774) and start the game.
3. Watch the black screen instead of the game.

#### APP VERSION
- [x] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

**Comment by mrjschulte** [comment]
Hi, this Title works when you build from Source against the latest Develop branch. 
When you've done this you will now have two options for playing SNES titles, the SNES9x Core or the Mednafen Faust Core. Both core have been updated since the Provenance version that you are using to support the Title in question.

**Comment by eSmus1c** [comment]
Hi! Sounds nice, but I have no idea how to build from source against the latest develop branch. I'm not a developer. So, I guess, I need to wait for the official prebuilt IPA update.
