### ISSUE TITLE
B button exits provenance on AppleTV

### ISSUE THREAD

**Issue by josemariano77** [Provenance-Emu/Provenance#1529]
Games are unplayable on AppleTV as the B button (often the jump button) exits the app.
It would be great if you could fix this.
Thanks.

**Comment by mrjschulte** [comment]
Fixed in current mainline Develop. Please build this from source to get the fix.

**Comment by josemariano77** [comment]
Thanks, however in order to fix it I need to get it signed, and I'm using
signulous. Is there any other way to do it if you are not a developer?

Thanks!




*JOSÉ MARIANO LÓPEZ-URDIALES*
Founder & CEO

Mobile: +34 638 785 006
Skype: josemariano77
If you really, really need to print this, why not use recycled paper?
