### ISSUE TITLE
Provenance for Apple TV adds "private" part to "partialPath" in PVFile

### ISSUE THREAD

**Issue by Aazamandius** [Provenance-Emu/Provenance#1550]
I built and run Provenance for Apple TV on my Apple TV
After it, I added some games (snes and sega)
After it, I restarted the app and games shown in the list but every one of them had the status "The rom file for this game cannot be found". I tried to find a reason but I don't know xcode good enough

I stopped on the step where the variable "partialPath" in the file PVFile.swift has "private/" part in the path - this is wrong, it shouldn't be here

![image](https://user-images.githubusercontent.com/4215125/128132149-b8f9b8b2-af2c-4cdb-8337-92a75a9ea459.png)

**Comment by Aazamandius** [comment]
The project has been build from release/2.0.0 branch commit 502511b1d1a455826173fe16eac9315f9484fa55

**Comment by JoeMatt** [comment]
I'm 99% sure the 'private' part isn't a bug, it's a feature of iCloud. Is iCloud sync enabled in settings?

**Comment by Aazamandius** [comment]
No, I checked it of course, it wasn’t enabled. The point is that in some parts of the app the path shows right, without “private” path, I can trace the app and show that places if you want. But in this part it adds that private part somehow.

**Comment by Aazamandius** [comment]
I made some extra research
1. This bug doesn't reproduce on simulator (in my case it is apple tv) BUT on simulator sega games were imported but didn't show in the games list
2. After adding the first time games are playable but after restart, they stopped launch
3. On Screenshots below in some part of the app the paths are right

<img width="1147" alt="Screenshot 2021-08-06 at 09 20 57" src="https://user-images.githubusercontent.com/4215125/128479479-2678afa6-ac3b-437c-9fa1-9ca0524e410a.png">
<img width="989" alt="Screenshot import is ok" src="https://user-images.githubusercontent.com/4215125/128479483-61d31afc-b71e-4717-9be4-c8fefdc4b00f.png">

**Comment by Aazamandius** [comment]
Yes, exactly
When you add a game it works. And continue works after restart the app
But if you do "Refresh game library" it breaks every game. It doesn't reproduce in simulator.

**Comment by JoeMatt** [comment]
The app code isn't adding it, something in the OS is. I think the iCloud check is probably wrong and it's adding a partial iCloud container prefix or something.

I mean, it's a bug in Prov I'm sure, but it's not as easy as searching for "private", cause I did, and it's not there.

I think I'm just going to rip everything iCloud out, I'm pretty sure it's never going to work as expected anyway if it's even working now. I've been unable to really give it a good testing in a while, since like iOS 12 when it did work but not since.

**Comment by Aazamandius** [comment]
Ok, let me help you then.
I have all the needed devices, I can build the app from any branch.
So I suggest you make a branch and remove all the code you want, then I build and test it.

**Comment by JoeMatt** [comment]
This and #1551  are probably related

**Comment by JoeMatt** [comment]
Added to the next release milestone since we've gotten a bunch of similar reports.

**Comment by JoeMatt** [comment]
Fixed in commit 7ad2779e71a6843a02237e64f4245e3770ae4702 and merged to develop. closing . thanks!
