### ISSUE TITLE
Is "refresh library" supposed to break all links to ROMs?

### ISSUE THREAD

**Issue by eduo** [Provenance-Emu/Provenance#1551]
"Refresh game library" marks all ROMs as faulty (red + warning sign) and refuses to launch them.

 
### Expected: 

Expected to load existing ROM files into icons in the library normally (perhaps losing custom changes)

 
### Actual: 

All ROMs replaced with red cover icons with a warning sign. Trying to launch gives an error ("The ROM file for this game cannot be found") even though the ROM is in the same place with the same name as before.

 ### Reproduce:  

1. Import any ROM succesfully into 2.0
2. Refresh Game Library
3. See ROM become unavailable

# 
#### NOTES  

It might be that there's an ongoing process that I'm missing, but there's no status of progress.

It's also impossible to match activity in the folder with behaviour in the library. Deleting from the library deletes the file (but doesn't send it to the trash. Adding a bunch of ROMs only sees some of them imported but they're all copied. There's no way to address the missing ones from within Provenance or where to see why they were ignored and/or why they are nonetheless kept as if they'd been imported.

I can provide screenshots or a quick movie, but to me it's pretty straightforward. I'll do so if it's not reproducibler.

#

#### APP VERSION
- [x] 2.0
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading via official repo]
- [] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 15.0 Beta 4
- [ ] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by Aazamandius** [comment]
For information
https://github.com/Provenance-Emu/Provenance/issues/1550
The same bug

**Comment by JoeMatt** [comment]
How many roms we talking?

If it's like, hundreds, then yeah, you gotta wait a while for it to rescan.

**Comment by Aazamandius** [comment]
No, I tried to add less than 5.

**Comment by JoeMatt** [comment]
Added to 2.0.1 milestone. This seems important though I haven't verified it yet myself on the cause.

**Comment by sobodash** [comment]
Had the same experience with a collection of 10 ROMs.

**Comment by JoeMatt** [comment]
Working on it in #1575
