### ISSUE TITLE
SteamController upstream updates

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#1564]
During 2.0 release, SteamController repo was out of date and breaking builds/swift pm.

There's been a new release after I asked them for a status update,
https://github.com/zydeco/SteamController/releases/tag/v1.3

I had manually added the code and removed the dependency, now I need to see if this new release will work (it has a bugfix we probably want too)

**Comment by mrjschulte** [comment]
Yeah these are the fixes I hinted at on discord from ToddLA as part of what he did for Mame4ios. Great to see there's a formal update/release w those fixes in there.
