### ISSUE TITLE
On screen buttons do not work with mednafen core

### ISSUE THREAD

**Issue by BatBoss** [Provenance-Emu/Provenance#1568]
**Expected:**

On screen buttons should work when using mednafen core

**Actual:**

None of the on screen buttons work in mednafen when playing .gb or .gbc roms

**Reproduce:**

1. Start a .gb or .gbc rom using mednafen core.
2. Attempt to press the buttons on screen

**NOTES**

With the new 2.0 update, I am not able to play any .gb or .gbc roms using the Mednafen core. The on screen buttons do not do anything (other cores work fine). This worked in the 1.4 release, so I think it must be a new issue.

My device is an iPhone 11.
iOS version is 14.7.1

**APP VERSION**

  2.0

**APP SOURCE**

Provenance-Emu GitHub  (Official)

**INSTALLED BY**

  Building from Source

**PLATFORM**

  iPhone

**iOS/tvOS VERSION**

  14.x

**Comment by JoeMatt** [comment]
Fixed in 2.0.1
