### ISSUE TITLE
Multidisc appears not to work on Sega Saturn

### ISSUE THREAD

**Issue by sobodash** [Provenance-Emu/Provenance#1571]
Multidisc appears not to work on Sega Saturn.

### Expected: 

Adding a multidisc game from a properly formatted ZIP should create a multidisc game entry.

### Actual: 

Provenance prompts to resolve conflicts (specify system) for each disc, then creates an icon associated with only one disc (whichever conflict you resolved first). All other discs and the m3u are orphaned in the Sega Saturn directory and not associated with the entry. They will remain if you delete the game entry with only the single disc associated with the icon being removed, and cause a crash if you attempt to re-add the game.

 ### Reproduce:  

Create a multidisc file named as:
- Sakura Wars (Japan) (Disc 1).bin
- Sakura Wars (Japan) (Disc 1).cue
- Sakura Wars (Japan) (Disc 2).bin
- Sakura Wars (Japan) (Disc 2).cue
- Sakura Wars (Japan).m3u

These are contained in Sakura Wars (Japan).zip. I have also tested with Panzer Dragoon Saga and Grandia with the same results.

#### NOTES  

I don't think it's user error. Single disc Sega Saturn games load, and I have no problem creating multidisc entries in PlayStation using the same method.

#

#### APP VERSION
- [x] 2.0.0
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mrjschulte** [comment]
Is there a smaller Multidisc game that is also affected by this to help with the testing? @sobodash ?

**Comment by sobodash** [comment]
> Is there a smaller Multidisc game that is also affected by this to help with the testing? @sobodash ?

Any multidisc game is going to be at least two discs. I took a quick look at the REDUMP collection on Archive.org and it looks like one of the smaller multidisc game is:

- Chou Jikuu Yousai Macross - Ai Oboete Imasu ka (Japan) (Disc 1).zip [187.6M]
- Chou Jikuu Yousai Macross - Ai Oboete Imasu ka (Japan) (Disc 2).zip [352.1M]

This is a REDUMP game though and they tend to have a BIN file for each track on each disc. Not sure if Provenance supports that. Might need to convert to a single BIN/CUE for each disc using something like ISOBuster.

**Comment by wattseat** [comment]
I noted this exact problem with Panzer Dragoon Saga. 
I don’t know if it will help, but adding the ccd, img and sub files from the 4 cds at once will add each individual disc to the library except for disc 1. This happens wether I follow the adequate rom formatting with the m3u file or not. If I erase those 3 discs from the library and reload the app it will add the first disc to the library.
