### ISSUE TITLE
(SPM) NSLogger fails compilation due to "unsafe build flags" error.

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1583]
Attempting to compile the Release 2.0.1 Feature branch results in a **Failed** compile due to how SPM embeds NSLogger. Our PVSupport Lib uses it for logging in Pv.

When attempting to compile the Release targets Xcode (12.5 on M1) will error out with the following error message:
`"The package product 'NSLogger' cannot be used as a dependency of this target because it uses unsafe build flags."`

The previous feature/release 2.0.0 branch compiles just fine because it does NOT use NSLogger.

**Comment by JoeMatt** [comment]
NSLogger was removed for 2.0 cause I couldn't get it to work with SPM but have since updated the dependency to work.

This error is odd though, I don't have an M1 to test yet but should be here soon. I could just fork it and change that flag, which flag is it though?

**Comment by JoeMatt** [comment]
I'm removing the blocker because M1 isn't really a blocker since 
1) We are now posting official ipa's and altstore
2) very few people are using m1 macs for dev or self deployment.

We should fix this if it's still an issue but not a release blocker.

**Comment by mrjschulte** [comment]
Well, perhaps seen as selfishly to some, it's a blocker for me continuing to develop on Pv as I only have access to an M1 these days :)

**Comment by JoeMatt** [comment]
I forked the project and don't understand why they even had that flag. I'm testing without it and updating some other outdated shit they had.

**Comment by JoeMatt** [comment]
Adding this back as a blocker for @mrjschulte :), i'm just removing this for now with conditionals until i can fix the unsafe flags in a fork or something.

**Comment by JoeMatt** [comment]
fixed in 2f23768961dd8e4d613ae8679622ea902ff89513
