### ISSUE TITLE
TvOS Release does NOT build due to 'searchController' is unavailable in tvOS

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1584]
PVGameLibraryViewController.swift fails compilation for the ProvenanceTV-Release scheme due to the 'searchController' being unavailable in tvOS.

**Comment by mrjschulte** [comment]
line 1523

**Comment by JoeMatt** [comment]
fixed in f7418f113b984c34b6e5b9365d3ab87e053d6c2a
