### ISSUE TITLE
Provenance 2.0.1 unstable- Insta Crashes when loading back to back games.

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1586]
Loading two games (could even be the same game) back-to-back using Mednafen will cause PV on tvOS to crash on a random Memory related Insta-crash event on tvOS. 

`Thread 16: EXC_BAD_ACCESS (code=1, address=0x14ec4c465)`
or
`Thread 15: EXC_BAD_ACCESS (code=1, address=0xb0)`
etc...

**Comment by JoeMatt** [comment]
Device or simulator?

These bugs have existed in medanfen due to static globals and dyunload issues, but not sure why just tvOS this time.

**Comment by mrjschulte** [comment]
I Always test vanilla on an actual device.

**Comment by mrjschulte** [comment]
It's fairly odd that our 2.0.0 release did not have any of these pretty heavy stability issues w Mednafen. 

I naively tried to merge back that 2.0.0 build of Mednafen into the 2.0.1 release branch and it all builds and launches but that didn't fix anything either. So odd and leads me to believe this isn't Mednafen related perhaps.

**Comment by cheif** [comment]
I've seen something similarly to this with NES emu as well, didn't have a debugger attached so I can't post logs, but the symptoms were exactly the same. Loaded a game, went back to library and then launched a new game on the same core.
Maybe we're accidentally retaining something?

**Comment by JoeMatt** [comment]
> I've seen something similarly to this with NES emu as well, didn't have a debugger attached so I can't post logs, but the symptoms were exactly the same. Loaded a game, went back to library and then launched a new game on the same core.
> Maybe we're accidentally retaining something?

it's a common issue with Mednafen because they use global static's without resetting their values explicitly ever because they expect the front end to `dyunload()` the library on each run.

We do that, but `dyunload` on iOS doesn't actually free the memory so the values hang between loads. We have custom code to force reset some globals but we've since updated mednafen and maybe missed some new ones.

**Comment by cheif** [comment]
> > I've seen something similarly to this with NES emu as well, didn't have a debugger attached so I can't post logs, but the symptoms were exactly the same. Loaded a game, went back to library and then launched a new game on the same core.
> 
> > Maybe we're accidentally retaining something?
> 
> 
> 
> it's a common issue with Mednafen because they use global static's without resetting their values explicitly ever because they expect the front end to `dyunload()` the library on each run.
> 
> 
> 
> We do that, but `dyunload` on iOS doesn't actually free the memory so the values hang between loads. We have custom code to force reset some globals but we've since updated mednafen and maybe missed some new ones.

Yeah, sorry I wasn't very specific, but this happens with the other NES core (snes9x?) for me, not Mednafen.

**Comment by JoeMatt** [comment]
> Yeah, sorry I wasn't very specific, but this happens with the other NES core (snes9x?) for me, not Mednafen.

Oh, that's strange.

**Comment by JoeMatt** [comment]
Maybe a similiar issue with fceux

```c
void FCEU_UpdateInput(void)
{
	//tell all drivers to poll input and set up their logical states
	if(!FCEUMOV_Mode(MOVIEMODE_PLAY))
	{
		for(int port=0;port<2;port++){
			joyports[port].driver->Update(port,joyports[port].ptr,joyports[port].attrib);
		}
		portFC.driver->Update(portFC.ptr,portFC.attrib);
	}

	if(GameInfo->type==GIT_VSUNI) // Bad access on GameInfo, a global
]```

**Comment by mrjschulte** [comment]
I'll build out our current develop w 2.0.1 merged in and see what I can find.

**Comment by urherenow** [comment]
I built the latest commits last night and it crashed on an ipad pro. First opened Super Mario Brothers with Mednafen, then closed and tried to open Super Metroid with Mednafen. Insta-crash.

Good news is that my Nimbus is working. Wasn't working with my last 2.0.0 build...

**Comment by urherenow** [comment]
Also just discovered that although you can start from your last save, loading a save state while in-game causes a crash too. This happened in snes mednafen playing Super Metroid, and is consistent.

**Comment by mrjschulte** [comment]
So this crashing is NOT related to Mednafen 1.27.1. I grabbed our 2.0.0 release and integrated the 1.27.1 Mednafen Core updates into it and everything still works fine. My money is on something else being the cause so I will continue to re-integrate until it "breaks".

**Comment by mrjschulte** [comment]
(Removed Mednafen from the title as the issue is most likely NOT related to Mednafen, but something else in our Provenance codebase)
