### ISSUE TITLE
PVSupport on tvOS Needs BitCode Enabled? 

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1590]
The current Develop branch, building to tvOS Release on M1, does not build successfully.

`'/Users/yourname/Library/Developer/Xcode/DerivedData/Provenance-cirhnhwxndolbvhfskwxypaoacem/Build/Products/Release-appletvos/PVSupport.framework/PVSupport' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/yourname/Library/Developer/Xcode/DerivedData/Provenance-cirhnhwxndolbvhfskwxypaoacem/Build/Products/Release-appletvos/PVSupport.framework/PVSupport' for architecture arm64`

Enabling BITCODE for the tvOS Release target in the PVSupport Framework allows the compilation to succeed.

**Comment by mrjschulte** [comment]
Is this due to Realm being affected on how it is built on M1 w SPM?

**Comment by JoeMatt** [comment]
Fixed on develop. PVPicoDrive was re-created and tvOS automatically added bitcode since it assumed 64bit only App Store builds require that now. Disabling bitcode for that framework fixes not needing bitcode.

**Comment by mrjschulte** [comment]
Picodrive? I thought it was pro system???
