### ISSUE TITLE
Selecting "Cheat codes" from pause menu causes insta-crash

### ISSUE THREAD

**Issue by urherenow** [Provenance-Emu/Provenance#1593]
Selecting "Cheat Codes" from the pause menu results in an instant crash. Multiple cores and systems. Tried with SNES (both cores) and PSX.

 
### Expected: 
Either an interface for searching memory for manipulation, a list of codes, or a warning that no file with cheat codes is present for *this* game.

Or, Expect to not have "Cheat Codes" as a selectable thing if they are not implemented yet.

 
### Actual: 

Crash to home screen

 ### Reproduce:  

1. load game
2. Open menu
3. Select "Cheat Codes"

# 
#### NOTES  

Much wanted/popular feature, but not as important as the other game crashing bugs (such as when loading a second game, or even a save state from within a game). Suggest the Cheat option simply be hidden from SNES cores until someone has the time to look into it. EDIT: Happens with PSX as well. Probably more/most cores.

#

#### APP VERSION
-[X] 2.0.1 (current source)
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [X] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [X] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [ ] iPhone
- [X] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [X] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by mrjschulte** [comment]
Our recent updates to Mednafen may be at vault here. We're looking into it.

**Comment by urherenow** [comment]
It's not specific to Mednafen (what handles PSX?). The other snes core does the same thing.

**Comment by JoeMatt** [comment]
I found some memory leaks and null possible nil pointer usage in the menu code. 

Will test if this is fixed.
