### ISSUE TITLE
Color tint GBA

### ISSUE THREAD

**Issue by JumpinFero** [Provenance-Emu/Provenance#1594]
On VisualBoyAdvance I can save my games but romhacks have a weird color tint to it but some don’t, but the same Roms with the color tint on Mednafen on provenance emulator it shows as usual normally and normal colors, in 2.0 beta it was red tinted, 2.0.1 it’s dark blue tinted, but on mednafen I can’t save my game since I get this
![569A715E-33F7-4781-8751-AD0655A9DF40](https://user-images.githubusercontent.com/90578574/133003451-1b8eeb4f-4181-4366-aa10-193ea4ecdd3c.jpeg)
![2325B945-A5F4-41B5-9EA3-4ECCEB5EB4E6](https://user-images.githubusercontent.com/90578574/133003452-cd0d40d1-3a2f-44d4-bd8f-4b5c2921de7c.png)

And here’s the tint I’m getting red is beta 2.0 dark blue is 2.0.1 

![EA4AC98D-C548-490E-BE03-9A1E1B70168E](https://user-images.githubusercontent.com/90578574/133003508-4f4cbbf0-1aca-4c3f-b91e-989ce30aa0c0.png)
![0404C1D1-15D7-4BCE-9C96-778B8C962EC0](https://user-images.githubusercontent.com/90578574/133003509-c44c6df1-d0c9-4c42-ba74-ef6eda7eb130.png)

**Comment by mrjschulte** [comment]
After some back and forth this was determined to be a "feature" of the games day and night cycle. Nothing to do here. Closing.
