### ISSUE TITLE
iCloud sync not working

### ISSUE THREAD

**Issue by wattseat** [Provenance-Emu/Provenance#1598]
iCloud sync seems to do nothing. I don’t see a Provenance folder in the iCloud Drive. 

 
### Expected: 

Syncing of save states and other files between devices. 

 
### Actual: 

No syncing of any kind

 ### Reproduce:  

1. Sideload latest release (2.0.2) on iPad and iPhone
2. Add Roms to the library, create save states in one device. 
3. Check the other for any kind of sync. 

# 
#### NOTES  

#

#### APP VERSION
- [x] 2.0.2
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Sideloading doesn't work with iCloud unfortunately because entitlements must be set at compile time.

now that AltStore is the preferred install choice I'm probably just going to remove iCloud and find a better solution.
