### ISSUE TITLE
iCloud sync is not working

### ISSUE THREAD

**Issue by frootloop88** [Provenance-Emu/Provenance#1603]
in settings there is an option for iCloud sync for battery stats. Its turned on but it doesn't work

#### APP VERSION
- [ ] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] 14.x
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by alexchandel** [comment]
This still appears to be broken. Any updates?

**Comment by JoeMatt** [comment]
It's being removed for something else. iCloud is unreliable, complex, and requires work arounds for code signing.
