### ISSUE TITLE
N64 Crashing on some roms

### ISSUE THREAD

**Issue by joniell87** [Provenance-Emu/Provenance#1608]
Noted Starcraft 64 Rom crashes on mission select screen.

Actual: Bug was not present on 1.5b
Confirmed this bug is present on 2.0.0, 2.0.1, 2.0.2 regardless of iOS device (tested iPhone SE Gen1, iPhone 8, iPhone SE Gen2) On iOS 14.6, 14.7.1 and 14.8.

Following alternatives tested on iPhone all iPhones running 2.0.2 (independently):
- Enabled/Disabled: Multi-thread GL, 4x Multi-sampling GL, Native Scale
- Core options tested: GFX plugin, RSP Plugin, HW lighting enabled/disabled.
- RSP Plugin: RSPHLE, CXD4

#### NOTES  
Interesting find: Interger scale plays rom without displaying image.

#### APP VERSION
- [* ] 2.0.0/2.0.1/2.0.2
- [*] 1.5 *beta*
- [ ] 1.4

#### APP SOURCE
- [*] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [*] [Side-Loading](https://git.io/vpYzf) {Altstore}
- [ ] [Building](https://git.io/vpYzv) *from Source*

#### PLATFORM
- [*] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [*] 14.6/14.7.1/14.8
- [ ] 13.x
- [ ] 12.x
- [ ] 11.x
- [ ] 10.x

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Thanks, will look into this for probably release after next.

**Comment by JoeMatt** [comment]
This is working for me on 2.x on iOS 15 (don't have a 14 device).

GlideN64/RSPHLE/HW Lighting ON in core options.

I'm closing since this isn't being reported by anyone else. If it continues after next release, reopen.
