### ISSUE TITLE
One Multi-disc game not working

### ISSUE THREAD

**Issue by wouter1984** [Provenance-Emu/Provenance#1626]
Good Day,

I have created several multi-disc m3u files (X-Files, Driver 2, Grandia, Metal Gear Solid, Oddworld - Abe's Exoddus, Resident Evil 2 and 70s Robot Anime Geppy-X

All work fine except 70s Robot Anime Geppy-X, I can't seem to get this one working. Anyone got this game working with multi-disc (4) support?

I have checked the cue files, they are naming the associated bin files correctly.
The 4 cue files have been listed in a m3u file, but still no swap disc option when running the game.

renamed the files several times and afterwards changed the cue and m3u content, but can't get this game to work.

**Comment by wouter1984** [comment]
By the way, I am on iOS 12.5.5. and am running latest 2.0.2 ipa build sideloaded with Altstore

**Comment by JoeMatt** [comment]
tested working in #1750
