### ISSUE TITLE
Won't Open (iPad Pro Gen 2 - 12.9”)

### ISSUE THREAD

**Issue by Sweek9** [Provenance-Emu/Provenance#1627]
After getting it on the tablet pressing on it pops up: **Unable To Install “Provenance”** This app cannot be installed because its integrity could not be verified. Google/YouTube guides say to wipe Safari data and open it in airplane mode with wifi off, didn’t fix it. They say if it doesn’t work that means it’s not compatible with my device, but I saw on Reddit someone else using it on a 2018 iPad Pro 2y ago.

**Comment by urherenow** [comment]
Sigh...


Settings -> General -> VPN and Device Management -> "trust" your signing cert.
