### ISSUE TITLE
Automatic Artwork retrieval not working.

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1630]
Built current develop branch for iOS and tvOS and the automatic artwork importing no longer works.

**Comment by mrjschulte** [comment]
This is NOT Pv related, looks like the Gamefaqs urls have changed for the artwork DB we use from OE.

Example Old URL:
https://gamefaqs1.cbsistatic.com/box/9/0/7/51907_front.jpg

New URL:
https://gamefaqs.gamespot.com/a/box/9/0/7/51907_front.jpg

**Comment by mrjschulte** [comment]
And here's the new update.
https://github.com/OpenVGDB/OpenVGDB/releases/tag/v29.0

I'll make a PR.

**Comment by JoeMatt** [comment]
Fixed in d45d9c4c92d4b8298ee352c51cf0af941474d69d
