### ISSUE TITLE
SONIC CD: Black Screen when changing Zones.

### ISSUE THREAD

**Issue by Beanie-Inki** [Provenance-Emu/Provenance#1635]
In the game Sonic CD for the Sega CD, whenever a boss is defeated in the third Act of a Zone, you can then destroy a machine afterwards in order to end the level and move on to a new Zone.

Unfortunately, instead of briefly using a black screen to transition to the next level, it just stays at the black screen indefinitely.

Oddly enough, I have been able to get it to work as normal twice, but I haven't a clue what I did to make it work.
The first time, I destroyed every monitor in the level, collected every ring, and beat the boss without getting hit. The second time, I simply loaded the final screen entirely before destroying the machine. I've been trying to load the next Zone again this time, using a combination of the previously mentioned methods, to no avail.

 
I expected to be presented with a black screen transition to the next Zone.

 
I ended up recieving an indefinite black screen.

 ### Reproduce:  

1. Play the game as normally up to the first boss you fight.
2. Beat the boss and destroy the machine afterwards.
3. Black screen should appear and not go away. No audio will be present either.

# 
#### NOTES  

This does not apply to transitioning to Special Stages.

#

#### APP VERSION
2.0.2

#### APP SOURCE

- Provenance-Emu GitHub  *&nbsp;(Official)*

#### INSTALLED BY 

[Side-Loading](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/sideloading)

#### iOS/tvOS VERSION

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

@mrjschulte

**Comment by JoeMatt** [comment]
Not a lot we can do about that if it's an upstream bug other than update the code if it's fixed since our version of Sega CD.

**Comment by Beanie-Inki** [comment]
Fixed. I for some reason just had to save state before destroying the machine, then reset and save RAM data. I'd load the save again and voila it transitions.
