### ISSUE TITLE
[Feature Request] upgrade mupen64plus to mupen-next

### ISSUE THREAD

**Issue by Spidy123222** [Provenance-Emu/Provenance#1636]
Libretro has a updated core called mupen64plus-next that has more accurate emulation via the paraLLEl-rdp plug-in that was made. It has noticeable speed improvements for some games that are difficult to run and also emulate accurately. LLE emulators tend to emulate games correctly especially with frame buffer ones like Mario kart 64. 

There is also other plugins in it that adds Nintendo 64DD emulation to add more games that aren't just normally supported by regular mupen64plus. It uses the latest version of glide but likely will be updated on provenience soon. The rdp core that is being used uses Vulkan so moltenvk would be need o be used to make that one work. An option to switch between these graphics plugins would be nice if it happens.

Libretro core lists the plugins it includes in the readme. The core they use for libretro is a port in plug-in form for mupen64plus.

#
 

I can't think of any easier solution than porting over the plugins themself.

#
 

Libretro mupen64plus-next: https://github.com/libretro/mupen64plus-libretro-nx

64DD: https://youtu.be/JDB64iZqLxY

Parallel-rdp core: https://youtu.be/A1--EFlJL5w

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
There's really no reason to though,

mupen64plus
GLideN64
cxd4
parallel-rsp
angrylion-rdp-plus (Currently based on it's ParaLLel variant)

We already use all of those, except parallel RSP because it's not great on ARM and we don't need it 

Angrylion is also CPU intensive though I think there's newer ports.
This project exists for libretto as an alternative to the dynamic loading of plugins.

I'd rather just add the ARM versions of the other plugins as a run time option (as well already do for rice/gliden64, cxd4/RDPHLE) as required than port an entire new code base.

Closing this issue. If you can come up for a good reason to support a whole other fork, reply, but if it's just "because", I'm happy with the N64 status as-is. It's one of, if not, the best performing mobile port out there right now.

**Comment by Spidy123222** [comment]
> There's really no reason to though,
> 
> 
> 
> mupen64plus
> 
> GLideN64
> 
> cxd4
> 
> parallel-rsp
> 
> angrylion-rdp-plus (Currently based on it's ParaLLel variant)
> 
> 
> 
> We already use all of those, except parallel RSP because it's not great on ARM and we don't need it 
> 
> 
> 
> Angrylion is also CPU intensive though I think there's newer ports.
> 
> This project exists for libretto as an alternative to the dynamic loading of plugins.
> 
> 
> 
> I'd rather just add the ARM versions of the other plugins as a run time option (as well already do for rice/gliden64, cxd4/RDPHLE) as required than port an entire new code base.
> 
> 
> 
> Closing this issue. If you can come up for a good reason to support a whole other fork, reply, but if it's just "because", I'm happy with the N64 status as-is. It's one of, if not, the best performing mobile port out there right now.
> 
> 
> 
> Also DD is supported by newest mupen. Can't remember if our version does, but if not, I'm already the process of updating it and I know for a fact DD support is in there.


I just gone through what was said and went through benefits. The core that is used for mupen64plus-next at this moment is not the same as the parallel-rdp core I thought it was for using the angrylion plug-in but I was wrong. The only port of RDP that is through someone currently porting it from parallel-rdp. So it isn't worth it at the moment until something like that would be done. Hope you understand where I was coming from though.

Goal of LLE is for as accurate as possible hardware level emulation from what I'm told. The core for parallel-RDP has listed benefits on their own repo where it does reference angrylion but also trying to improve on it. 

They seem to have actually improved on angrylion and made cpu utilization much less harsh by using modern Vulkan implementations and normal improvements that they have done.

So it's not ready I guess. Would have to look into this another time but I'll give links to sources in case I missed anything that I used in these. 

Rdp port: https://mudlord.github.io/Parallel-RDP/

Another Rdp Port using last one but looks like for unofficial mupen64plus android port: https://github.com/mupen64plus-ae/parallel-rdp-standalone

Parallel-rdp: https://github.com/Themaister/parallel-rdp



Listed improvements they gave.

- Asynchronous pipeline optimization
 
- Tile-based rendering

- Synchronization (syncs cpu and gpu better)

- Asynchronous compute (improves loads)

- **Much** faster LLE RDP emulation of N64 compared to a CPU implementation as parallel graphics workloads are offloaded to the GPU.

- A backend renderer for standalone engines which aim to efficiently reproduce faithful N64 graphics.

- Hopefully, an easier to understand implementation than the reference renderer.

- An esoteric use case of advanced Vulkan compute programming.


Sorry for the inconvenience. Thanks for you're response and I hope didn't interrupt anything important. I personally like accurate and efficient emulation. so that's why it lead me to post this feature request.

I know that LLE emulation is the most accurate form of emulation from what I have seen but it just is a bit more slower (depending how it is implemented) because of needing to emulate system calls more then api calls like HLE I'm also on the discord.

**Comment by Spidy123222** [comment]
> There's really no reason to though,
> 
> 
> 
> mupen64plus
> 
> GLideN64
> 
> cxd4
> 
> parallel-rsp
> 
> angrylion-rdp-plus (Currently based on it's ParaLLel variant)
> 
> 
> 
> We already use all of those, except parallel RSP because it's not great on ARM and we don't need it 
> 
> 
> 
> Angrylion is also CPU intensive though I think there's newer ports.
> 
> This project exists for libretto as an alternative to the dynamic loading of plugins.
> 
> 
> 
> I'd rather just add the ARM versions of the other plugins as a run time option (as well already do for rice/gliden64, cxd4/RDPHLE) as required than port an entire new code base.
> 
> 
> 
> Closing this issue. If you can come up for a good reason to support a whole other fork, reply, but if it's just "because", I'm happy with the N64 status as-is. It's one of, if not, the best performing mobile port out there right now.
> 
> 
> 
> Also DD is supported by newest mupen. Can't remember if our version does, but if not, I'm already the process of updating it and I know for a fact DD support is in there.


Apparently I found out that the angrylion in mupen64plus-libretro-nx is not the parallel-rdp core port than I thought it was. The comment on the angrylion core they made made it seem like to me it was a port of parallel rdp core which in fact it wasn’t and it also made me think it wasn’t a plug-in so yes I also thought parallel was an emulator itself. I had to delete my previous reply for just mess. I referenced a parallel-rdp port link that somone posted. Not sure if it’s completely relevant. I found out it was a plug-in by a little more research on other sites. [Link to site that helped me.](https://emulation.gametechwiki.com/index.php/Recommended_N64_plugins#google_vignette) 

Rdp port last referenced before I deleted messy reply: [https://mudlord.github.io/Parallel-RDP/]()

Parallel-rdp: [https://github.com/Themaister/parallel-rdp]()

Libretro showcase of rdp and comparisons of other plugins a bit (recommended to read): [https://www.libretro.com/index.php/category/parallel/]()

From looking into it. It seems the plug-in supports android and haven’t seen any issue from people complaining about any android issues and seen satisfaction with how it feels and performs.

**Listed improvements (repo and article from libretro mixed in together.).**

- referenced the angrylion-rdp plug-in for their own implementations. (so it should have most of what angrylion-rdp has if everything is implemented from it.)

- Ubershaders with Asynchronous pipeline optimization
 
- Tile-based rendering

- Synchronization (syncs cpu and gpu better)

- Asynchronous compute (improves loads)

- **Much** faster LLE RDP emulation of N64 compared to a CPU implementation. As the parallel graphics workloads are offloaded to the GPU.

- A backend renderer for standalone engines which aim to efficiently reproduce faithful N64 graphics.

- An easier to understand implementation than the referenced renderer.

- An esoteric use case of advanced Vulkan compute programming. (They said this on their repo)

- Enforcing RDRAM coherency

- GPU-driven TMEM management

- GPU bound performance (they must be proud of this compared to angrylion by using Vulkan throughout development)

- code for android script (looked in code and found android folder so could or could not)

- 8/16-bit integer support for RDRAM management

- Correct Dithering

- The entire VI postprocessing pipeline renders better than others at higher resolutions for bit exact rendering.

- Accurate Depth bias

- Higher compatibility with games

Sorry for the inconvenience. Thanks for you're response and I hope didn't interrupt anything important. I personally like accurate and efficient emulation. so that's why it lead me to post this feature request.

I know that LLE emulation is the most accurate form of emulation typically from what I have seen but it just is a bit more slower (depending how it is implemented) because of needing to emulate system calls more then api calls like HLE. There are also many pros and cons of HLE and LLE types of emulation and honestly if one is better than the other for depending on the given console. One would likely need both types in case one doesn’t work well on one than the other and I feel that parallel-rdp is a great LLE offering. Btw I'm also on the discord.

**Comment by JoeMatt** [comment]
I've looked into Parallel RDP before, it's on my radar. It wasn't a simple copy and compile though so it's on the back burner.
