### ISSUE TITLE
[Feature Request] n64 Touch controls

### ISSUE THREAD

**Issue by Spidy123222** [Provenance-Emu/Provenance#1637]
It is currently hard to use the n64 touch controls in provenience. The layout is hard to use compared to an app called Delta where the controls have everything needed and supports swiping to press multiple buttons at once.

 

Would like a proper joystick and dpad to be separate from each other. Likely have option for multiple layouts for the controllers for the type of games that use more of the left side of a n64 controller and or more of right side and have a neutral layout where it has all layed out as default likely similar fashion as delta as it's easy to use or your own way.

For a proper analog stick it hard to to certain movements super Mario 64 without tapping a lot to get slight movements or it freaking out between 2 inputs because trying to do a certain angle it doesn't like.

#
 

#
 

Provenience:
https://user-images.githubusercontent.com/64176728/143726934-bf74f37d-01a5-477d-83e3-4ac70084dbf0.MOVreplaceWithAdditionalNotesOrDelete

Delta:
https://user-images.githubusercontent.com/64176728/143727035-65240a25-894e-43fd-9154-e99a7ee85f0c.MOV

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
#801 more or less
