### ISSUE TITLE
Version 2.0.3 is not installed on AltStore

### ISSUE THREAD

**Issue by RaphaelZimermann** [Provenance-Emu/Provenance#1655]
The 2.0.2 IPA version installs fine on my iPhone 11;  but version 2.0.3 crashed AltStore during installation;  is there a chance that the IPA is corrupted?  I downloaded the IPA several times;  All previous versions that I downloaded now for testing install correctly.

Thanks

**Comment by JoeMatt** [comment]
IPA is working with other sideload methods.
It's crashing altstore on desktop (using hidden sideload menu) and mobile for me. I'm assumig the same code is used by both.

I submitted crash logs to AltStore discord. Waiting to hear back.

**Comment by RaphaelZimermann** [comment]
Ok, thanks!

**Comment by RaphaelZimermann** [comment]
Version 2.0.4 don't install also 😣

**Comment by JoeMatt** [comment]
> Version 2.0.4 don't install also 😣

i'm aware, it's altstore, not the app.

**Comment by JoeMatt** [comment]
fixed in upcoming #1750
