### ISSUE TITLE
[Request] Add CoreOptions for N64 Video

### ISSUE THREAD

**Issue by HappehLemons** [Provenance-Emu/Provenance#1678]
N64 core has a bunch of weird issues:

1) No video core options, with bad defaults selected. It seems to be running at a upscaled + filtered default resolution. It's a bad choice considering there are games that don't even run full-speed and need to run at 1x native sale to be playable (Gauntlet legends for example) 

2) No option to disable the expansion pack (some games require this)

Using version 2.0.4 on iPhone 12 Max Pro

**Comment by JoeMatt** [comment]
done in #1387 #1716
