### ISSUE TITLE
Feature Request - Make "shaders" folder accessible under iOS files.app

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1684]
Make the Provenance shader folders:

```
/Provenance/Utilities/shaders
-blit	
-crt	
-default
```
accessible to the files.app on iOS.This will allow us access to the various .glsl shaders and allow for on device editing without having to use Xcode.

**Comment by JoeMatt** [comment]
Can re-use the code that copies .ini files. First it checks if they exist, if not, copies to that dir and loads them from there.

Only issue is, what to do if we update the internal version, though i'm sure the number of people editing shaders is tiny and can just deal with it, or we don't update.

**Comment by mrjschulte** [comment]
Yeah, no one besides myself will probably use this but it allows for some ultra-portable dev with tooling that will exceed what Xcode can do so if we want to be able to have some more agile progress in that area AND this is easy to add then I say lets do it !~

**Comment by JoeMatt** [comment]
done in 17efaeefb84e5a399a9db7e9f18e15b6c80b24a4
