### ISSUE TITLE
Bug Report: Mednafen listed twice when choosing core

### ISSUE THREAD

**Issue by urherenow** [Provenance-Emu/Provenance#1711]
### Expected: 

Provide list of cores available for any given rom, with no duplicates

 
### Actual: 

Mednafen is listed twice

 ### Reproduce:  

1. build from source
2. select snes game
3. 

#### APP VERSION
 Latest tree as of 1/15/2020

#### APP SOURCE

- Provenance-Emu GitHub  *&nbsp;(Official)*
- 
#### INSTALLED BY 

Building
#### PLATFORM

iOS and iPAD
#### iOS/tvOS VERSION

15.2
-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Did you update from a previous version?
I think this is due to a prior misspelling and now the database is showing 2 copies of mednafen since the ID was misspelled.

**Comment by urherenow** [comment]
Unpaid account, so yes, I always rebuild without uninstalling first. It's a pain to transfer the roms back and forth, and the database used doesn't even consider crc32. Either they are named exactly right, or they are not recognized 😒

**Comment by urherenow** [comment]
Moved the rom folders, deleted the app, re-built it, then moved the folders back. This indeed took care of the issue.
