### ISSUE TITLE
Bug Report: Mednafen bsnes core is broken in current tree

### ISSUE THREAD

**Issue by urherenow** [Provenance-Emu/Provenance#1712]
----- BUG REPORT: Be clear, concise and thorough, beginning with a summary. --->

When choosing Mednafen for an SNES game, Provenance crashes

 
### Expected: 

Run the selected game

 
### Actual: 

Crash in bsnes core at around:

void Scheduler::enter() {
  co_switch(thread_active);
}
with: "thread 1: EXC_BAD_INSTRUCTION (code=1, subcode=0xe8a16ff0)"

 ### Reproduce:  

1. clone and build source
2. select snes game
3. choose Mednafen
4. *crash*

# 

#### APP VERSION
 Latest tree as of 1/15/2022 (2.0.5 develop)

#### APP SOURCE

- Provenance-Emu GitHub  *&nbsp;(Official)*

#### INSTALLED BY 

[Building](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source) *from Source*

#### PLATFORM

iOS and iPad
#### iOS/tvOS VERSION

15.2
-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
cannot reproduce

**Comment by urherenow** [comment]
It happens on both iPhone and iPAD. It happens when cloning from scratch, and building with a fee dev account. Are you on 15.2? Did you do a clean install?

**Comment by urherenow** [comment]
My sincere apologies. I hate xcode. Even deleting the folder and starting from scratch, causes issues with derived data. I had to nuke that folder, and now it runs fine.
