### ISSUE TITLE
[Feature] Enable TVOS Screen Saver

### ISSUE THREAD

**Issue by tomp8628** [Provenance-Emu/Provenance#1717]
TVOS screen saver does not come on when Provenance is left open.  Confirmed on .ipa 2.0.4 with newest TVOS running, 15.2

**Comment by JoeMatt** [comment]
Currently this is by design, to allow the webserver and imports to work all the time.


What's the reason for wanting the Screen saver to be enabled rather then just backing out?

I'd be willing to add support back when the menus are active, but have to look into the consiquences first.

**Comment by JoeMatt** [comment]
This actually already exists. See the settings for `Disable Auto Lock`
