### ISSUE TITLE
Loading Save States crashes iPadOS app

### ISSUE THREAD

**Issue by timbo3344** [Provenance-Emu/Provenance#1755]
Trying to load a save state from within a game or from title context menu results in the app crashing.  It only works to load a save from "recently saved" menu.

 
### Reproduce:  Load a save state from within a game or the context menu of a game title

# 
#### NOTES  

This is happened on every iPad and Provenance version I have ever installed.  I have wiped my iPad and reinstalled every app from scratch including altstore and provenance and it will always crash when I load a save save from within a game or the title context menu.  It happens with games from any system I've tried (Atari, NES, SNES, Genesis, N64, Gameboy).  I can load the recently saved icons from the home menu but that's the only way to successfully load save states.

#

#### PLATFORM
iPad

#### iOS/tvOS VERSION

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by timbo3344** [comment]
app version didn't post:
app: 2.0.5 Beta from Provenance Discord
installed by Altstore
IpadOS 15.3.1

**Comment by timbo3344** [comment]
screenshot video: https://www.dropbox.com/s/00zsnn8g06bat3y/RPReplay_Final1644779906.MP4?dl=0

**Comment by urherenow** [comment]
Can't duplicate. I build myself though.
