### ISSUE TITLE
[Feature] Update FCEUX Core

### ISSUE THREAD

**Issue by lonkelle** [Provenance-Emu/Provenance#1797]
I’ve been finding more NES homebrew that won’t play in Provenance lately only to find out that FCEU is not on 2.6+, instead its years behind the latest release: http://sourceforge.net/projects/fceultra is the current release while Provenance is on:  https://github.com/Provenance-Emu/Provenance/blob/09fda1e08fb474329546e687a772515c81c4ebaf/Cores/FCEU/PVFCEU/Core.plist#L19

**Comment by lonkelle** [comment]
It links directly to the source of that same version on the SourceForge description. It’s hosted on GitHub their latest source: https://github.com/TASEmulators/fceux/blob/master/src/version.h

**Comment by JoeMatt** [comment]
forgot the link,
https://github.com/Provenance-Emu/fceux

**Comment by JoeMatt** [comment]
almost working,
https://github.com/Provenance-Emu/Provenance/pull/1810

fully builds and then fails to link, some missing symbols and import paths need fixing. soon
