### ISSUE TITLE
[Bug] SNES9x controller non responsive

### ISSUE THREAD

**Issue by tomp8628** [Provenance-Emu/Provenance#1848]
using Nimbus on ATV4k, SNES9x core, controller does not respond.  1st player light does show on controller.  Other SNES cores do not replicate the controller issue and work fine. 

 
### Expected: 

controller to be responsive/recognized

 
### Actual: 

Controller not recognized/responsive. 

 ### Reproduce:  

1. 2.1 build ATV4k
2. Any SNES rom
3. Nimbus controller

# 
#### NOTES  

#

#### APP VERSION
2.1 official ipa

#### INSTALLED BY 

<!-- 
[Side-Loading](

#### PLATFORM
Tvos

#### iOS/tvOS VERSION
Current

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by urherenow** [comment]
It’s really a pain for me to build on my aTV, because I don’t have a real Mac. Was this the very first time you built it for your aTV? If not, you’ll likely need to start from scratch to ensure this is really a bug. “Scratch” means:

1) Delete the app from your aTV
2) Find and delete your “derived data” folder (Google will help if you don’t know where… I’ve created a shortcut to it on my desktop)
3) Clean your build folder
4) Build it again, import your games and test

**Comment by JoeMatt** [comment]
I'm investigating this now

**Comment by fkysly** [comment]
SNES play <zelda: a link to the past>, controller not working too. I'm using Xbox Controller.
other Zelda series include nes/n64, working normal.

**Comment by JoeMatt** [comment]
https://user-images.githubusercontent.com/399864/159646200-27e6d5b2-9cbe-483d-94c5-bcb2779d328d.mp4

Seems to be working fine for me.
Apple TV 4K, Nimbus controller

**Comment by JoeMatt** [comment]
Checking Zelda specifically now. Will update with results.

**Comment by radoslavkalinov** [comment]
I have the same issue on ipad pro 12.9 (2020) ios 15.2

There is no input response for any snes9x running game, mednafen works fine.

When the controller is off, no virtual button-layout appears.

i play all my snes games on snes9x, so hope to see this fixed soon

**Comment by mrjschulte** [comment]
Looks like something in 6ee93c0043b526c6cb2032c469e45567c0d000dc broke it. Let me take a deeper look.

**Comment by mrjschulte** [comment]
#1929 submitted to address this potentially.
