### ISSUE TITLE
Sega Genesis GX Plus "Video Overscan options not accurate on first try.

### ISSUE THREAD

**Issue by mrjschulte** [Provenance-Emu/Provenance#1856]
Sega Overscan options: Not working.
From a full on Vanilla pull and build.
Import Sega Genesis title into Pv
In GameLibraryView go to a Title, and longpress to pull up menu and select Genesis Plus GX Options 
Go into the Video Overscan options
Note it is set to "none"
Change it to "Full"
Launch game, note border appearance visually appears to be set to the "Horizontal" option instead???

That's clearly Wrong

Exit game, 
In GameLibraryView go to a Title, and longpress to pull up menu and select Genesis Plus GX Options 
Go into the Video Overscan options
Note it is still set to "Full"
Re-select "Full" and confirm with a press
Launch game,
Borders are no set correctly.

Are the Genesis Options defaulting to something on first time use/init?

**Comment by JoeMatt** [comment]
fixed in this commit,
e25f60e2f6c68c990451097c78bc9d24147562ff
