### ISSUE TITLE
Fix SIGSEGV in void std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*) (__tree:81)

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#1885]
### Stacktrace ###

void std::__1::__tree_balance_after_insert<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*, std::__1::__tree_node_base<void*>*) (__tree:81);PVMupen64PlusVideoGlideN64

std::__1::__tree<std::__1::__value_type<CombinerKey, graphics::CombinerProgram*>, std::__1::__map_value_compare<CombinerKey, std::__1::__value_type<CombinerKey, graphics::CombinerProgram*>, std::__1::less<CombinerKey>, true>, std::__1::allocator<std::__1::__value_type<CombinerKey, graphics::CombinerProgram*> > >::__insert_node_at(std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>*, std::__1::__tree_node_base<void*>*&, std::__1::__tree_node_base<void*>*) (__tree:2081);PVMupen64PlusVideoGlideN64

std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<CombinerKey, graphics::CombinerProgram*>, std::__1::__tree_node<std::__1::__value_type<CombinerKey, graphics::CombinerProgram*>, void*>*, long>, bool> std::__1::__tree<std::__1::__value_type<CombinerKey, graphics::CombinerProgram*>, std::__1::__map_value_compare<CombinerKey, std::__1::__value_type<CombinerKey, graphics::CombinerProgram*>, std::__1::less<CombinerKey>, true>, std::__1::allocator<std::__1::__value_type<CombinerKey, graphics::CombinerProgram*> > >::__emplace_unique_key_args<CombinerKey, std::__1::piecewise_construct_t const&, std::__1::tuple<CombinerKey const&>, std::__1::tuple<> >(CombinerKey const&, std::__1::piecewise_construct_t const&&&, std::__1::tuple<CombinerKey const&>&&, std::__1::tuple<>&&) (__tree:2097);PVMupen64PlusVideoGlideN64

CombinerInfo::setCombine(unsigned long long) (map:1521);PVMupen64PlusVideoGlideN64

CombinerInfo::update() (Combiner.cpp:0);PVMupen64PlusVideoGlideN64

GraphicsDrawer::_updateStates(DrawingState) const (GraphicsDrawer.cpp:643);PVMupen64PlusVideoGlideN64

GraphicsDrawer::_prepareDrawTriangle() (GraphicsDrawer.cpp:717);PVMupen64PlusVideoGlideN64

GraphicsDrawer::drawTriangles() (GraphicsDrawer.cpp:746);PVMupen64PlusVideoGlideN64

RSP_ProcessDList() (RSP.cpp:59);PVMupen64PlusVideoGlideN64

send_dlist_to_gfx_plugin (hle.c:197);PVMupen64PlusRspHLE

DoRspCycles (plugin.c:426);PVMupen64PlusRspHLE

write_rsp_regs (rsp_core.c:278);PVMupen64Plus

r4300_write_aligned_word (memory.h:87);PVMupen64Plus

JR (mips_instructions.def:893);PVMupen64Plus

CoreDoCommand (pure_interp.c:730);PVMupen64Plus

### Reason ###

SIGSEGV

### Link to App Center ###

* [https://appcenter.ms/orgs/Provenance-Emu/apps/Provenance-EMU/crashes/errors/245645699u](https://appcenter.ms/orgs/Provenance-Emu/apps/Provenance-EMU/crashes/errors/245645699u)

**Comment by tadepalli-vinay** [comment]
Hi @JoeMatt, 
Could you update on how above segmentation fault issue in standard library function got resolved at your side? 
I am facing similar issue right now, looking for solutions to this issue.
