### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by joakyhsf69** [Provenance-Emu/Provenance#1887]
The latest version, 2.1.0 does not work on my Apple TV 4k 1Gen running tvOS 15.4, signed via signulous and installed via sideloading. The previous version opens fine

 
### Expected: 
The app opens without problems

 
### Actual: 

The app opens and closes by itself

 ### Reproduce:  

1.Sign de app by signulous
2. Install with xcode
3. Open App

#

#### APP VERSION
2.1.0

- Provenance-Emu GitHub  *&nbsp;(Official)*

#### INSTALLED BY 
[Side-Loading](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/sideloading)

#### PLATFORM
TVOS

#### iOS/tvOS VERSION
15.4

**Comment by JoeMatt** [comment]
it works fine in all our testing on that platform, if you're having issues, ask in our discord help channel
