### ISSUE TITLE
Build Failure on tvOS

### ISSUE THREAD

**Issue by IndyShepherd** [Provenance-Emu/Provenance#1903]
Hello, 
I continue to receive the same build failure error message when almost complete. 

Showing All Errors Only -> Compile Swift source files (arm64)
/Users/patrickfisk/Provenance/Provenance/Emulator/CoreOptionsViewController.swift:126:108: 
'sheetPresentationController' is unavailable in tvOS'
'sheetPresentationController' has been explicitly marked unavailable here

I am installing from MacBook Monterey. I have xCode 13.3. I have downloaded the latest Source Code for Provenance. I am Choosing ProvenanceTV-Release > myAppleTV. (tvOS 15.4)

 
### Expected: 

Expecting the Build to complete Successfully

 
### Actual: 

The Build fails with error message above

 ### Reproduce:  

1. Build Provenance from Source
2. Setup Provenance Workspace
3. ProvenanceTV-Release -> AppleTV (tvOS 15.4)

# 
#### NOTES  

#

#### iOS/tvOS VERSION

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by IndyShepherd** [comment]
As information - I found the file where that was being called: CoreOptionsViewController

if #available(iOS 15.0, *), let sheetPresentationController = actionController.sheetPresentationController {

//  I changed it to this:

if #available(iOS 15.0, *), let sheetPresentationController = actionController.popoverPresentationController {

***

The Build is working fine now! (tvOS 15.4)

**Comment by JoeMatt** [comment]
> if #available(iOS 15.0, *), let sheetPresentationController

this should be fixed already on develop,

```swift
                            if #available(iOS 15.0, *), let sheetPresentationController = actionController.sheetPresentationController {
//                                let cellRect = self.tableView.rectForRow(at: IndexPath(row: rowIndex, section: sectionIndex))
                                sheetPresentationController.sourceView = self.tableView
//                                sheetPresentationController.sourceRect = cellRect
                            } else if let popoverPresentationController = actionController.popoverPresentationController {
                                let cellRect = self.tableView.rectForRow(at: IndexPath(row: rowIndex, section: sectionIndex))
                                popoverPresentationController.sourceView = self.tableView
                                popoverPresentationController.sourceRect = cellRect
                             }
                             ```

**Comment by JoeMatt** [comment]
nevermind, this is broken on current xcode for me still as well. It was working before...

**Comment by JoeMatt** [comment]
fixed and pushed to develop
