### ISSUE TITLE
Please fix the button layouts

### ISSUE THREAD

**Issue by omarc08** [Provenance-Emu/Provenance#1915]
I just recently installed Provenance because I wanted a PS1/PSX emulator. Everything was fine until I played a game. The buttons were overlapping and it was so annoying. I have looked for solutions on Reddit, Discord, and other issues posted on this repo. I also tried going in & out of full screen mode. That seems to remove the joystick that is stuck on the bottom. But the buttons on the right are still overlapping with the start buttons so when I'm pressing X, I sometimes press the start. This is really annoying when playing fast paced games like Tekken. An easy fix to this Problem would just be to give the user a way to move the buttons and resize them on the screen. It's pretty clear that this is not an easy task because you guys would've done it by now. But please try and fix this in the next update.

(Also don't tell me to use a controller. I know I can use one but I want to be able to play with touchscreen instead)

![image](https://user-images.githubusercontent.com/95196282/171980751-f6ed1e67-82e6-4751-880e-4cc085bd286e.jpeg)

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Known issue. Meant to do a new release to fix this.
I think I fixed this in develop but I need to double check.

I'll leave this ticket open.

**Comment by omarc08** [comment]
> Known issue. Meant to do a new release to fix this.
> 
> I think I fixed this in develop but I need to double check.
> 
> 
> 
> I'll leave this ticket open.

Ok cool. I found a temporary fix which was to use an older version.
