### ISSUE TITLE
smb:// Support

### ISSUE THREAD

**Issue by Lodovik** [Provenance-Emu/Provenance#192]
Because the Apple TV4 has very strict local storage limitations, it would be great to be able to browse network shares to load ROMs. If Provenance could remember the path, that would make it almost like local storage. Saves could be stored locally.

**Comment by fuzhuo** [comment]
+1
Game roms is huge, especially when meet PSX games..

**Comment by jasarien** [comment]
I don't have plans to include SMB support at this time. You can still store your ROMs on your SMB share and transfer them over your network manually as and when you like - you can backup your saves from the Web UI and then delete the ROMs if you're trying to free up space.

**Comment by techdragon** [comment]
With the possibility of PSX support being added soon, both sizes of AppleTV are going to become more likely to have storage related issues for users. 

I'm a developer too so I know this is a large feature to ask for, and I'm certainly not asking for someone else to give me a pony. But I think considering the possibility that Provenance will gain support for Emulating games from consoles where rom sizes of several hundred megabytes or larger are the norm... the issue of external off device storage should be reconsidered. 

@jasarien - Could this possibly be reopened and the won't fix flag removed? Perhaps a label of community contribution necessary or something else could be used to show you don't have any desire to work on this yourself, but the addition by someone else would be welcome?

**Comment by sevdestruct** [comment]
UIDocumentPicker now supported, this is pretty much, so less needed but if we're talking about a way to help AppleTV with a custom feature to support something similar—materialize in a different ideas being discussed.

**Comment by JoeMatt** [comment]
closed by #495
