### ISSUE TITLE
Closing already completed Issues on the GitHub 

### ISSUE THREAD

**Issue by Carter1190** [Provenance-Emu/Provenance#1937]
the GitHub issues section is flooded with issues that have already been fixed or done, but have not been closed, such as #754 as well as #997 which have been merged in long ago, but remain open for unknown reasons

 

Closing down issues that have already been fixed, or update them if still occurring on latest version if a bug or update them if not implemented as of latest version
#
 

none

#
 

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
closed those issues
