### ISSUE TITLE
Unable to load any Nintendo 64 ROMs using PVMupen64Plus on develop branch

### ISSUE THREAD

**Issue by jpike88** [Provenance-Emu/Provenance#1974]
No matter what N64 ROM I try to load, it crashes.

 
### Expected: 

MupenGameCore functioning properly I guess

 
### Actual: 

I'm noticing that breakpoints on MupenGameCore.m don't kick in, they have dotted lines...

A crash occurs, see screenshot. Still trying to understanding it, it appears that maybe the core variable isn't properly defined, maybe the class is not actually getting compiled... or the loadFile method is perhaps missing? It's hard to know as it's such a generic error. 

<img width="1460" alt="Screen Shot 2022-10-02 at 23 10 08" src="https://user-images.githubusercontent.com/9585787/193464320-7bc6bb55-efeb-41d9-b158-7bc9c072ea8a.png">

 ### Reproduce:  

1. Commit dd08428df
2. Try to fire up a N64 game
3. Crash

#

#### APP VERSION
dd08428df

#### APP SOURCE
Offical source

#### INSTALLED BY 

Building

#### PLATFORM
tvOS

#### iOS/tvOS VERSION
16

**Comment by jpike88** [comment]
@JoeMatt hey mate I know you're busy, could you maybe just point me in the right direction and I'll have another crack at fixing it?

**Comment by JoeMatt** [comment]
fixed in 2b303fee622d1afbb8908cdbb03874d632e371e4
