### ISSUE TITLE
Neo Geo Support

### ISSUE THREAD

**Issue by dashby07** [Provenance-Emu/Provenance#199]
I love Provenance, and am thankful for the dedication the developers have in making it even better. Are there any plans to add Neo Geo support in the future?

**Comment by gingerbeardman** [comment]
It's based on https://github.com/OpenEmu/OpenEmu which does not support Neo Geo at this time.

**Comment by WLR86** [comment]
Actually the experimental version of OpenEmu supports MAME roms, and this includes Neo Geo games. I'm running Metal Slug in OpenEmu for instance. So I guess there would be a possibility to get it to work without too much effort

**Comment by gingerbeardman** [comment]
@WLR86 do you have a link to the experimental OpenEmu version? Thanks!

**Comment by WLR86** [comment]
@gingerbeardman Sure ! On the home page of OpenEmu, click the arrow next to the download button, this will make a list appear from which you can download the experimental version binary. You can also find instructions on how to compile the source with experimental features enabled here : https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide

**Comment by gingerbeardman** [comment]
@WLR86 oh, I have that already, I thought you meant an experimental version for tvOS

**Comment by asos-jamesaddyman** [comment]
Guys, I don't mean to be a grouch, but this isn't a discussion forum - I get notified for every comment posted on Issues.

**Comment by jasarien** [comment]
Guys, I don't mean to be a grouch, but this isn't a discussion forum - I get notified for every comment posted on Issues.

**Comment by ylluminate** [comment]
Is there work going on in this area?
