### ISSUE TITLE
Undefined symbol errors.

### ISSUE THREAD

**Issue by chrishawn** [Provenance-Emu/Provenance#1993]
I had an old source and Xcode build all working, but now I'm trying to do a new build fresh git pull from source with Xcode 14.1 and a paid apple account and i keep getting  these 3 errors:

- Undefined symbol: _$s10RealmSwift0A14CollectionImplPAAE12makeIteratorAA11RLMIteratorVy7ElementQzGyF
- Undefined symbol: _$s10RealmSwift4ListCyxGAA0A14CollectionImplAAMc
- Undefined symbol: _$s10RealmSwift7ResultsVyxGAA0A14CollectionImplAAMc

first glance is it looks like an issue with the pod dependencies, tried a build clean not sure where to look next
is this a pod versioning issue? or an Xcode 14.1 issue?

**Comment by jtnessler** [comment]
Are you attempting to build for install on a Gen-3 Apple TV?  I am getting the first and third error when attempting install.

**Comment by chrishawn** [comment]
nope an iPhone 14 Pro

**Comment by smorkin** [comment]
Exactly the same problem here, using Xcode 14.1 and Ventura 13.0, when trying to build Provenance-Release (target is an iPad).

**Comment by chrishawn** [comment]
i tried an iPhone X as well now. So the issue must be somewhere either with Xcode 14.1 or Ventura 13.0

**Comment by chrishawn** [comment]
i did `rm -rf ~/Library/Developer/Xcode/DerivedData/*` and then `Xcode>File>Packages>Reset Package Caches` and the build still fails

**Comment by jtnessler** [comment]
I tried that last night too. Same fail.

**Comment by JoeMatt** [comment]
No clue what's going on here, but sounds like a local/xcode issues.
I've been doing clean builds on different machines, with different macOS, XCode and CPU types so I don't think it's the repo.

**Comment by chrishawn** [comment]
And have you built it on Ventura?

**Comment by JoeMatt** [comment]
Yes, 13.1 and 12 on Intel.

**Comment by smorkin** [comment]
Interesting.  I’m building on an M2 (MacBook Air). Perhaps M1/M2 and Ventura is the issue.
