### ISSUE TITLE
PVSupport, Bliss core, 4DO core, not inheriting DEVELOPMENT_TEAM setting from Codesigning.xcconfig

### ISSUE THREAD

**Issue by jpike88** [Provenance-Emu/Provenance#2010]
all seem to have the S32Z3HMYVQ team in there

**Comment by JoeMatt** [comment]
Thanks. I can fix this, though it shouldn't make a difference. Frameworks are code signed at the app build stage using its sign settings. Those targets should be set to "don't codesign" if not already.
