### ISSUE TITLE
[PS1] - Disc swapping

### ISSUE THREAD

**Issue by jpike88** [Provenance-Emu/Provenance#2034]
Some PS1 games cover multiple discs. Mednafen has this function built in, just needs to be exposed through provenance

**Comment by JoeMatt** [comment]
We have it. It's in the pause menu. 
See multi cd Roms in the wiki. 
Mednafen detests the m3u so they can be added after the fact as long as they have the same name.m3u as the cd1. You also don't need the (cd1) at the end. 

Game (cd1).bin
Game (cd1).cue
Game.m3u

Etc.
