### ISSUE TITLE
Crashing when opening ps2 games on iPad Pro 2020

### ISSUE THREAD

**Issue by Alexck002** [Provenance-Emu/Provenance#2119]
I have installed the latest beta of Provenance 2.2.1 I’ve tested NSMB and it works properly but when trying a ps2 game the app just crashes

**Comment by JoeMatt** [comment]
it's still under development and requires JIT and other things still.

Closing until official release.

**Comment by Alexck002** [comment]
I know but my iPads jailbroken. And it works with PSP which requires JIT as well

**Comment by JoeMatt** [comment]
It's not done yet. No reason to make bug reports until it's published.
