### ISSUE TITLE
PAL Resident Evil 2 doesn't work

### ISSUE THREAD

**Issue by tycooko** [Provenance-Emu/Provenance#2124]
PAL Resident Evil 2 is either displayed as different games for each of the discs that complete the game in question (meaning it is displayed as two games both titled "Resident Evil 2" and, if you look into the games' info, it tells you one is disc 1 and the other is disc 2) or only disc 1 is shown (sometimes, it will tell you it's the .m3u file, but it actually only plays disc 1, with no "Swap discs" option visible in the game's menu).

I expect multi-disc games to be shown as one game with the number of discs appearing on top of the game's thumbnail in Provenance's main screen, and then when you boot said game, you have the "Swap discs" option available in the menu.

I'd say that, rather than repeating here the 50 attempts in different directions that I tried to make multi-disc games work, it would be more useful if anyone could upload the PAL version of Resident Evil 2 in Provenance, make it work properly, and tell me how they did it.
Because, for now, I've tried every tutorial I could find. I've inserted the game's files manually though the "Files" app of the iPhone; I've imported them directly inside Provenance; I put the two .bin files, the two .cue files and the .m3u file all together in one big .7z archive. I've put disc 1's .bin and .cue in one .7z archive, then disc 2's .bin and .cue in another .7z archive, then finally made a last .7z archive with these first two archives, plus the .m3u; I've named the m3u just like the game, then I've tried adding "(Disc 1)" because it's the first disc that the emulator would look for, then "Disc 2" not because of the actual second disc but because it's a "two-disc game", then I renamed the whole thing with "com.provenance.psx/" before the game's title for the .m3u file... Nothing works.

#### APP VERSION
I've tried both 2.1.1 and 2.2.0

#### APP SOURCE
This official Github.

#### INSTALLED BY 
Side-loading it with Altstore.

#### PLATFORM
iPhone 13 Pro

#### iOS/tvOS VERSION
16.2

**Comment by JoeMatt** [comment]
Can you just use the default bug template rather than this narrative story.

What's the expected behaviour?

What's not correct about it?

**Comment by tycooko** [comment]
> Can you just use the default bug template rather than this narrative story.
> 
> What's the expected behaviour?
> 
> What's not correct about it?

Thank you for this condescending reply after one year. Exquisite.

Don't worry: I've solved my issue by using Retroarch.

By the way: I know reading is hard, but my message was VISUALLY divided into three segments:
1) a short version of what's happening;
2) why is that a problem/what's the expected behavior;
3) the biggest segment that made you go "Oh no! Reading!" was details to give anyone who might have wanted to help more references and ground to do that.

Literally, the template is there. What gave you a headache was just a different format and order of the paragraphs.
Anyway, as said, I don't need help with this anymore. Thanks. Hugs.
