### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by smorkin** [Provenance-Emu/Provenance#2180]
Documentation of how to install by building on Wiki is wrong.

 
### Expected: 

Opening workspace in Xcode should result in no errors.

 
### Actual: 

Errors simply opening the project, without trying to build.

 ### Reproduce:  

1. Simply take a fresh Mac with a standard Xcode install, and open the workspace file after following the instructions.
2. All targets have issues with signing and capabilities.

# 
#### NOTES  

Not sure these are all the purely documentation errors since I had to change a lot to finally get Provenance to build, but some of the issues with documentation are, in the **Build Sources**, section **2**:

- No _PRODUCT_BUNDLE_PREFIX_ exists in the mentioned file, _CodeSigning.xcconfig_. Should be _ORG_IDENTIFIER_.
- All targets have a Team & Bundle identifier which is **Unknown S32Z3HMYVQ** when opening the workspace. This is picked up from the _Build.xcconfig_ file, but nothing in documentation mentions changing this. There is a mention in this file that _PRODUCT_BUNDLE_PREFIX_ etc should be picked up from _CodeSigning.xcconfig_ but this does not happen → you have to change those in this file as well
- It seems as the changes to _Build.xcconfig_ & _CodeSigning.xcconfig_ must be done before opening the workspace, rather than the order specified in documentation.
- Group / iCloud capabilities do not work when following instructions (I have a paid for developer account, but I had to remove those capabilities to be able to get forward, so don't know what the problem is).

#
<!--- ☑️ REQUIRED: Check the detail boxes after posting! -----------------------→

#### APP VERSION
<!-- 2.0.X -→

#### APP SOURCE

- Provenance-Emu GitHub  *&nbsp;(Official)*

#### INSTALLED BY 

[Building](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source) *from Source*

#### PLATFORM

iOS

#### iOS/tvOS VERSION

16.4

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by urherenow** [comment]
What are you talking about? It's all covered and explained.

https://wiki.provenance-emu.com/installation-and-usage/installing-provenance/building-from-source

**Comment by smorkin** [comment]
The documentation is definitely buggy as mentioned in this case (referenced identifier does not exist in the file referenced), but I just got pointed on Discord to the GitHub project hosting the Wiki so will continue this case over there where it belongs; closing this one here.
