### ISSUE TITLE
[Bug] PVO2EM audio.c build error: "Undeclared function ext_IRQ()."

### ISSUE THREAD

**Issue by urherenow** [Provenance-Emu/Provenance#2234]
When building Provenance-XL, it errors on PVO2EM audio.c. Undeclared function ext_IRQ(). ISO 99 and later do not support implicit...

 
### Expected: 

Build without errors

 
### Actual: 

XCODE halted building on this error.

 ### Reproduce:  

1. Clone repo
2. Setup code signing and remove necessary things like app groups
3. Choose Provenance-XL scheme
4.  Try to build

#### APP VERSION

Latest Git

#### APP SOURCE

Provenance-Emu GitHub 

#### INSTALLED BY 
Building

#### PLATFORM

iOS/iPAD
#### iOS/tvOS VERSION

16.6.1
-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://wiki.provenance-emu.com/installation-and-usage/installing-provenance)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by robkoehler45** [comment]
I also run into this trying to build to Apple TV/tvOS.  17.2, xCode 15.1

**Comment by JoeMatt** [comment]
Can you check on current develop branch.

CI and local builds are working for me on this at the moment.

**Comment by urherenow** [comment]
My apologies. I live on Japan time, so I only just now have time to try a fresh build. Deleted my derived data and making a fresh clone to give it a try. This might take a while...

**Comment by urherenow** [comment]
Sigh... didn't work, because it isn't merged into develop. Does [feature/XCode15BetaMiscFixes] have everything else that is currently merged to develop? Because I wouldn't want to do a checkout otherwise.
