### ISSUE TITLE
apple tv 4k sideload

### ISSUE THREAD

**Issue by ripjaw1219** [Provenance-Emu/Provenance#2326]
hello i was just wondering if it was possible to sideload provenance to the apple tv 4k (3rd gen) if it is possible how do you do it

**Comment by urherenow** [comment]
The same as sideloading ANYTHING. In other words, not a Provenance issue. Github is for collaboration and bug reporting, not a help forum. 

You can get help in discord.

**Comment by ripjaw1219** [comment]
> The same as sideloading ANYTHING. In other words, not a Provenance issue. Github is for collaboration and bug reporting, not a help forum. 
> 
> 
> 
> You can get help in discord.

never noticed there was a discord thanks
