### ISSUE TITLE
Fast forward broken for GBA

### ISSUE THREAD

**Issue by Rmilner22** [Provenance-Emu/Provenance#277]
Fast forward does not work at all with GBA, either fast forwards for several seconds before reverting to regular speed or doesn't fast forward at all and after several seconds, runs at half speed.

**Comment by jasarien** [comment]
Which device are you using? Fast forward is dependant on CPU performance and capability. Fast forward will work better on an iPhone 6S than it will on an iPhone 4

**Comment by Rmilner22** [comment]
5s, fast forward works flawlessly for GBC though. Thanks for the reply

**Comment by jasarien** [comment]
GBC is less intensive to emulate than GBA, it can run faster with the same limitations as GBA

**Comment by Rmilner22** [comment]
Is there any solution or is my phone simply incapable of running GBA games fast forwarded?

**Comment by jasarien** [comment]
There might be a better implementation that may allow GBA to fast forward without losing sync, but I fear it wouldn't do your battery any good.

**Comment by kyleseely** [comment]
I have the same problem and I'm running on an iPhone 6.

**Comment by meldridge** [comment]
Same problem here, iPhone 6.

**Comment by AlexanderGalen** [comment]
Same problem on an iPhone SE, which has very similar specs to the 6s. Also, some strange behavior I noticed is that if i toggle my sound from muted to unmuted or vice versa after the speed returned to normal, it speeds up again.

**Comment by Traviskn** [comment]
I've also run into this issue, tested on an iPhone SE as well as a 6.  The fast forward works briefly but soon reverts back to normal speed.  Interestingly I've noticed that each time I rotate my device, the speed goes up for a few seconds, then drops back down.

**Comment by sevdestruct** [comment]
I haven't found the fast forward feature useful until we can make it more accessible, it's 3 taps in.. it's generally best for slow dialogue and games without a run button... But until we can get #725 I would even consider disabling this feature and removing it from the action sheet(s), until we can improve not just the performance but the actual toggle accessibility. Thoughts?

**Comment by meldridge** [comment]
Fast forward is killer feature for Pokemon, to give one example. Given that this bug only occurs on GBA ROMs, removing it entirely due to poor UI design is a bit like curing dandruff via decapitation.

**Comment by sevdestruct** [comment]
Alright, granted didn't say i was DOING it, persay, but i do want to get this in here in a better way in 2.0/2.x release… My question about thoughts/feedback was regarding that improvement, not about removing the feature.

----
That said, can anyone confirmed experiencing this on a recent dev branch build?? 
----
Would help us find out if this is an active bug still. a lot of changes since even the last post before me…

**Comment by sevdestruct** [comment]
tested on both VisualBoyAdvance and mednafen cores on latest. this is a non-bug now.
