### ISSUE TITLE
MFI Controller doesn't load if game launched from 3D touch

### ISSUE THREAD

**Issue by MysticalOS** [Provenance-Emu/Provenance#334]
Noticed another MFI bug today. If you launch app via 3d touch to choose shortcut to a recent game, it launches right into game without MFI support. It appears the code to load MFI doesn't execute if you skip the game selection screen.

iOS 9.3.1
iphone 6S+
GameVice for iphone
Code: Latest

**Comment by jasarien** [comment]
I'm only able to reproduce this issue when launching a game from scratch using 3D touch shortcuts, as in, killing Provenance totally and then selecting a 3D touch shortcut. 

It definitely knows there is a controller connected as the on-screen controls are hidden. So, my thought is that this has something to do with the controller assignment settings - in that it might not be setting the controller as player one.

**Comment by leolobato** [comment]
Could you try to reproduce using [my branch](https://github.com/leolobato/Provenance)? I've improved the way the controllers are automatically assigned and may have fixed this issue as well.

**Comment by sevdestruct** [comment]
I just tested this against the newer Swift branches (develop/n64-Swift/PushPop/UIRedesign) and i cannot reproduce this. Can we call it closed?
