### ISSUE TITLE
Controller input locks after varying amounts of time

### ISSUE THREAD

**Issue by joshuafitforbattle** [Provenance-Emu/Provenance#461]
Hey, I adore the emulator and really appreciate all of the work that goes into it, but I've got a problem. 

I'm using a steel series nimbus controller, it'll be set to either player 1 or 2, and after a while of playing the last button I pressed will get locked in the game- for example, if I was holding down a button for rapid fire, it'll just keep doing that without me being able to press anything else, or I'll be holding right in a game, and the character will just keep going in that direction and the only way to stop it will be to disconnect the controller. 

I know it's not an issue with the controller, because I've been using it with gba4ios as well and haven't encountered this issue once. Any help would be greatly appreciated. Thank you for your time!

**Comment by joshuafitforbattle** [comment]
Sorry, correction, I'm using a steel series stratus

**Comment by joshuafitforbattle** [comment]
still experiencing an issue here.

**Comment by sevdestruct** [comment]
@joshuafitforbattle Can you confirm latest firmware on your controller and try against a current release or even better: recent dev branch build?
