### ISSUE TITLE
Add ROM to Home Screen (URL Scheme Support)

### ISSUE THREAD

**Issue by BeyatchKillah** [Provenance-Emu/Provenance#64]
Ticket todo:

- [ ] Add URL to app target
- [ ] Modify app delegate `open url` to parse URLs
- [ ] Add UI to 'Save to Homescreen' to quick open ROM by URL with Artwork as icon.

Docs:
[Adding custom URLs](https://developer.apple.com/documentation/uikit/core_app/communicating_with_other_apps_using_custom_urls)

--- Original Request ---
With URL scheme support (I believe that's the name) you could open the individual ROMs from the iOS homescreen. GBA4iOS supports them already so maybe it may work for Provenance as well?

**Comment by josejulio** [comment]
That shouldn't be to hard to implement, I may look onto this once i finish #39 .

**Comment by pmp174** [comment]
Any advancement in this?

**Comment by josejulio** [comment]
Sorry, haven't had time to look onto this :(.

**Comment by marcelvoss** [comment]
So, I made some progress and added support for launching games using the following format:

provenance://play?md5=xxxxxxxx

This way, any game in game libraries can be opened from anywhere on the platform. Nevertheless, you'll **have to know the MD5 hash for each game**. We could maybe add an option to copy the hashes from somewhere, although I'm not sure about the actual implementation. Any ideas/thoughts?

**Comment by josejulio** [comment]
Isn't there any 'id' or canonical name that we can use instead of the md5 ?

**Comment by marcelvoss** [comment]
Well, I was only worried about taking the individual ROM names since users can change them in app. I know that the MD5 hash isn't optimal but works well.

**Comment by josejulio** [comment]
All the hashes are already on OpenVGDB (Provenance already uses it) so anyone who has access to it would know it.

sqlite> select romID, romHashMD5, romFileName, romExtensionlessFileName from ROMS WHERE romID=17462;

romID | romHashMD5 | romFileName | romExtensionlessFileName
------- | ----------------- | ----------------- | ---------------------------------- 
17462 | C2C5A4B990CE72F98B7B7F236E66C022 | World of Illusion Starring Mickey Mouse and Donald Duck (USA, Korea).md | World of Illusion Starring Mickey Mouse and Donald Duck (USA, Korea)

**Comment by marcelvoss** [comment]
Alright, I'll add the ROM IDs as well. Makes sense.

**Comment by sevdestruct** [comment]
Any progress on this? Still interest? Cobwebs here.

**Comment by JoeMatt** [comment]
This is sort of supported since this is basically what the force touch launch or launch from spotlight does. Not sure what the purpose of expanding this feature is. Wouldn't take much though since the hooks that are needed are all there in the app delegate already.

**Comment by sevdestruct** [comment]
It's novel, I'll grant it that. OK, leaving it open for someone who _really really_ wants ROMs as app icons on Home Screen to jump on this one. Up for grabs, folks…

**Comment by JoeMatt** [comment]
It looks like there was code to handle opening URIs already, but the proper info.plist entries weren't there and the URL processing code I think was off. But it's a pretty simple add to support opening by MD5. 

I added code to support `provenance://open/md5=#####`

The hard part is how to add the bookmark. Basically what you have to do is,

-  spin up a local web server
- Create a page, probably using a template html file in the app with some string replacement code, to make a HTML page that has a link in it to add the bookmark. Preferably you use the artwork of the game to create a bookmark icon too and serve that inside the webpage also so the shortcut bookmark has the artwork you want, the proper game title to display on the homepage, and url to match the md5
- direct a WebView/Safari whatever to port/page to that page so the user can click the add bookmark link

Another way would be to use the provenance homepage to hose the site that generate the bookmarks, either way you have to bounce out to something in safari.

**Comment by sevdestruct** [comment]
…adding to this notes from @JoeMatt, regarding a quesiton I had:

**How difficult would it be to get our aspect fill game cover art into an iPhone icon frame and generate a proper app icon automatically for this?:**
>I guess not hard, you have to create a websnippets file, you embed the image as a string
basically you would create the html file, andn send it to a webserver to point Safari to it
like how we bounce a safari controller to the web importer, but basically you'd have a template html file in the app, and generate the URL and string encode image on the fly based on the rom selected, since icons are the same size on iOS, you know the aspect, you'd use core graphics to generate any image you want really.

**Comment by JoeMatt** [comment]
At the end of the day, this feature is kind of pointless. We have spotlight, we can make a today screen plugin, and even a Siri plugin, and they all will be up to date with live data. These book marks are difficult to create and will be out of sync with rom deletions and artwork updates. Not to mention the huge work and code bloat it would introduce.

**Comment by sevdestruct** [comment]
…hmm. Yeah, I agree the original requested feature itself was novelty at best, and a proper icon is also novelty.. I hadn't thought about the desync to meta in the app. I mean i guess you could recreate it if you ever change the name, or cover, and manually delete it after the fact…

…eh.

**Comment by applehawk** [comment]
How about URLScheme, it's still doesn't work ? This issues was created at 2015 =)

**Comment by sevdestruct** [comment]
let's just close this.
