### ISSUE TITLE
Support for supplemental rom files (.xml) via SNES9x

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#684]
So, granted this is an edge case for games like Tengai Makyou Zero (Far East of Eden Zero) on Super Famicom, there is only two emulators i know of that support this particular game, BSNES Compatible build, and SNES9x if you have an accompanying .xml file (named same as your ROM file and in the same directory) such as this one for the game mentioned above with the contents:

```
<?xml version='1.0' encoding='UTF-8'?>
<cartridge region="NTSC">
	<rom>
		<map mode='shadow' size='0x100000' address='00-0f:8000-ffff'/>
		<map mode='shadow' size='0x100000' address='80-bf:8000-ffff'/>
		<map mode='linear' size='0x100000' address='c0-cf:0000-ffff'/>
		<map mode='linear' offset='0x600000' address='40-4f:0000-ffff'/>
	</rom>
	<spc7110>
		<ram size='0x2000'>
			<map mode='linear' address='00:6000-7fff'/>
			<map mode='linear' address='30:6000-7fff'/>
		</ram>
		<mmio>
			<map address='00-3f:4800-483f'/>
			<map address='80-bf:4800-483f'/>
		</mmio>
		<mcu offset='0x100000'>
			<map address='d0-ff:0000-ffff' offset='0x100000' size='0x500000'/>
		</mcu>
		<dcu>
			<map address='50:0000-ffff'/>
		</dcu>
		<rtc>
			<map address='00-3f:4840-4842'/>
			<map address='80-bf:4840-4842'/>
		</rtc>
	</spc7110>
</cartridge>
```

Considering Provenance is using the SNES9x core, would support for loading in this file be feasible, for the games that require it?

**Comment by jasarien** [comment]
What’s it for?

**Comment by sevdestruct** [comment]
Compatibility? Without it that game will not play on SNES9x… I believe it's one of the reasons Richard Bannister separated the builds of BSNES as well, back when. Again, it's an edge case or cases, I believe there is only a few. Only asking since we are using a core from 1 of the only 2 emulators i know that can even play that particular ROM.

**Comment by sevdestruct** [comment]
This is no longer needed. Updated SNES9x core #734 is compatible!
