### ISSUE TITLE
Update Realm database

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#691]
### Systems ###
- [ ] `List<PVGame>`
- [x] BIOSes -> PVBIOS
- [x] Basic metadata (Name, short name, identifier, extensions, multi-disc capabable)
- [x] Extra Metadata
- - [x] Manufacturer 
- - [x] release year
- - [x] media type
- - [x] bits
- - [ ] box art aspect ratio

### Cores ###
- [x] `List<Systems>`
- [ ] Configuration options

### Save State ###
- [ ] Link to PVGame 
- [ ] Date
- [ ] Screen Shot image (save a screen shot on save and add to Image cache)

### Expand PVGame ###

- [x] Add a play counter
- [x] Add a total time in game counter
- [ ] Migrate existing PVGames to add PVSystem entry
- [ ] Add reverse relationship to system
- [ ] Add `List<PVSaveState>`
- [ ] Maybe: Tags
- [ ] Maybe: Add per game settings.

Adding System entries would allow a few things,

- Only need to update collection view section for that system
- Re-order the order the appear in browsers
- Can use Realm event listeners to be notified when a new system is added to List<PVGame> instead of doing a full datasource reload on every action that MAY have modified the contents.

**Comment by abesada** [comment]
Branch: Feature/n64+swift
Platform: appleTV simulator and device

The compilation is successful but crash when I execute the app:

Fatal error: Migration is required due to the following errors:
- Property 'PVGame.romSerial' has been added.: file .../Provenance/Provenance/Game Library/Database/RomDatabase.swift, line 139

**Comment by sevdestruct** [comment]
Other work to be done

- [ ] **Systems.plist additions**:
- - [ ] Manufacturer 
- - [ ] release year
- - [ ] media type
- - [ ] years in production
- - [ ] bits)

**Comment by GoldenChaos** [comment]
Building the develop branch is failing on Xcode 9.3 beta 4 right now because the Realm module needs to be compiled with Swift 4.1. Would updating Realm to work with Swift 4.1 fall under this issue? Do they even have a version compiled with Swift 4.1 yet?

**Comment by JoeMatt** [comment]
They have a new Beta but it doesn't seem to support 4.1 yet. They may be waiting for official release.

https://github.com/realm/realm-cocoa/releases

**Comment by JoeMatt** [comment]
done a while ago.
