### ISSUE TITLE
Time Interval/Recurring Auto-Saves with Backlog + "Limitless" Save States

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#717]
Thinking for an option to (on by default) for auto-saves on time interval, so recurring like every 5-10 minutes or so, with a backlog of like last 3 autosaves. Maybe make them non-user-writeable, so can't overwrite, and also expand UI to not have a limit of 5 save slots

- [x] Recurring/Timed Auto-Save States
- [x] Unlimited Manual Save Slots
----

This should cut down on user error with people using only save states as their only save(especially auto-save only - not smart), and not battery saves, especially on games that have a "Point of No Return" in where it loads, like some Pokémon game @jasarien mentioned, and otherwise just a handy feature I think is good anyway.…

----
…there is a plan for a new Load/Save View for 2.0 designs that i want to build this into, but that has it's own feature set (screenshots, etc) that i'll make in another ticket if there isn't one yet

**Comment by JoeMatt** [comment]
Added 5 min autosave
Added option to disable autosave (default on) `PVSettingsModel.shared.timedAutoSaves`
Added option to change time interval (default 5 min) `PVSettingsModel.shared.timedAutoSaveInterval`

**Comment by sevdestruct** [comment]
Thanks @JoeMatt 
https://github.com/Provenance-Emu/Provenance/commit/75ff6e45d881ccdfd70be8d7459d2eb5c09b38da I've added optional toggle, and a dependency on  and relation to auto save toggle = feature complete.
