### ISSUE TITLE
Vote/Suggest for Open Discussion Platform

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#733]
Disclaimer:
----
We get _way_ too many posts here that aren't issues and are just general discussions or issue comments that branch off unrelated all too often… Please refer to the new [Issues Usage](https://github.com/jasarien/Provenance/wiki/Issues-Usage) on our wiki.

----

That said, on to the real purpose of this post as I'm only going to do this open [but very focused] discussion once here in the Issues: an open vote (or suggest as comment) for a platform to use for open discussions, general questions, announcements and any other community engagement.

Vote/Suggest for Open-Discussion Community Platform:
----

 1. Please use **this thread's comments only for suggestions**, so we can keep this organized.
  _Add pros and cons and such but please keep it simple, edit your post if you need to come back with these instead of cluttering the ~~comments~~ suggestions._
 2. Please use _only_ the 👍 or 👎 emojis on the suggestions to vote.

_I'll kick this off with a couple…_

**Comment by sevdestruct** [comment]
Discord with public channel(s).

**Comment by sevdestruct** [comment]
Subreddit

**Comment by sevdestruct** [comment]
Stryde (Slack clone by Atlassian who bought Trello)
----

Need to check if we are able to make a public join link but there is some interesting features here to replace our Slack usage with that I've been looking into.

**Comment by sevdestruct** [comment]
Slack (Team Communication, of course…)
----
We all use it for work and such.. Just throwing this in there, just for comparison sake, since we are currently using (for just developer focused conversations) and since it shares similar feature sets with the majority, but it's not preferred as the cons will show… 

- **Pros**:
  - Familiar. We are already using this (for dev)…
  - A lot of cross platform plugins… (GitHub, Trello, tons more)
- **Cons**:
  - **Invite only!** this is a deal breaker in my opinion to get community engagement, even with a public channel. So this is a management pain.
  - Not free video chat / screen sharing, etc… (paid accounts only) (we jumped to Discord for this recently, kinda need this to make things easier on dev side.

**Comment by BaffleBlend** [comment]
Please let us know when a decision is made and give us a link to the chosen platform when the time comes. And maybe also on the main website.

(I personally voted for Discord.)

**Comment by sevdestruct** [comment]
Forum (Various) [Specific option (s): TBD]
----
Not sure about this, but I suppose it's an option…There are so many of these old bb types, but they just feel antiquated anymore… If there is interest I'll do some research against this, or am open to suggestions.
_will update later with some general pros/cons_

**Comment by sevdestruct** [comment]
Other Forums? (Various) [Specific option(s): TBD]
----
Not sure about this, but I suppose it's an option…There are so many of these old bb types like phPBB, [Vanilla](http://vanillaforums.com/en/), but they just feel antiquated anymore—even with modern ones like [Discourse](https://www.discourse.org), [Muut](https://muut.com) or lightweight discussion tools like [Disqus](https://disqus.com)—and most don't tend to have the ease of three modernized IRC revivals that Slsck seemed to popularize… If there is interest I'll do some more research against this topic, or am open to suggestions.

_(will update later with specific option or multiples, and some general pros/cons)_

**Comment by sevdestruct** [comment]
[Muut](https://muut.com) (Modern BB Forum+Chat?) 
----
…might pull muut out of the forum various above, seems similar to Discourse, but i think it may have more chat capability, but can't determine if there is a free option in there, they also are on GitHub as well.
