### ISSUE TITLE
Prep 1.5 release

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#757]
### BUG FIXES ###
- [x] First import for a system is blank
- [x] tvOS layout can't navigate special sections
- [x] NSLayoutConstraints Errors in console

### Coding ###
- [x] Fix crash when opening game from library search
- [x] Bump version number
- [ ] Test and fix importer oddities
- [ ] Write database migration function

### 1.4 Upgrade ###
- [ ] Messaging to indicate that DB is going to be dropped and rescanned
- [ ] After ROMs are re-imported, try to match up old save states to new
- [ ] Maybe back up artwork and reimport

Idea: Artwork and saves could be moved to a folder to match the MD5 of the rom, then drop the DB, and try to rematch by the MD5 again.

### QA ###
- [ ] Test save states migration
- [ ] Test database migration function
- [x] Test iOS 8

### Distribution ###
- [ ] Add continuous integration (Fastlane with Fabric, Hockey App, Test Flight?)

### Docs / Social Media Prep ###
- [ ] Update release diff log
- [ ] [Update docs](https://github.com/jasarien/Provenance/projects/7) - @sevdestruct
- [ ] Create announcement post for later publish
- [ ] Add twitter integration to wordpress for publish push
- [ ] Links on website to wiki
- [ ] Installation tutorial vids?
- [ ] Add a contributors page
- [ ] Verify 3rd party attributions are correct
- [ ] Create a press kit with updated screen shots, logos

**Comment by yashghelani** [comment]
Hey. I’d love to contribute to the website. I can design as well as code. Where do I begin?

**Comment by sevdestruct** [comment]
@yashghelani better to discuss this in discord.

**Comment by eduo** [comment]
I had seen the "rematch" option and thought it would be in 1.5 (then 2.0). 

Is there no possibility to tell the app to try and match a ROM again, if it fails the first time? Perhaps after renaming or specifying a search string?

**Comment by JoeMatt** [comment]
> I had seen the "rematch" option and thought it would be in 1.5 (then 2.0). 
> 
> 
> 
> Is there no possibility to tell the app to try and match a ROM again, if it fails the first time? Perhaps after renaming or specifying a search string?

Not one at a time, just the whole lib which is slow. 

Moving/copying it back into the imports dir (using webdav), would force a single rom reload though, without deleting saves.

**Comment by JoeMatt** [comment]
Closing since we did 2.0 already.
