### ISSUE TITLE
Delete game causes crash

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#759]
Delete game. Crash. Restart, but at least game is deleted.
(I know you are aware of this one, @JoeMatt - just logging it here to track

**Comment by jasarien** [comment]
I think this should be fixed in the save states branch. With the added extra checks we did, the game library has been working great for me. Deleting/adding for roms and save states.

**Comment by sevdestruct** [comment]
as far as i can tell, testing a bunch of systems (goodbye games) and save states, deleting is working.
