### ISSUE TITLE
Importer Glitches

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#761]
After a long series of documenting importer tests i have the following list of strange happenings:
#709 might solve some these, but I don't think that is the only problem.

- [ ] Conflict Manager crashes
- [ ] Conflict catcher triggering before archive extraction is complete
- [ ] Games not showing up in Library after extraction until relaunch (might be related to the above)
- [ ] .bins in wrong directory
- [ ] temporary ghost folders (witnessed via WebDav)
- [ ] WebDav out of sync with server or Web UI
- [ ] Wrong disc as imported as main or at least wrong name (Disc # still in game name)
- [ ] Cover art with extra `.` periods in name won't match and cause crashes (#760)
- [ ] Cover Art unmatched and leftover in Imports seems to be causing false unarchiver extractions or extraction alerts. (#760)

**Documentation of tests:**

1. Web UI: Uploaded some Sega CD ROMs, (.zip files) some or maybe all of them of them flagged a conflict, said ignore.
2. Web UI: Uploaded 2 multi-disc PSX games (.7z files) (both of which successfully imported previously sucessfully without step 1.
3. Stopped the web server right after uploaded completed.
4. Extraction begins, and shortly after, conflict catcher prompted, during the extraction, early on..

Not sure yet if it's the Sega CDs ROMs that were already flagged, or the extracting archive is having one of it's importing files flag before the whole archive is extracting… 

After extraction PSX game didn't show up in Game Library or Conflicts Views. That said this same game imported ok before, when nothing was in conflicts prior to it..

5. PSX game showed up in Library after putting Provenance through quit/launch cycle, so maybe existing files in conflicts are a problem. One game was titled …(Disc 2), again, though…

Checked the directories… All PSX games did end up in the right directory. All Sega CD games from previous import in step 1. ended up Conflicts directory, but haven't elected to resolve them yet. For some reason Provenance made an empty Genesis directory…

6. Deleted one of the two PSX games. Reuploaded same .7z file through Web UI, no conflict prompts, game showed up in PSX Library without restarting…

Checked directories via Web UI, one the last PSX game's .bin files ended up in Genesis. 

7. Uploading… new multi-disc ROM that (.7z file) hasn't been uploaded yet). Uploaded fine. shows up live in Game Library.

8. Upload another fresh Sega CD ROM (.zip) - flags a conflict, I dismiss, not resolve.

9. Upload another fresh PSX ROMs, single disc (.7z) - stop server after upload completes, it extracts, no interrupts—but it flags a conflict, go to resolve, tap on it this PSX game in the list—**crash**

10. Relaunch, the game that crashed on selection in Conflict Manager (though i hadn't resolved it) is now in PSX Library…

11. Return to conflict resolver to resolve the 3 Sega CD games still in there, tap on one, but this one shows the resolution options, tap on Sega CD—**crash**

12. Relaunch. Game from last crash shows up in Sega CD Library..

13. Rinse, Repeat. All the Sega CD games in conflict manager have same result…

14. Started server from Settings. Upload through Web UI yet another fresh multi-disc PSX game (3 discs) (.7z). Stopped web server directly after upload completed. Go back to Library, extraction is in progress. -- Phone goes to sleep, because it's taking a while… Wake it up - Finsihed unarchiving, shows up in PSX Library, no problem

Checked the directories via WebDav that I still had open during this, there is now an empty Game Gear directory in there… also still showing all of the Sega CD uploads from above in Conflicts. Ejected WebDav… Reconnect to WebDav, Game Gear directory is gone. Nothing in Conflicts…

- Tested on iOS, iPhone X, latest UIRedesign branch.

NOTE: No BIOS had been uploaded yet in the above scenario, library consisted of GBA, GBC, NES, SNES, NES, PSX before step 1.

**Comment by kaiser71** [comment]
How would I import my saves from laptop/computer on psx, it doesn’t have a memory card folder

**Comment by Cepheidsong** [comment]
After some testing today, I found out some things that I'm still seeing if it is 100% correct but so far:

if the segacd (I haven't tried psx yet) file name matches exactly the one in the openvgdb parser, it will not cause a conflict or crash the current test branch- it will just load up like any other rom.
The parser list is: https://github.com/OpenVGDB/Parser/blob/master/Parse/releases/source-scd.txt

There are lists for other systems.  The file name also has to have the region as (USA) or (Japan) in the file name at the end.  This also seems to be the case for a lot of other roms for any system.  (example: 8 Eyes.nes won't find cover art, but 8 Eyes (USA).nes will)

When the file names are off for the segaCD, it can still find the cover art if it can recognize it... but it usually causes a crash, but will have the art and everything fine when you reload Provenance.

Anyway just to say there is no crash or conflict when the file name perfectly matches the parser.  Just passing it on!  I'll test with some psx later.

**Comment by sevdestruct** [comment]
I'm closing this ticket.. too complex, running isolated test right now, trying to fix multi-disk and pce-cd importing - splicing out specific bugs as individual tickets now…
