### ISSUE TITLE
Changes to the screen resolution or multiple screen resolution

### ISSUE THREAD

**Issue by fdm96** [Provenance-Emu/Provenance#771]
App version: 1.5
iOS / TVOS Version: 11.3 Beta 4

Hello for the first time you have great since you have sent me back in my youth 👍 wanted to ask what I would like TVOS so my wish, it would be possible that you can enter the resolution itself such as 16:9 wide instead of only the 4:3??

Thanks for the great work ....

**Comment by JoeMatt** [comment]
Well there's two things there,

1. Some cores do have a wide screen option internal. We need to finish #680 do enable that
2. For square only cores we have a ticket for #639 

You can track those issues for updates. I'll close this as a dupe.
