### ISSUE TITLE
Save States (including auto-save) not working

### ISSUE THREAD

**Issue by MichaelMKenny** [Provenance-Emu/Provenance#774]
If I try saving state to a slot, in the 1.5 dev build, the state is not saved. The action menu dismisses as if it worked, but tapping "Load State" shows no saved state. 

And if I attempt to save state on the Nintendo 64 emulator the video hangs, but the audio continues in the background.

Happens on both my iPhone X and iPad Pro on iOS 11.

**Comment by jasarien** [comment]
Save states and autosave states should be working now in 6ac5eb0e7a1be7a0cd4eee4b9f30d0426848fc17
