### ISSUE TITLE
Availability of content without webadress

### ISSUE THREAD

**Issue by kelet91** [Provenance-Emu/Provenance#775]
Hello guys,

I really love your work! But I still have a request.

Could you please make the content also available from other locations in addition to the webadress in the Browser? For example the ability to place savegames in a dropbox or anything else.

I ask you this because if IOS failes to prove the app in settings, all roms and savegames can‘t be saved because you don‘t have the possibility to get inside the App.

**Comment by JoeMatt** [comment]
We already have this. 
WebDav server and UIDocumentPicker in the 1.5 / develop branch.

UIDocumentPicker allows you to connect with cloud services in the app if you have their app installed; ie DropBox, Google Drive, iCloud, Box, etc etc

**Comment by kelet91** [comment]
I’m very happy to hear this, thanks!
Could I ask you, when do you expect to release 1.5?

**Comment by jasarien** [comment]
We do not commit to specific release dates. We work on this in our spare time, so its difficult to schedule things. It'll get released when it's done.
