### ISSUE TITLE
Player3 and player4 + multi-tap issue!

### ISSUE THREAD

**Issue by Mr-se7enX** [Provenance-Emu/Provenance#776]
I just got the last version of Provenance. I confirm that multi-tap not working on psx and Snes cores. I tested controllers on PCE and N64. I found out that controller 3 controls player4 and controller 4 not working.

**Comment by JoeMatt** [comment]
I'm aware. 4 player is still under dev. It's a bug where it double selects the controller. You have to select and then unselect the duplicate entries and add the next controller, repeat. I'll fix this soon.

**Comment by JoeMatt** [comment]
This should have been fixed in 48c08d9

**Comment by JoeMatt** [comment]
Though note multi-tap is not supported at all on PSX, it's too broken for various reasons so I pulled it, this should be fixed in N64 though. SNES never had multi-tap support added in our code so that would be a separate feature request.
