### ISSUE TITLE
8Bitdo NES30  not working on provenance n64 ROMS

### ISSUE THREAD

**Issue by bri4289** [Provenance-Emu/Provenance#778]
I am new to this site and if I am not posting this in the correct area i apologize in advance! I am trying to figure out how to get my controller to work with n64 ROMS but I still cant get it to work. The controller works with SNES and gameboy ROMS.

**Comment by sevdestruct** [comment]
Merging this with larger icade rehaul ticket: #741 -- If you're new please read the wiki on Issues Usage. And welcome to Provenance.
