### ISSUE TITLE
Sound starts to drop some "frames" with tvOS 11.3

### ISSUE THREAD

**Issue by CooperRS** [Provenance-Emu/Provenance#779]
Starting with the tvOS 11.3, I experience issues with the sound breaking after some seconds playing a game. It sounds like the sound starts to drop some "frames". I experience the issue with a wide variety of games (N64 Games, SNES Games, see below for an incomplete list of games I experienced the issue with). Opening the menu (where one can save/load the state and return to the game library) and closing it without selecting any option solves the issue for the next 20 seconds (or so) before the issue comes back. In particular, I do not need to change the game speed to solve the issue.

I'm running the latest version of of tvOS (11.3 Final (15L5211b)) on a 4th gen Apple TV. On the Provenance side I'm running commit a5c67bfcab04a0a8ad75e170191feae49275a072.

Given that the issue does not affect one single emulated device but rather all as well as a wide variety of games, I'm assuming this is somehow related to tvOS or how the sound output is generated by Provenance.

Any ideas what I could try to fix the issue? Please let me know, if you need a sound sample or any logs.

#### N64

* Super Mario 64

#### Super Nintendo

* Super Mario All-Stars
* Super Mario Kart

#### GameBoy Advance

* Super Mario Advance 2

... and probably some more.

**Comment by jasarien** [comment]
Did you make sure to build the Release target and not the debug? The release target has optimisations enabled, while debug does not.

**Comment by CooperRS** [comment]
Yep, I chose `ProvenanceTV-Release`as target.

**Comment by CooperRS** [comment]
Ah, of course I restarted both the Apple TV and Provenance without any luck. Sry, I forgot to mention that above 🙂.

**Comment by CooperRS** [comment]
Here are some logs I receive when starting Provenance:

```
2018-03-30 22:11:16.247325+0200 Provenance[560:1372792] [DYMTLInitPlatform] platform initialization successful
2018-03-30 22:11:21.735749+0200 Provenance[560:1372615] ### Failed to Soft Link: /System/Library/PrivateFrameworks/CoreSuggestions.framework/CoreSuggestions (2)
2018-03-30 22:11:23.312176+0200 Provenance[560:1372615] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-03-30 22:11:23.313021+0200 Provenance[560:1372615] [MC] Reading from public effective user settings.
0 🔹 [Debug] PVDirectoryWatcher.swift:73 startMonitoring()
  ↪︎ Start Monitoring /var/mobile/Containers/Data/Application/9A8BC31C-0ABB-4F36-B5A5-059F99F0FB5E/Library/Caches/Imports

0 🔸 [Info] PVGameLibraryViewController.swift:1525 numberOfSections(in:)
  ↪︎ Sections : 3

0 🔹 [Debug] PVDirectoryWatcher.swift:73 startMonitoring()
  ↪︎ Start Monitoring /var/mobile/Containers/Data/Application/9A8BC31C-0ABB-4F36-B5A5-059F99F0FB5E/Library/Caches/Imports

0 🔸 [Info] PVGameLibraryViewController.swift:1525 numberOfSections(in:)
  ↪︎ Sections : 3

0 🔸 [Info] PVControllerManager.swift:139 handleControllerDidConnect
  ↪︎ Controller connected: Nimbus

0 🔸 [Info] PVControllerManager.swift:212 setController(_:toPlayer:)
  ↪︎ Controller [Nimbus] assigned to player 1

0 🔸 [Info] PVControllerManager.swift:212 setController(_:toPlayer:)
  ↪︎ Controller [Nimbus] assigned to player 1

0 🔸 [Info] PVControllerManager.swift:139 handleControllerDidConnect
  ↪︎ Controller connected: Remote

0 🔸 [Info] PVControllerManager.swift:212 setController(_:toPlayer:)
  ↪︎ Controller [Remote] assigned to player 2

0 🔸 [Info] PVControllerManager.swift:212 setController(_:toPlayer:)
  ↪︎ Controller [Remote] assigned to player 2

5 🔹 [Debug] PVCoreFactory.swift:31 createInstance(forSystem:)
  ↪︎ Created core : <<PVGBAEmulatorCore: 0x14bd96f30>>

2018-03-30 22:11:28.816716+0200 Provenance[560:1372615] 🔸 [Info] -[PVGBAEmulatorCore loadFileAtPath:error:]:151
  ↪︎ VBA: Battery loaded
2018-03-30 22:11:28.998023+0200 Provenance[560:1372615] multiplier: 1.0
2018-03-30 22:11:29.471454+0200 Provenance[560:1372615] ❗ [Error] -[OEGameAudio createGraph]:285
  ↪︎ couldn't set device properties
2018-03-30 22:11:29.630039+0200 Provenance[560:1372615] ❗ [Error] -[OEGameAudio createGraph]:285
  ↪︎ couldn't set device properties
6 🔸 [Info] PVGameLibraryViewController.swift:468 handleUpdate(forSection:deletions:insertions:modifications:needsInsert:needsDelete:)
  ↪︎ Section 0 updated with Insertions<0> Mods<1> Deletions<0>

6 🔸 [Info] PVGameLibraryViewController.swift:1525 numberOfSections(in:)
  ↪︎ Sections : 3
```

The only thing I can spot there is an error when setting audio device properties:

```
2018-03-30 22:11:29.471454+0200 Provenance[560:1372615] ❗ [Error] -[OEGameAudio createGraph]:285
  ↪︎ couldn't set device properties
```

**Comment by JoeMatt** [comment]
You got super unlucky and pulled between commits while i had a bug that was choosing the the wrong gles version. 

Pull and rebuild and keep an eye on the commits, i've been pushing all day, except volatility.

**Comment by CooperRS** [comment]
Hmm, I updated to commit 6ac5eb0e7a1be7a0cd4eee4b9f30d0426848fc17 but the updated GLES version does not fix the issue. Still having broken sound with the same "solution" as described above (open and closing menu).

Please note: To make sure that Xcode being attached while running Provenance is not the issue, I also started Provenance without it attached. I still get the broken sound. I'm still using the release build target.

**Comment by svanimpe** [comment]
I have exactly the same issue. I'm running 1.4 release (rev. bbbafbcd) on tvOS 11.3.

**Comment by jasarien** [comment]
Now I'm worried that 11.3 is having an impact -- I'm seeing the same thing on my AppleTV (4th Gen), with tvOS 11.3, this definitely used to be fine -- and if @svanimpe is seeing the same thing qwith 1.4 on 11.3, then I definitely suspect 11.3 broke something :(

I'm reopening this @JoeMatt as there definitely seems to be an issue -- I don't know what it is though. It doesn't seem to be affecting my iPhone or iPad both on 11.3 as well, just tvOS for some reason.

**Comment by jasarien** [comment]
@svanimpe @CooperRS Cooper Can you guys do me a favour?

Go into your Apple TV settings, go to Video and Audio, then to Resolution -- You might notice that the selected resolution is 50hz, as opposed to 60hz. Choose a new resolution with 60hz and I think it solves the issue! Can you try it and let me know please?

**Comment by braindx** [comment]
To add my experience:

I just gave Provenance a run on my Apple TV 4K on tvOS 11.3. I didn't have sound dropping but I had massive video judder for some reason. After force quitting Provenance, changing resolution from 4K to 1080p and then back to 4K, and running Provenance again the issue went away... Very strange.

**Comment by jasarien** [comment]
@braindx did you select a 60hz resolution when you changed from 1080 back to 4k again by any chance?

**Comment by braindx** [comment]
It was at 60Hz the entire time. I verified it had never been at 50 Hz or any other refresh rate.

**Comment by jasarien** [comment]
Switching to 60hz from 50hz has definitely solved it for me.

**Comment by braindx** [comment]
I should also add that the FPS counter in Provenance displayed a constant 60fps despite seeing the massive judder. It seems like the issue was entire on the Apple TV side of things as Provenance seemed to be doing everything correctly.

**Comment by CooperRS** [comment]
I can confirm, that switching to 60Hz solves the issue for me, too.

Thank you for the help! 😊

However, still seems quite strange that the Video output causes such an issue?

**Comment by jasarien** [comment]
It's the way the GL view syncs with the TV's refresh rate to reduce things like screen tear. The API allows us to specify a preferred frame rate for the GL view to render at, but apparently it's more of a suggestion 🙄

**Comment by clementbarry** [comment]
@jasarien switching to 60Hz "solves" the issue, but is arguably a lesser option in countries where live TV broadcasts at 25fps: while tearing is prevented in Provenance, live TV apps start stuttering when not at 50Hz (at least on ATV4 / tvOS 12). Could there be a software solution to run at 50Hz without tearing, better than this workaround of switching manually video settings back and forth between 50Hz to 60Hz?

**Comment by jasarien** [comment]
If you read above you’ll see we already tried this. The OpenGL API thats we use to render the emulation output has a `preferredFPS` property, which we always set to 60 FPS. However, tvOS ignores this and just uses the system setting. This is most likely a bug, however since Apple have deprecated OpenGL in iOS, tvOS and macOS, I have no reason to believe they’ll fix it.
