### ISSUE TITLE
Swift Complier Error when building for tvOS

### ISSUE THREAD

**Issue by tvosrepo** [Provenance-Emu/Provenance#781]
Ive followed all the steps from the wiki and I get this error when trying to complete the build  
```

Users/admin/Provenance/ProvenanceTV-Bridging-Header.h:13:9: error: 'Provenance/Version.h' file not found
#import "Provenance/Version.h"
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/admin/Library/Developer/Xcode/DerivedData/Provenance-eokggonprsmsdfabossvorhhsbgi/Build/Intermediates.noindex/PrecompiledHeaders/ProvenanceTV-Bridging-Header-swift_UJ5NLPKSYS9E-clang_1J3IP71SVW962.pch' for bridging header '/Users/admin/Provenance/ProvenanceTV-Bridging-Header.h'
```

**Comment by sevdestruct** [comment]
@tvosrepo can you jump on our Discord to discuss. i am pretty sure you can just try building again, that file gets generated.

**Comment by tvosrepo** [comment]
Yeah I can do that.  I just need a few minutes to boot up my VM again and make a Discord account. Ill test building again to make sure first.

**Comment by jasarien** [comment]
This should be fixed in the latest develop branch.
