### ISSUE TITLE
(Request)C64 and PSP, maybe PS2 and GC?

### ISSUE THREAD

**Issue by XTutorials** [Provenance-Emu/Provenance#787]
Hi. I love your emulator. But I miss my Commodore 64 and PSP games, can you add these emulators in the next updates of Provenance? And it would be pretty cool too if you could add PS2 emulation(since already there is one on iOS called "Play!") and GameCube too(I am pretty sure there is one for iOS aswell).
Sorry if this is bot much of a issue, but I don't know where to put is elsewhere.
Regards,

**Comment by sevdestruct** [comment]
Hey @XTutorials: Thank you please join us on the GitHub. These discussions are happening there and we have most of what you are requesting (that's a lot to make in a single request, btw) in existing PRs or project milestones here. We have to close these issues if you open them, which I'm going to do now, there are links posted on the site that lead to the GitHub, on the readme, the wiki, etc: [Provenance Discord](https://discordapp.com/channels/421819941835243520/421820192356696074)
