### ISSUE TITLE
ios 11 compatibility

### ISSUE THREAD

**Issue by MikeDCastillo** [Provenance-Emu/Provenance#788]
Not compatible with 11.3
<img width="420" alt="screen shot 2018-04-01 at 11 28 30 pm" src="https://user-images.githubusercontent.com/23977239/38184381-7c94208c-3604-11e8-9632-5f036ad6f682.png">

**Comment by l80n63** [comment]
Update your Xcode to the new one released a few days ago, however that new version of Xcode only works with machines running High Sierra so if you don't want High Sierra, you can not run it.

**Comment by jasarien** [comment]
If you installed 11.3 on a device then you need Xcode 9.3 to build to it.
