### ISSUE TITLE
Recent Build Errors (Mupen64 folder)

### ISSUE THREAD

**Issue by Cepheidsong** [Provenance-Emu/Provenance#790]
For the past few days, all the builds have had unbuildable errors in xcode due to many .h files missing in the PVMupen64Plus folder.  I've been solving this part by taking the PVMupen64Plus folder from an older build (the jaguar branch) and replacing the folder of the current builds, since it has all the files xcode requires, though on top of that, had to create Plugin folder in that folder, and make a copy of mupen64plus-video-gliden64 folder and put it into the Plugin folder.  Then it builds!

I didn't see anyone else mention issues with all the daily updates coming out so I wanted to see if it was an issue with the one up on github or just something weird with my own copy.

Successful build doing that with the file-moving on the current up to date Develop build (the SaveState one had a 126 denied permission error so I couldn't try that.)

**Comment by jasarien** [comment]
`Develop` branch is beginning to move to submodules for cores. You need to update the submodules before building.

When you clone, if you're using a graphical git client, like Tower or Github Desktop, then you need to tell it to initialise submodules when you clone.

If you're using the command line, you have to run `git submodule update --init` from within the Provenance directory.

This is all details in the build instructions here: https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance#clone
