### ISSUE TITLE
Controls overlapping on iPhone SE

### ISSUE THREAD

**Issue by Corey-Evans** [Provenance-Emu/Provenance#799]
Hi there,
Love your work. Such a polished set of cores.

One issue. On slim devices, in my case the SE, the controls overlap in portrait. Eg. https://imgur.com/a/QiPD8

Thanks heaps!

**Comment by jasarien** [comment]
I’d suggest a simple fix of not playing in portrait? 🤷‍♂️

**Comment by sevdestruct** [comment]
@Corey-Evans : unfortunately, this won't be fixed until we have a more dynamic controller overlays, and more constraints, but SE is becoming more of an edge case with the app considering the current models, so it's a fairly low priority, I'm going to fold this into the #718 ticket as that will be overhauling the overlay controls anyhow.
