### ISSUE TITLE
Help with the multi discs

### ISSUE THREAD

**Issue by Cloutdaddyy** [Provenance-Emu/Provenance#800]
The past 16 hours I’ve been trying to figure out how to play metal gear solid but I always get this message saying I need to make a “.m3u” file so I read the info on how to do it but it’s really confusing me I typed in both of the “.cue” files for both discs then installed the “.cue” files then the “.bin” files then the “.m3u” file and once I press it it says to check on the files to see if it’s not corrupted can someone send me another link or video on how to do it because all the videos I’ve been looking at are just showing how to do it on open emu. I have provenance 1.5 beta

**Comment by jasarien** [comment]
You said you uploaded “the cue files, **then** the bin files, **then** the m3u”. Are you saying you uploaded them separately? Did you not read the instructions where it says all multi-disc ROMs must be uploaded as a single Zip file?

**Comment by sevdestruct** [comment]
Firstly, make sure you are using the 1.5 beta (multi-disc works better in the latest version), follow the Install wiki for this (we do not support 3rd-party builds of our app, so only use this method).

Installing:
https://github.com/jasarien/Provenance/wiki/Installing-Provenance

To Import ROMs, follow these instructions, please read it, there is multiple options and specific requirements for multi-file rom and multi-disc games/

Importing ROMs:
https://github.com/jasarien/Provenance/wiki/Importing-ROMs

**Comment by Jzephh** [comment]
I feel that this is still not clear. I have been over your instructions multiple times and still cant manage to get it to work. Can you not provide a step by step guide to the people who are using this app wanting to play multi disc games? I know that the wiki is there but for some people it is not clear...

**Comment by sevdestruct** [comment]
The guide you speak of is already in the wiki. Check Importing ROMs wiki, read all the sections, including the multi-file ROMs section, not just the multi-disc ROMs. And make sure you are Importing correctly with the other topics in that wiki.

**Comment by Jzephh** [comment]
Thank you very much. You allowed me to see where I was going wrong, You guys that make these emulators are absolute geniuses, keep it up.


________________________________

**Comment by confusedguynumber6** [comment]
I am still confused on the process of importing multi discs to provenance on an ios device.
Could you elaborate on a step-by-step tutorial or a video?

**Comment by confusedguynumber6** [comment]
yes

**Comment by naannekh** [comment]
Still domt get it. Im using ipad. And its hard to make m3u file without computer. Can anyone help?

**Comment by Jzephh** [comment]
You have to use computer to do it I think not possible without

Sent from my iPhone

On 15 Jan 2019, at 7:07 pm, naannekh <notifications@github.com<mailto:notifications@github.com>> wrote:


Still domt get it. Im using ipad. And its hard to make m3u file without computer. Can anyone help?

**Comment by sevdestruct** [comment]
Take these questions to our Discord [help channel](https://discord.gg/3ka2E6). Thanks.
