### ISSUE TITLE
Limit number of AutoSaves

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#805]
AutoSaves are taking over the new Save States Menu, and Search Results. We should limit the number of AutoSaves to like 3.. or 5, tops..

**Comment by sevdestruct** [comment]
@yoshisuga, would you like to take this one on next?

**Comment by yoshisuga** [comment]
Sure!

**Comment by sevdestruct** [comment]
Notes from Discord discussion:

> Let's go with 2, or maybe 4, maximum for the 1.5 version, since it's a w column grid view, so it feels complete without a grid space missing when maxed out.
> 
> We may revise this for 2.0, when the UI is updated.

**Comment by sevdestruct** [comment]
Confirmed. Now limited to 5.
