### ISSUE TITLE
Getting Build Errors

### ISSUE THREAD

**Issue by dallasgroot** [Provenance-Emu/Provenance#807]
Hey there, I am getting this build error with the latest build
<img width="1376" alt="screen shot 2018-04-08 at 9 06 34 pm" src="https://user-images.githubusercontent.com/7484579/38478932-e3bde2fe-3b70-11e8-9559-18f0df38f1d1.png">

**Comment by JoeMatt** [comment]
Read the installation page on the wiki. Need to use 'git checkout' not the zip, and do 'git submodule init'. It's all in the wiki.

**Comment by dallasgroot** [comment]
<img width="1440" alt="screen shot 2018-04-08 at 10 25 09 pm" src="https://user-images.githubusercontent.com/7484579/38480670-bd448442-3b7b-11e8-8124-5227306141ed.png">
and this is what I'm getting by doing that

**Comment by sevdestruct** [comment]
This thread is closed.

You're not following the Install wiki, follow each step to the letter. You are skipping the submodule step in Get Source > Terminal via `git`

#

If you have trouble join us on our [Discord](https://discord.gg/4TK7PU5)
