### ISSUE TITLE
'ProSystem/ProSystemGameCore.h' file not found

### ISSUE THREAD

**Issue by sumingliang** [Provenance-Emu/Provenance#811]

**Comment by jasarien** [comment]
Please follow the build instructions in the wiki. https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance

Errors like this are clear demonstration that you have not read or followed the instructions correctly.

**Comment by sevdestruct** [comment]
For future reference. please refer to our [Issues Usage](https://github.com/Provenance-Emu/Provenance/wiki/Issues-Usage) wiki:
https://github.com/Provenance-Emu/Provenance/wiki/Issues-Usage

For how to use and not to use the Issues board here.
