### ISSUE TITLE
N64 games will extract but not show up in Provenance

### ISSUE THREAD

**Issue by M1staAwesome** [Provenance-Emu/Provenance#814]
Tested on an iPhone 8 Plus, running iOS 11.2.6. Downloading roms on mobile then opening them through Provenance just extracts them, and nothing else. Other games seem to work okay.

**Comment by M1staAwesome** [comment]
Also forgot to mention, am on version 1.4 of Provenance.

**Comment by jasarien** [comment]
Version 1.4 does not have N64 support.
