### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by jajajaime** [Provenance-Emu/Provenance#817]
I am having this issues when trying to build for appletv 4k. It gets to the linking stage, and then this happens.
It is related to PVMednafen tvOS
My appletv has tvOS 11.3.
```
Undefined symbols for architecture arm64:
  "_EmulatedSNES", referenced from:
      MDFNI_InitializeModules()::InternalSystems in PVMednafen_lto.o
  "_EmulatedSNES_Faust", referenced from:
      MDFNI_InitializeModules()::InternalSystems in PVMednafen_lto.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas?

**Comment by jasarien** [comment]
@JoeMatt was anything missed tvOS when updating mednafen? It does look like the same error that is failing builds on travis, something to look into.

**Comment by frozen1988** [comment]
Hello,
I get this build error too. :(

**Comment by jajajaime** [comment]
Build succeeded with the latest changes from this morning.
Thanks, guys!
