### ISSUE TITLE
Psx digital/analog virtual gamepad issue

### ISSUE THREAD

**Issue by Fabiusco** [Provenance-Emu/Provenance#819]
Hi, I'm trying to play Parasite Eve on Provenance on iOS, but the controls doesn't work as they should.
The problem is that this particular game switchs controls betwheen analog and digital depending on the gamepad you are using.
I believe Provenance emulates a dualshock, but the vitual gamepad on screen shows the digital directional buttons only, and as they are turned off by the game itself, they cannot be used.
Every other button seems to to work just fine.
There's a workaround to this issue?

**Comment by JoeMatt** [comment]
duplicate #706 #690 depends on #735
