### ISSUE TITLE
PSP Core: PPSSPP

### ISSUE THREAD

**Issue by dantheman213** [Provenance-Emu/Provenance#82]
PPSSPP is multi-platform and has a build configuration for iOS and works great as an emulator. It should be taken into consideration for integration into Provenance. PPSSPP is located here:

https://github.com/hrydgard/ppsspp

Potential challenges are:
- Large complex codebase by itself
- Many libraries and dependancies

**Comment by jasarien** [comment]
It's a possibility for the future, but right now it's not on my short term radar.

**Comment by gingerbeardman** [comment]
It's based on https://github.com/OpenEmu/OpenEmu which does support PSP, so it should be possible.

**Comment by pmp174** [comment]
https://github.com/hrydgard/ppsspp 

https://github.com/OpenEmu/PPSSPP-Core

**Comment by sevdestruct** [comment]
No one has talked about this in a while… Seems [Retroarch](https://github.com/libretro/RetroArch) has functional core integrated. @JoeMatt, @braindx (I know you're looking at N64 integration and other cores with braindx' upgrades to the renderer, any interest here?)

**Comment by JoeMatt** [comment]
I got a build of PPSSPP running a couple months ago when they released an update to their non-JIT code for ARM. The concern was, without jailbreak, would it be fast enough without JIT features. It appears it is at least for my iPhone 7 and I'd assume both gens of ATV 4 could run it as well then. I tried to get a build going the other day. It's not as simple as copying and tweaking OpenEMU's repo though.  I have to look at PPSSPP make file for iOS and go through and add all those files to the build targets. PPSSPP is a combination of around a dozen libraries, it's going to be a time consuming process and I'm juggling  way too much on my plate. I doubt I even look at it again until the Spring.

I got further with Yaubase for Sega Saturn where it builds up until a final stage that hangs XCode, so I'll probably work on that first as far as new cores go. With the growing number of cores, some UI and ROM management features are also in desperate need of attention. Feature requests are far outpacing outside development, such is open source I suppose.

**Comment by JoeMatt** [comment]
I just checked out the latest PPSSPP official branch. It has a CMAKE file that generates an Xcode project file so it's about as simple as can be to get this integrated. This is probably a good candidate for the first core to use a git submodule checkout. I'll use their project as a sub-project and link their targets into a PVPPSSPP.framework target and then just mimic what OpenEMU already wrote to pass the ISO path and start the emulation, handle input controls etc. Organising it that way will make it easy to pull upstream change, generate a new Xcode sub-project, build, test and then commit the updated git commit hash to the submodule configuration.

The only downside to using submodules is it makes an extra step in the download and install process to checkout submodules. I really wish git command line would recognise there are submodules and prompt to init them on a first checkout of the container repo.

PPSSPP's performance is astoundingly good. I have no idea what kind of magic they're working, but I was playing Virtua Fighter 5 at full 60fps, not a single audio stutter or frame drop, with antialiasing, a multi pass shader and texture upscaling. Pretty incredible. And the controls map so well to MFi gamepads, this seems like a no brainer to do next. I was messing around with rei-cast for Dreamcast, performance is horrendous if with a bunch of custom hacks I made to even get it to run on a 64bit arch, and Yaubase is giving me issues, so PSP is next!

**Comment by sevdestruct** [comment]
👍 excited for this.

**Comment by mrjschulte** [comment]
( Wanted to see about where this was and if it's a decent sized(read simple enough)endeavor for me to look into for adding a new Core to Pv. )

**Comment by mkozjak** [comment]
Any news on this implementation? So much good work on this project so far!
