### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by Jamse22** [Provenance-Emu/Provenance#820]
Edit:

## Panasonic 3DO Support.

- [ ] Core integration: [4D0](https://github.com/libretro/4do-libretro) via libretro

#

Original:
> will support 3do games provenance 1.5

**Comment by jasarien** [comment]
Assume you mean 3DS, then no.

**Comment by sevdestruct** [comment]
i think they mean Panasonic 3DO, @jasarien

**Comment by Jamse22** [comment]
Yes, I meant panasonic 3DO

**Comment by jasarien** [comment]
Huh, ok. Well still no I think?

**Comment by sevdestruct** [comment]
is there an existing core or source emulator for 3DO?

**Comment by JoeMatt** [comment]
https://github.com/libretro/4do-libretro
