### ISSUE TITLE
WebDav Server Always-On broken

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#822]
WebDav works, but Always-On feature does not.
@JoeMatt mentioned it might be bug related to WiFi usage specifically.

**Comment by JoeMatt** [comment]
I can't reproduce. Works fine here on sim and device from live setting change and cold start. It shouldn't be wifi related since wifi isn't checked to start webdav from always on option.

**Comment by wattseat** [comment]
I am getting this on 2.0.2 sideloaded. It was working in the beginning but then stopped working.
