### ISSUE TITLE
3D Touch/Long Press doesn't Delete

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#828]
3D Touch / Long Press not deleting object.
*Update* Re-opened for Recent Save regression

### Expected:  
Deletes.

### Actual:  

Games:
- [x] 3D Touch to Delete
- [x] Long Press to Delete

Recent Games:
- [x] 3D Touch to Delete 
- [x] Long Press to Delete

Recent Saves
- [ ] 3D Touch to Delete
- [ ] Long Press to Delete

Save States
- [x] Long Press to Delete
- ~~3D Touch to Delete~~ (N/A)

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
**Update** Re-opening for Recent Saves regression

**Comment by JoeMatt** [comment]
The save states are deleting, the UI just isn't updating live
