### ISSUE TITLE
Conflict Manager 'ghosts' (left-behind [duplicate] files)

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#833]
Conflict Manager gets stuck or leaves a ghost table cell.

**Expected:**
ROM gets sorted and pushed to system.

**Actual:**
ROM is sorted, but leaves behind a ghost table cell in Conflicts, due to leftover duplicate file from move/copy function.

**Reproduce:**
1. Upload to CD-based games (in my test was 2 PCFX [2x] multi-file ROMs).
2. Stop server once uploaded…Unarchiving has begun…
2. First one unarchives, flags conflict catcher while unarchiver is processing 2nd one. Hit yes.
3. Resolved to system and return to Game Library
4. 2nd game still unarchiving… Completes, flags conflict, hit yes.
5. Try to resolve, and it sticks… or view doesn't update—seems game is in correct library [need to confirm that every time, as first test it wasn't but I may have selected TG16CD by accident that time]

Relaunching, and trying to resolve conflict made it go away, but another time it has stuck there indefinitely. A ghost. On further inspection, there is a duplicate .cue left behind in conflicts so it's a very similar if not same issue as what is causing #832, race condition?

**Comment by sevdestruct** [comment]
i haven't been able to reproduce this since some of the recent commits, but that doesn't mean it's gone just yet. Keep an eye out…

**Comment by falcocerr** [comment]
Hi, I’m having same issue and can’t find the answer
