### ISSUE TITLE
PCFX won't load [many] games

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#834]
~~Until I get a single report from a user that they could play a PCFX game on Provenance (v1.5), I am logging PCFX support as broken.~~

Update, one user has reported 1 game playable. that's 1 out of like 7 now… so uh… Stay tuned?

**Expected:**
- Game loads up. Play

**Actual:**
- Black screen. mednafen corrupt ROM (3:4 ROMs)
- BIOS screen only, music player, etc…no game, can't launch.
  - (Also, Ii suspect button mapping is totally wrong based on interaction with BIOS)
  - waiting for confirmation from other users if audio in music player is even from the game tried.

**Tested:**
4 ROMs in total, all in 2x multi-file format(s): `.cue + .bin`.  Will update

**Notes:**
It has been suggested that switching the rendering mode from PCE_FAST to NORMAL might fix this?

**Questions:**

1. Was this working on v1.4?
2. How about v1.5 pre-mednafen updates?

**Comment by JoeMatt** [comment]
Working for me...
![simulator screen shot - iphone x - 2018-04-16 at 11 49 36](https://user-images.githubusercontent.com/399864/38820590-4eb56f68-416c-11e8-9ad2-28bb66c9f017.png)

**Comment by sevdestruct** [comment]
@JoeMatt what file formats was that in: `.cue + .bin`?

**Comment by JoeMatt** [comment]
Well we can default back to non fast. I don’t think per core settings is going to make it to 1.5. Too much work and we’re really delayed. So try resetting back, it’s just and ifdef at the top of mednafengamecore.m, and when we add per core options this can be an issue again

**Comment by JoeMatt** [comment]
PCFX loads to bios but then does load the game a few seconds later. Check you have a valid bios maybe? Tested a few games all working. 'Super Power League FX' 'Comic Road' 'Battle Heat'.I had one game that wouldn't load but I think cause it imported wrong. I'm gonna bump this at least out of 1.5 blocker since I got a number of PCFX games to run no issue.

**Comment by sevdestruct** [comment]
think i may just of had a slew of bad roms maybe… and controller mapping (now fixed, i just pushed it) wasn't helping sort that out, seems everything launches to BIOS and will autolaunch if you don't move the cursor.. so gonna call this closed now
