### ISSUE TITLE
R button on controller doesn't send input to N64

### ISSUE THREAD

**Issue by boogaloo9** [Provenance-Emu/Provenance#855]
N64 R button not working on steel series controller. There is no R button mapped for N64

### Expected:  
Press R1 on steel series and R button would be pressed on n64 emulator

### Actual:  
Nothing

### Reproduce:  
1. As above
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Offiical Discord](https://discord.gg/4TK7PU5) </sup><br

**Comment by sevdestruct** [comment]
I forgot N64 even had shoulder buttons. Godd catch. But we do have touch overlay controls—wonder why MFi controllers aren't registering R..  —what about L? anything?

**Comment by boogaloo9** [comment]
Don't know about L. Most games don't use L. But almost all use R

**Comment by sevdestruct** [comment]
well, @boogaloo9…could you go check since this is your ticket and make it complete?

**Comment by boogaloo9** [comment]
Sorry for the late reply. Yeah, I don't think L is working either. Again, it doesn't really matter as most games don't use L.

Great app by the way. Thank you for all you do.

**Comment by sevdestruct** [comment]
You're welcome, we appreciate the gratitude
…but if you aren't going to finish your report, why reply at all? You opened the ticket. We are also busy people. Don't just dump incomplete issues on the boards and then not even followup on your own report when we ask, or it gets closed and wastes everybody's time.
