### ISSUE TITLE
Mednafen: PSX Player 2 MFi Controller not working

### ISSUE THREAD

**Issue by ssh88** [Provenance-Emu/Provenance#856]
When playing playstation games with 2 SteelSeries Nimbus's connected to my iPhone, only player 1 is recognised.

Provenance itself definitely recognises both controllers as games in Nintendo 64 & SNES work with 2 player.

Ive tried searching the forms for anyone else with this issue but cant seems to find any threads on this. Any ideas?

**Comment by JoeMatt** [comment]
Deleting because not in proper ticket format. Also, 1.5 is work in progress, we know there are issues in PSX.

**Comment by sevdestruct** [comment]
@ssh88 please use our Discord server

**Comment by jasarien** [comment]
@sevdestruct @JoeMatt  This is shabs, he’s already in the Discord and discussed this bug with me. I think this is a legit bug and should re reopened.

**Comment by jasarien** [comment]
@ssh88 Please reformat the initial issue to follow the template (you can see/copy the template if you go to create a new issue).

**Comment by ssh88** [comment]
Sorry guys, I raised this and deleted the initial format by mistake. Then ended up going to discord to discuss and forgot to update with the right format.

My bad! 

@JoeMatt thanks for the fix! I was looking completely in the wrong place
