### ISSUE TITLE
excuse me for a duplicate but I think it should be compatible with all devices

### ISSUE THREAD

**Issue by Alex2029** [Provenance-Emu/Provenance#862]
I mean psx n64 pc engine, they all work poorly on 32 bit devices it would be cool to make a full compatibility with all devices and 32 and 64 all to work equally simply for me Iphone 5c I think not everyone wants to update their device

**Comment by jasarien** [comment]
I’m sorry but we can’t support older evicted indefinitely. Apple removes support for older devices and we keep up with Apple. If we don’t then we can use the latest features and our code becomes old and unmaintainable.

**Comment by Alex2029** [comment]
Iphone 5c think it's old with me?

**Comment by jasarien** [comment]
iPhone 5C is an old device.
