### ISSUE TITLE
I do not want to make a duplicate but I need help I can not play SEGA 32X black screen on any games my Iphone 5c I'm gonna out of safari and I'll open up in Provenance

### ISSUE THREAD

**Issue by Alex2029** [Provenance-Emu/Provenance#863]

**Comment by Alex2029** [comment]
I took a screenshot

**Comment by jasarien** [comment]
Stop. Creating. Issues.

Take your questions to Discord. The links are on the main github page and in the wiki. You havew been told twice and already had one account blocked. 

Stop. Creating. Issues.
