### ISSUE TITLE
Importer: Search by name / hash before matching by extension

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#867]
Presently the importer tries to find any possible systems by extension, then does the SQL query for roms in the systems that could could match.

With the genesis extension change for instance, we could still match .bin's that are imported that users didn't rename if the md5 or filename matches the DB.

### Expected:  
Extensions should be a fallback for matching roms

### Actual:  
Match
1. name
2. MD5
3. TODO: CD Serial / Header
4. extension

### Reproduce:  
Import a rom

# 
#### NOTES  
Should add a list of ignored files extensions so we don't try to match known non-rom files
`jpg, jpeg,bmp,gif,txt,nfo,nzb,rtf,url`

**Comment by sevdestruct** [comment]
seems like an oversight on our part. great idea. had a question though:

@JoeMatt - if we do name before md5, don't we have possibility of getting a game in wrong system if it matches at that step?

…unless the intention that it will scrape as much info in that order of priority to match — more of a cross ref for anything it can determine in each category:
**example:** let's say a name is matched, let's say Breath of Fire II (USA), and it matches to both GBA and SNES for intance, so then it moves on to MD5 and says ok, this MD5 hash seems to be GBA, finds nothing in step 3, and step 4 confirms .gba extenison, s 2 out of the 4 were GBA only. 1 of the 4 was 50/50 GBA/SNES

**Comment by sevdestruct** [comment]
I had another idea that I think we should consider adding this I think might help with the system sorting, as a failsafe for unmatched ROMs:

Support for system encoded rom filenames using our sys ext described in Systems.plist:

```
[game].[sysext].[ext]
```
```
Diablo.psx.cue + Diablo.psx.bin
```

…essentially this would force it to go to the right system folder even when all else fails to match, at least you get an unmatched ROM in the correct system game library. Thoughts?

**Comment by JoeMatt** [comment]
I would say just do md5, or CD header/serial when that gets added, then do system(s) by extension + name as-is now.
