### ISSUE TITLE
Mednafen Graphical issues

### ISSUE THREAD

**Issue by jsex** [Provenance-Emu/Provenance#875]
### Expected:  
For game to load with no graphic issues

### Actual:  
Not rendering correctly -> games are glitching out graphically making them ***unplayable***

### Mednafen Cores Affected:
- [ ] NES
- [x] SNES 
- [ ] Game Boy
- [ ] Game Boy Color
- [ ] GBA

### Reproduce:  
1. Launch SNES game
2. Select mednafen
3. Let it play past opening titles (they might be okay, but it's a false positive), glitches after…

# 
#### NOTES  
…so far only **ALL** SNES games are the one with the issue the others Mednafen graphically work fine besides the exception of gba Pokemon games stay white on white screen but Mednafen gba games work otherwise without any graphic issues 

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
This is definitely not a blocker for 1.5 since I could just remove SNES from Mednafen ,it's not necessary.

**Comment by JoeMatt** [comment]
I turned off speculative rendering. I've tested a bunch of roms and the rendering is fine, a few hack roms don't work.

Mednafen SNES is meant as a higher performance alternative, it has speed hacks. If it doesn't render, don't use it. Bugs solved.
