### ISSUE TITLE
Provenance 1.4 and 1.5 beta crashing when I press start during a game

### ISSUE THREAD

**Issue by ali998x** [Provenance-Emu/Provenance#879]
This is my first time using GitHub I am not sure how to follow the whole format 

Expected: a menu to pop so so I could save a state  

 Actual: the whole app crashed 

Reproduce: I have no idea what to do. You guys may know better. I am totally new to this

Notes: checked the versions 1.5 beta 1.4 and 1.3.  Same problem.  I installed ipa,s form the GitHub page 
Initially totally roms wouldn't load even when I would import them form the safari (ie select the open with provenence option).  They just wouldn't be there.  Then I opened Provence in filza file explorer (I am jailbroken btw running iOS 8.3) there I saw the roms were actually stored in a folder named folder. So I moved the rooms form there to the roms folder and so the roms loaded perfectly. I could play them but then when I would press start they would crash.

 APP VERSION
- [✔️ ] 1.5 *beta*
- [ ✔️] 1.4

#### APP SOURCE
- [✔️ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [✔️ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ✔️] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ✔️] 8.x

**Comment by JoeMatt** [comment]
How did you test 1.5?

**Comment by ali998x** [comment]
I forgot to mention I got the 1.5 from iemulators (the one with the black screen).  On that I tried to move the roms to the rom folder but nothing happened.    As for 1.4 I got it form here.  The roms loaded but the crash was the only problem

**Comment by sevdestruct** [comment]
so you didnt report your app source accurately, and we don't support 3rd party nor jailbroken devices, as that is not necessary all this is working on our end and with our users, i suggest you ask for help in our discord #help channel.
