### ISSUE TITLE
IOS 11 - Provenance 1.5 PSX?

### ISSUE THREAD

**Issue by Seta193** [Provenance-Emu/Provenance#880]
Hello, I'm new to this and was wondering how to download PSX games on to Provenance 1.5. On my phone, I was able to download Snes (.7z files) games and open them in Provenance without any issues. But I can't get PSX games (also .7z) to show up in Provenance even though I installed them the exact same way as the Snes games.

**Comment by JoeMatt** [comment]
https://github.com/Provenance-Emu/Provenance/wiki/Formatting-ROMs
