### ISSUE TITLE
IOS Provenance 1.5 - PSX game boots into Audio/CD mode

### ISSUE THREAD

**Issue by Seta193** [Provenance-Emu/Provenance#881]
Ok so I managed to successfully install a PSX game (Crash Bandicoot) onto my phone, with the .cue + .bin files in the "com.provenance.psx" folder. But once I select the game in Provenance, it won't start properly. Instead, it shows the Sony logo and goes into the blue audio/CD player screen instead of the actual game. Any way to get the actual game to start?
![ri54nhh](https://user-images.githubusercontent.com/38902763/39555164-ff4ccb52-4e44-11e8-8c63-205f92a53977.jpg)

**Comment by sevdestruct** [comment]
probably bad rom, - also, please don't ignore the issues template, makes it hard to help you — ask for help on our Discord server— game play fine for us.
