### ISSUE TITLE
TvOS cannot build over itself 

### ISSUE THREAD

**Issue by tomp8628** [Provenance-Emu/Provenance#886]
TvOS cannot build over itself, even with same version. Troublesome for free developer accounts. 

### Expected:  
Rebuild Provenance over itself successfully

### Actual:  
Error in Xcode about database migration.

### Reproduce:  
1. Install on tvOS.  Then reinstall over itself. Even with same version. 
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by tomp8628** [comment]
On beta 1.5 obviously, recent few versions since maybe mid April.

**Comment by JoeMatt** [comment]
There's no bug here. 1.5 is under dev, as the schemas change the DB has to be dumped. It would be a huge overhead to write a translation function for every change between releases. If this is an issue, use a different bundle ID, don't upgrade or stick to 1.4.

**Comment by sevdestruct** [comment]
Agreed.
