### ISSUE TITLE
Download Provenance

### ISSUE THREAD

**Issue by ricapctba** [Provenance-Emu/Provenance#887]
replaceWithSummary

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ x] 1.4

#### APP SOURCE
- [x ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ x] [Building](https://git.io/vpYzv) *from Source*
  - [x ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ x] Apple TV

#### iOS/tvOS VERSION
- [x ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>
Hello,

I had make the download, but some files not having.

for example this folders: Provenance-develop\PVMupen64Plus\Plugins , all folders inside are in blanck....

please, help me.

tkls

**Comment by JoeMatt** [comment]
`git submodule init`
Follow the wiki.

https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance#building

**Comment by ricapctba** [comment]
tks for your replly...

But not working, last month i got install in other appletv..

But now, have some wrong...

Did u get ??

**Comment by jasarien** [comment]
If it’s not workingX then you’re not following the instructions in the wiki you were linked to. If you can’t do that, then we can help you.

**Comment by ricapctba** [comment]
ok...tks...I will try again after.
