### ISSUE TITLE
Atari 2600: Add ability to use right analog stick as 2nd player stick

### ISSUE THREAD

**Issue by fancyham** [Provenance-Emu/Provenance#889]
For games that have one player using two joysticks, allow the 2nd player stick to be the right analog stick and with one of the unused controller buttons as the fire button(s). 

Useful for games like two-stick battle zone, or with games like 2600 Stargate, where the second stick is used by player 
 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
I'm not 100% clear what this feature is.

On games that are accepting input on controller 1 for player 1, you want to use a second controller as a second joystick input for that player?

Which systems?

**Comment by sevdestruct** [comment]
I think what is meant is that there is some game that uses the second player joystick? And that if we could allow the player 1 right stick to control the player 2 left stick.. actually no, I have no idea what the fuck this is..

**Comment by fancyham** [comment]
Yes, exactly that.  Some 2600 games, for example, use the second-player stick for additional functions. In some more complicated single-player games, the right stick controls loading different weapons or manage inventory or accesses maps.

So since many MFi controllers have dual (analog) sticks, it’d be nice to map the unused right analog stick to be the second-player joystick so one doesn’t need a second MFi controller to access those functions.  The second player joystick button should then be mapped to an unused game pad button.

**Comment by JoeMatt** [comment]
I mis tagged the commit cause im' tired but it's added here,
9992151eb75defb35e700e7ceb3127d45a60c23d

**Comment by fancyham** [comment]
Cool!
