### ISSUE TITLE
After updating to Provenance 1.5, it only supports .7zip files... (iOS)

### ISSUE THREAD

**Issue by vghost01** [Provenance-Emu/Provenance#891]
Before updating to 1.5 in Cydia, Provenance 1.4 suported basically all files that I tried to emulate (.rar, .bin, .zip, .7zip) but after updating to 1.5, every game from my library except .7zip games have dissapeared, and even if I try to re-download the games, they won't appear in my library. Only .7zip games work.

Also, another issue: When pressing the + in the top right corner, and selecting cloud & local files, the app simply crashes.

Fixes?

**Comment by jasarien** [comment]
You mentioned Cydia. Did you get Provenance from the cydia store or side load it with cydia Impactor?

**Comment by vghost01** [comment]
From the Cydia store, using the dtathemes repo.

**Comment by jasarien** [comment]
Unofficial builds are not supported. They are usually out of date and contain bugs that we have already fixed in latest commits. Please see the wiki for supported install methods.
