### ISSUE TITLE
PSX buttons not working

### ISSUE THREAD

**Issue by wilsonb8** [Provenance-Emu/Provenance#893]
Hi,
I’ve just installed on ios11.3 but I can’t get psx games working. They load fine but the buttons on the phone don’t respond. 

In particular D-pad buttons not responsive 

### Expected:  
Menus to move/game to move

### Actual:  
Nil

### Reproduce:  
1. Open either Harry Potter games on psx and attempt to use menus

# 
#### NOTES  

#

#### APP VERSION
- [x ] 1.5 *beta*
  - [ x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Most likely this is same as #826
