### ISSUE TITLE
[Feature Suggestion] Dropbox / Google Drive Sync

### ISSUE THREAD

**Issue by nsuchy** [Provenance-Emu/Provenance#900]
Hi everyone. This is a feature suggestion I think might be nice to include in Provenance 2.0, the ability to sync our ROMs and Game Saves to either Dropbox or Google Drive would be a really nice feature. Examples of the need are messed up installs of a new build, a lost or stolen device, and the ability to use other emulators also synced to those platforms. Thoughts?

**Comment by jasarien** [comment]
Duplicate #1

**Comment by nsuchy** [comment]
@jasarien Thanks for clarifying, funny how this is a duplicate of the first issue ever 😛, thanks for all you do :)
