### ISSUE TITLE
Importer match by filename needs to filter to known extensions

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#901]
After refactoring to match by filename before MD5, things like jpg's are matching as ROMs now. 

Need to filter to only known ROM extensions.

### Expected:  
ROMs match by filename and only roms

### Actual:  
Non-rom files with known filenames are matching as roms, ie; Super Mario World.jpg

### Reproduce:  
TBD

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Might want to pair this with #760

**Comment by JoeMatt** [comment]
That's for a later release though, this is a new bug from a change I made recently.
