### ISSUE TITLE
Problem with Importing Genesis Roms

### ISSUE THREAD

**Issue by BrettBidwell** [Provenance-Emu/Provenance#907]
replaceWithSummary

### Expected:  
To import a Genesis rom into Provenance beta 1.5

### Actual:  
Nothing happened 

### Reproduce:  
1. Add .bin file support not just .cue file support
2.
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ✔️] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ✔️] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [✔️ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [✔️ ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Please read the wiki, you're doing it wrong, read importing ROMs. And formatting roms. Support was  dropped for .bin Genesis ROMs, change extension to a supported one. also .cue have nothing to do with Genesis.. at all
