### ISSUE TITLE
WWF NO MERCY 

### ISSUE THREAD

**Issue by Crimson43** [Provenance-Emu/Provenance#910]
Can’t play WWF NO MERCY. I try to play it but there is no analog stick to move/select a type of match or superstar. Plz fix if you can

**Comment by Crimson43** [comment]
Can’t play WWF NO MERCY. I try to play it but there is no analog stick to move/select a type of match or superstar. Plz fix if you can

**Comment by sevdestruct** [comment]
stop. use a full MFi controller. go to Discord to discuss.
