### ISSUE TITLE
Renaming matched ROMs broken

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#916]
Renaming [matched] games in Game library (and game info) is broken.

### Expected:  
Renames

### Actual:  
Doesn't

### Reproduce:  
Try to rename a [matched] ROM:
- [ ] Long Press in Game Library
- [ ] Long Press in Game Info View

# 
#### NOTES  
Broke directly after zoom Game Library feature commits. Working previously.

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Unable to reproduce on multiple devices, renamed long press and in moregameinfo vc

**Comment by sevdestruct** [comment]
Renaming bug seems isolated to matched ROMs, unmatched ROMs still allow renaming…
