### ISSUE TITLE
PSX multi-disc

### ISSUE THREAD

**Issue by falcocerr** [Provenance-Emu/Provenance#922]
hi, Sorry if this has already been asked, I looked but couldn’t find a question like this
All my games work correctly, even multi-disc games but this is my “issue”
For some multi-disc games I only see one image in the library (that’s perfect) but for others I have an image for each disc, what can I do to get just 1 image per game and not 1 per disc?

**Comment by sevdestruct** [comment]
known issue. refer to importing roms wiki. try importing and unarchiving 1 at a time
