### ISSUE TITLE
Save State Makes UICollectionView Crash on dequeue

### ISSUE THREAD

**Issue by leolelego** [Provenance-Emu/Provenance#925]
The last build on develop (sha `9d71b792`) crash on Apple TV when you dequeue in `RealmCollectionViewCell.swift` at line `340` and cellId = `SaveStateView`. 

With message `'[<Provenance.PVSaveStateCollectionViewCell 0x7fb661459530> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key label.'`

~~No issues on iPhone/iPad.~~ I really think It's linked to the Storyboard for the cell.

### Reproduce:  
1. Fresh install/Launch
2. import a game (SNES)
3. Launch the game, wait a little for an auto save state
4. go back to the app home 
5. -> Crash

6. Relaunch the app -> Crash

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by awasem** [comment]
yes just crashed for me too

**Comment by sevdestruct** [comment]
iOS seems fine again. After travis.yml update commit. Will report if it shows up as in.

**Comment by JoeMatt** [comment]
fixed in e1266bdd72b216c11a2cef60fb8b30fc11754496
