### ISSUE TITLE
Multi disc PS1 games doesn't work

### ISSUE THREAD

**Issue by pschwaab** [Provenance-Emu/Provenance#929]
Hi all,
I recently downloaded Final Fantasy VIII to play and followed the instructions to get them all in one .7z or zip file (I've tried both formats and they don't work.) I then put it in icloud drive and add it to my providence on iphone and I get the error message that it might not be set up right or corrupted or something. Can you tell me first of all if I set it up right, and if it is, what else might be causing the issue? Other ps1 games work fine. 

![untitled](https://user-images.githubusercontent.com/39775117/40736926-48c9ead2-6437-11e8-9c91-e4dc0d7d6b8b.jpeg)

**Comment by sevdestruct** [comment]
This already works. And you didn't use the template. Read the wiki or go to discord and ask for help.

**Comment by pschwaab** [comment]
I managed to figure it out anyway. Had the m3u set up as a rtf

**Comment by sevdestruct** [comment]
@pschwaab: It's specified in the wiki you need to make plain text file. You realize we have a Discord server full of 500+ users that can help you figure this out easier, even though all of this information is 100% on the wiki.
