### ISSUE TITLE
Final Fantasy VIII controls do not work after I get into the game.

### ISSUE THREAD

**Issue by pschwaab** [Provenance-Emu/Provenance#930]
I press to create a new game with the controller connected. It goes through opening cinematic and then I get to the first conversation in the game. I can't press anything on the controller and disconnecting the controller and using the virtual buttons doesn't work either.
### Expected:  
Expected the game to work

### Actual:  
Controls didn't work after selecting new game. they did work on the menu though

### Reproduce:  
1. Start final fantasy 8
2. Try to use controls in the game after selecting new game
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)* 

#### INSTALLED BY 
- [ x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by Cloutdaddyy** [comment]
Wait you got muti disc games working on 1.5 can you show me because I’m so confused at the moment on how to do it I did all the steps but I get a error saying something is out of place or corrupted

**Comment by pschwaab** [comment]
I got it working because I had created the .m3u text file as a .rtf instead of a .txt because I was using a Mac. So I clicked format and change to .txt file. You need to create a .txt file with the names of all the .cue files then rename it to .m3u instead of .txt and include that with you zip file of all the disc images with all the cue files. That’s what my issue was anyway.

**Comment by sevdestruct** [comment]
@pschwaab you specified sideloading as your means of installing. are you sure about that?
Please stop opening Issues and go to our Discord #help channel first.

@Cloutdaddyy all taht information is fully detailed in the wiki in Formatting ROMs
