### ISSUE TITLE
Use full height of the screen on Landscape with iPhone X for PSX and N64

### ISSUE THREAD

**Issue by leolelego** [Provenance-Emu/Provenance#938]
Upscale a little the emulator PSX  and Nintendo 64 frame size on iPhone X on landscape. Actually on the opening (Sony logo on PSX) the height is full filled but after this their is some padding top and bottom.

I suppose It came from choice made to looks well on iPhone 7-8/plus models who have the same ratio.  

Some screens, I added the red background to determine the space at the top/bottom which could be used (in black)
![img_8ecd5595bd2b-1](https://user-images.githubusercontent.com/4069471/40976359-412b3baa-68ce-11e8-8521-4fa10ea05058.jpeg)
![img_99fa4eb34219-1](https://user-images.githubusercontent.com/4069471/40976360-41463cf2-68ce-11e8-96c3-a1bc185b0ca5.jpeg)
![img_0762](https://user-images.githubusercontent.com/4069471/40976357-410ea31e-68ce-11e8-9634-083964a9396b.PNG)

### Expected:  
Have full height screen used on iPhone X in Landscape. 

### Reproduce:  
1. Open PSX or Nintendo 64 games on Beta 

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
If the PSX BIOS logo fills the screen, then the letter boxing comes from the game.

**Comment by JoeMatt** [comment]
Sizes are set to standard screen sizes. As James stated, lettering boxing would be from the games.
There are no plans for custom sizes at this time. It may come down the road with #680 or #742

**Comment by sevdestruct** [comment]
Also: #436

**Comment by ansinerd** [comment]
can we have full screen for psx on provenance? on my Iphone 13 the latest build has cropped from both sides in landscape mode while it works perfect in portrait mode.
