### ISSUE TITLE
Opening ROM locks library UI

### ISSUE THREAD

**Issue by BaffleBlend** [Provenance-Emu/Provenance#939]
### EDIT: I assumed wrong what the issue was. Check the later posts for more information.

I have my own reasons for wanting to make individual rom shortcuts, so I was happy to see Joe expand on the options.
I was delighted to find that the "open by title" option works fine. However...

### Expected:  
With the url " provenance://open?md5=153b6d32026993569b16ff89c53197a3 ", I expected to open "Sonic3C", a mod for Sonic the Hedgehog 3.

### Actual:  
The game not only fails to open, but very game cover is replaced with a blank image, every game title is replaced with the placeholder "Long Game Title: Extra Ext..", and nothing can be clicked, including any ROMS or the buttons on the top of the screen.

### Reproduce:  
1. Obtain the MD5 of any game in your library.
2. Enter the open-by-MD5 URL scheme ("provenance://open?md5=") into Safari, with the chosen game's MD5.
3. Press "Go".

# 
#### NOTES  

~~An important note is that the other URL option to open by title, in this case " provenance://open?title=Sonic3C ", DOES NOT cause this problem and in fact opens the game successfully.~~
Note no longer valid. See below.

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by BaffleBlend** [comment]
Update

**Comment by BaffleBlend** [comment]
I closed this by mistake while I was TRYING to add new information. I'm not entirely sure how it happened.

I spoke too soon on the open by title being a success.

While it DOES open the game, and returns to the menu normally after exiting the game, closing and then reopening Provenance makes it become locked in the same way.

Opening by title the same way afterward still succeeds at opening the game and still accesses the non-locked menu upon quitting the game, but it becomes the only way to.

**Comment by BaffleBlend** [comment]
Update: with the help of a backup of the system files I made immediately after building, I was able to locate the file causing the lockout.

It's "default.realm".

Replacing default.realm after the lockout with the backup default.realm made Provenance function normally again.

**Comment by JoeMatt** [comment]
Replacing the realm file and not it's associated files will lead to odd behavior so that's not really expected to 'fix' anything.

I'll look at the original bug but it sounds like a one off issue. Did you do any other kind of manual file replacement before?

**Comment by BaffleBlend** [comment]
Well, I did delete everything in the Provenance folder so that I could cleanly restore it from the backup I made immediately after building it and before opening it for the first time.

Unfortunately, I can't afford to keep rebuilding from scratch to experiment. Building takes me two hours minimum.
