### ISSUE TITLE
Accessing PSX memory card menu

### ISSUE THREAD

**Issue by SirJohny** [Provenance-Emu/Provenance#940]
Some games like Tomba 1 and Suikoden 1 save files can be used in the sequels. I was wondering if all PSX games use a different virtual memory card and I want to load a Suikoden 1 file in Suikoden 2. How to access PSX memory card menu?

#### APP VERSION
- [  ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
You can find the battery save and copy it over the battery save for the sequel.
We have no plans for sharing battery saves between games at this time.

**Comment by tubartz08** [comment]
Hi!

I am also playing suikoden 1, and also wanted to play suikoden 2 as a sequel. I did copy the saved file of suikoden 1 from battery save folder and transfer it to battery save folder of suikoden 2. But when i started to play suikoden 2, it says no save data from suikoden 1. Hope you can help me, i am willing to donate. Godbless you!

**Comment by sevdestruct** [comment]
This issue is closed, but you might find a way to do this with a memcard manager, as mentioned in: [Game Saves](https://github.com/Provenance-Emu/Provenance/wiki/Saves), and manually put your save from one game's memcard onto the memcard you are using for the sequel so it is detected.
