### ISSUE TITLE
PC-FX controls are wrong

### ISSUE THREAD

**Issue by BaffleBlend** [Provenance-Emu/Provenance#941]
I've already reported this, but I may as well make it an official ticket.

### Expected:  
Onscreen controls to do what the button label says.

### Actual:  
(Key: What the button says it is → What the button ACTUALLY is)
• Ⅰ → Ⅰ (Correct)
• Ⅱ → Ⅱ (Correct)
• Ⅲ → D-Key Up
• Ⅳ → D-Key Right
• Ⅴ → D-Key Down
• Ⅵ → D-Key Left
• Select → Ⅲ 
• Run → Ⅳ
• D-Up → Ⅴ
• D-Right → Ⅵ
• D-Down → Select
• D-Left → Run

### Reproduce:  
1. Load any PC-FX game.
2. Experiment with the controls.

# 
#### NOTES  
As reference material, here are what the controls are SUPPOSED to be for "Battle Heat", one of the FX's launch titles:
Ⅰ: Taunt
Ⅱ: Block/Dodge (when combined with direction)
Ⅲ: Light Attack
Ⅳ: Heavy Attack
Ⅴ: Jump
Ⅵ: Special Attack (can only be used when health is low)

(Source: https://www.giantbomb.com/battle-heat/3030-27416/ )

The directions and remaining buttons can be tested in the BIOS; the D-Key will move the cursor, Select will jump to one of the menu options, and Run will start the game.

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
@BaffleBlend when you get caught up could you see if MFi mapping is better now? my last couple commnits might have fixed this for both potentially.
