### ISSUE TITLE
This application’s bundle identifier does not match its code signing identifier.

### ISSUE THREAD

**Issue by jmaver** [Provenance-Emu/Provenance#943]
I have built and deleted and built over and over again. The build works fine. When it goes to install onto my iPhone X, it copies the files and then I get this dialog message. I tried another set of bundle ids initially with com.johnmaver.* instead, but same issue. I even went to each project and set it up as my bundle id. Same issue. I have done clean/build, clean folder/build as well. I can't fix it!

### Expected:  
I expected it to install on my phone and run, like it does on the emulator.

### Actual:  
Build succeeds. I get that dialog and install fails.

### Reproduce:  
1. brew cask install fastlane
2. git clone https://github.com/Provenance-Emu/Provenance.git
2. cd Provenance
3. git submodule update --init
4. brew install carthage
5. open Provenance.xcworkspace in xcode
6. I signed up for a paid developer account and it pulls my info correctly
7. Go to Project settings and change bundle id for 4 targets
  a) Provenance -> com.johnmaver2.provenance
  b) ProvenanceTV - com.johnmaver2.provenancetv
  c) TopShelf - com.johnmaver2.provenancetv.topshelf
  d) Spotlight - com.johnmaver2.provenance.Spotlight
8. For each, set the Team to the paid account. Profile and signing cert look good
9. Switch to Provenance-Release
10. Initially created, but now just set app group  for each of the 4 to group.johnmaver2.provenance. All steps have checks.
11. Set PVAppGroupId to "group.johnmaver2.provenance" in Provenance/ProvenanceTV/PVAppConstants.swift
12. Hit run with target = my phone
13. build completes
14. install starts, copies files, and failes.

# 
#### NOTES  
- XCode 9.4
- iPHone X - 11.4
#

#### APP VERSION
- [X] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [X] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [X] [Building](https://git.io/vpYzv) *from Source*
  - [X] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [X] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [X] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sapidog** [comment]
I alse have same issue, confused...

**Comment by sevdestruct** [comment]
Yeah, we're aware. You can join Discord and keep up to date on dev status, and announcements to be aware.

**Comment by jasarien** [comment]
This is fixed in b64166a2e95f9dcbb1bea8ef34e6a83d06bd2b05
