### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#945]
This is an umbrella ticket for adding localization

- [ ] Localize XIBs and Storyboards
- [ ] Locate strings in source code and replace with `NSLocalizedString`
- [ ] Add localization files for English
- [ ] Recruit community members for other languages

**References**
https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881
https://codeburst.io/localization-of-ios-app-in-swift-4-and-xcode-9-3c7c7d53ae11

**Comment by BaffleBlend** [comment]
Could I have a transcript of all of the text that Provenance uses? I may be able to help with this to an extent.

**Comment by illando** [comment]
I can help with Italian localization.

**Comment by JoeMatt** [comment]
2.1.0 added many langs (russian, dutch, chinese (simplified) and spanish).

If @illando wants to do italian still, or @yoshisuga Japanses, look at Strings.strings and create a localized version in the standard format copied from the english version.

eg;
"Yes" = "Si"
