### ISSUE TITLE
Color Palette option available, but not functional on GBC: Enable, or Remove

### ISSUE THREAD

**Issue by BaffleBlend** [Provenance-Emu/Provenance#946]
I was surprised to find the "Change Palette" option to also be in the menu for Game Boy Color games. I remembered that a number of GBC cartridges could also be played on an original Game Boy (the ones this is possible with having a black cartridge instead of the usual transparent one).
I thought the menu option was there for that reason. However, it does nothing when chosen.

### Expected:  
The screen color to change to green or monochrome, as if the cartridge was in an original Game Boy.

### Actual:  
Nothing happened.

### Reproduce:  
1. Open any Game Boy Color game.
2. Open the pause menu.
3. Select "Change Palette".

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jsxn** [comment]
I don't see the change palette in provenance anymore??

**Comment by jsxn** [comment]
well at least for gameboy games
