### ISSUE TITLE
[Request] Ability to change console sorting

### ISSUE THREAD

**Issue by BaffleBlend** [Provenance-Emu/Provenance#947]
I'm sorry, but this is a minor annoyance I've had.
Right now, the consoles are in (roughly) alphabetical order. While this does work for navigation mostly, it does lead to some oddities such as the 32X interrupting the Atari consoles (while being on practically the opposite end of the sorting than its sister accessory, the Sega CD), or the Game Boy Advance being before the Game Boy Color. Not to mention that some consoles have alternate names (e.g. should it be sorted as the Lynx or the Atari Lynx? The Turbografx or the PC Engine?) or are simply in the wrong place entirely (e.g. the Game Gear).

Right now, just for quick reference, the order is:
Atari 2600, 32X, Atari 5200, Atari 7800, Famicom Disk System, Game Gear, Game Boy, Game Boy Advance, Game Boy Color, Genesis, Atari Lynx, Master System, Nintendo 64, Nintendo, Neo Geo Pocket, Neo Geo Pocket Color, Turbografx-16, Turbografx-CD, PCFX, Pokémon Mini, PlayStation, Sega CD, SG-1000, Supergrafx, Super Nintendo, Virtual Boy, Wonderswan

I would personally prefer if the consoles were sorted in mostly the same way as they are in [the MFi Controls spreadsheet](https://docs.google.com/spreadsheets/d/1sxgeExnqDg8vdnDHyjjcDbpB0LgOnTwIOFCgaKr2ajU/edit?usp=sharing); by company, family (e.g. the Game Boys being together and separate from the NES-SNES-N64 line), and chronological order. So I would like the option to change sorting in the Appearance menu.

**EDIT:** For the sake of clarification, this is more or less the order I would prefer:
(Note: * marks consoles that haven't been added yet, but I know are planned/considered for some point. These obviously don't apply as categories yet.)
**(Atari)**
2600, 5200, 7800, Jaguar*
Lynx
**(NEC)**
PC Engine / Turbografx-16, PC-CD / Turbografx-CD, Supergrafx, PC-FX
(Nintendo)
NES / Nintendo / Famicom, Famicom Disk System, Super NES / Super Nintendo, Nintendo 64
Game Boy, Game Boy Color, Game Boy Advance, Nintendo DS*
Pokémon Mini
Virtual Boy
**(Sega)**
SG-1000, Master System, Genesis / Mega Drive, Sega CD / Mega CD, 32X, Saturn*, Dreamcast*
Game Gear
**(Sony)**
PlayStation
PlayStation Portable*
**(Miscellaneous)** _(companies with only one console and relatively few games available)_
3DO*
Neo Geo Pocket / Color
Wonderswan / Color

**Comment by sevdestruct** [comment]
This is already planned in 2.0, @BaffleBlend, if you have additions please add to comments in #722
