### ISSUE TITLE
BIOS folder not created

### ISSUE THREAD

**Issue by datav87** [Provenance-Emu/Provenance#950]
There was no BIOS folder created in Apple Documents therefore I am unable to import BIOS settings to play PSX.

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
This is already fixed in development branch

**Comment by datav87** [comment]
Sorry for being such a newb...
Could you tell me where in the development branch I might find it?
Thanks!

**Comment by datav87** [comment]
I believe I found it..
BIOS.cpp or BIOS.h?
I’m new to all this so I’m just not sure what to do with those lines of code.
Thanks again!

**Comment by JoeMatt** [comment]
https://github.com/Provenance-Emu/Provenance/wiki/Installing-Provenance#building
https://github.com/Provenance-Emu/Provenance/wiki/Importing-ROMs

For any help join help channel on our Discord server from our home page link.
Locking this thread now.
