### ISSUE TITLE
Sega CD missing start button

### ISSUE THREAD

**Issue by Milkyyboi** [Provenance-Emu/Provenance#953]
I am having problems with the controls in the sega cd system where the start button is missing, is this normal or a bug and is there a fix?

**Comment by sevdestruct** [comment]
go to discord and use our help channel, this isn't enough information.

**Comment by sevdestruct** [comment]
@Milkyyboi …if this is regarding MFi controllers, yes, please refer to [Controls](https://bit.ly/2LDZNzI) in the [wiki](https://git.io/vxA4Q), we also have a [FAQs](https://git.io/vp9EX) section. Please use it.
