### ISSUE TITLE
Provenance TVos app crashes after adding custom artwork

### ISSUE THREAD

**Issue by guitarmandp** [Provenance-Emu/Provenance#954]
Not sure if this is just a bug with 1.5 but in using the new 1.5 the provenance TVos app crashes once my custom artwork has been uploaded everytime I open the app and the only fix is to delete the app and reinstall the app. So far custom artwork isn't working for me.

**Comment by guitarmandp** [comment]
Okay so I'm not sure that I did something wrong but it seems to work if I upload both the game and the artwork at the same time. If I upload the game and then go back later and upload the artwork that's where I run into problems.

**Comment by sevdestruct** [comment]
this is a none issue in #760
