### ISSUE TITLE
Why Whenever I clicked the plus in the corner of my screen it tells me I have no internet connection?

### ISSUE THREAD

**Issue by akirk943** [Provenance-Emu/Provenance#955]
REPLACE_WITH_SUMMARY

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
In the latest version the + button will provide the option to import ROMs from the local Files app or from cloud services, or start the built-in web server.

On older versions (eg, 1.4), it starts the built in web server only. If you are not connected to a WiFi network, then you cannot start the web server, it requires a WiFi connection.

**Comment by sevdestruct** [comment]
That's not to say you can't create an ad-hoc wifi network via your laptop or pc and connect your phone to it, which should also work.
