### ISSUE TITLE
Share function not working between 2 devices

### ISSUE THREAD

**Issue by illando** [Provenance-Emu/Provenance#956]
I tried to send some games from Provenance installed on iPad to Provenance on iPhone... but it transfers only the game.

The functions seems to work perfectly from the side of the device that is sharing.
Inside the zip file created there are: the rom, the cover, the Battery Saves, and the Save States with their relative screenshots.
The problem seem to be on the device that is receiving this Zip. After choosing to open the archive with "Files", I saved it inside the Provenance import folder.
The game is correctly added to the library with the cover, but the  Save States with screenshot remains in the inbox folder, and the Battery States file disappears.

Maybe an iCloud sharing system is already scheduled for version 2.0... but meanwhile this could be a great alternative!

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
The importer doesn't understand battery saves and save state files nor is there metadata to help with the proper import, so this is a feature request more so than a bug since it's not expected or documented to work in the manner stated in this ticket

**Comment by JoeMatt** [comment]
closing in preference of feature ticket #959
