### ISSUE TITLE
Trouble uploading Roms in 1.5 Beta on Apple tv 4k

### ISSUE THREAD

**Issue by Dnordborg** [Provenance-Emu/Provenance#957]
REPLACE_WITH_SUMMARY

### Expected:  
Roms to load

### Actual:  
Library remains empty, tried importing with every method
Switched back to version 1.4 and then it works to import the roms

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [x ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x ] Apple TV

#### iOS/tvOS VERSION
- [x ] Latest (11.4)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by urherenow** [comment]
This seems to be the go-to answer, but perhaps the issue template should be updated to ask for that info? 1.5 beta does not mean it came from a third party site. I built the current source directly from here, and must say that something is indeed fishy with the uploads.

I tried all methods as well, and even created a roms folder to upload to via the web interface. The next day, I tried one more time chosing the local option and pointing to the files I uploaded the night before... and this worked right away. No Idea what was going on in the background that necessitated the long wait for the uploads to work.

**Comment by sevdestruct** [comment]
No one assumes this was an unofficial install. ROMs folder is no longer used, it's Imports now (as states in the wiki) You clearly aren't reading the documentation or looking at existing issues nor is the OP - we are aware of specific issues with importer and any _fishy_ importer bugs are currently  logged in #832 #785 #867 and conversation can go into commments there or if this is something new it can be considered a new bug if anything specific was specified whatsoever, which wasn’t, and  it’s not reproduceable if you follow the wiki - we don’t need more nonspecific tickets or tickets for existing topics, we get new tickets for things all the time that more often than not user error and started for a lack of reading the wiki —  Our GitHub is for actual bug reporting and tracking  not a discussion board or help desk, we have discord for that, please check importing ROMs wiki, and formatting roms. we understand the purpose of GitHub just fine.

**Comment by sevdestruct** [comment]
@Dnordborg if you are still having issues, please drop by Discord in our [#help](https://discord.gg/NhzgrXh) channel and we will get you sorted.

**Comment by urherenow** [comment]
None of the 3 referenced tickets are related to this bug. The wiki was followed FIRST, before experimenting. What part of “by any method” is not understood? The 3 roms I was trying are formatted perfectly fine. They imported fine the next morning AS I ALREADY STATED.

This is a bug with the latest source. Don’t worry though. I won’t try to post again or contribute to a bunch of divas that assumes that nobody can read a wiki.

**Comment by sevdestruct** [comment]
Okay... Because divas work on open source projects for free and create open communities to help their users.. right.

Things don't just magically work the next morning.. is it possible—consider just for a second that just maybe missed something or skipped a step. Try helping people help you. Please stop presuming you know everything. You don't need to experiment. Many people have followed the wiki and it works. I can demonstrate it on that exact hardware. Unless you state the exact things you are trying in detail we can't guess what you are doing. Saying you 'did all the things' is not giving details. We are not mind readers. Submit steps to reproduce, or a log. Explain. Saying something is broken without that is just like taking a shit on the floor. It's not helpful.

**Comment by JoeMatt** [comment]
Oh boy 🙄

And yeah this is a crappy bug report, steps should be clear. 

Did you upgrade over a 1.4 install or fresh install?
Did you try killing the app and restarting?
Does 'by any method' really mean that cause we have 
1. Web interface
2. Web Dav

Does 'refresh library' fix it?

**Comment by discostur** [comment]
@JoeMatt @sevdestruct Hi, i think i hit the same bug ... did a fresh install of provenance `v1.5b 2774` via sideload on my apple TV 4k running latest iOS 14.3. 

I tried uploading the .z64 ROMs to the `Imports` folder via webUI. If i refresh the webUI just after the upload has finished the directory is empty - so the just uploaded file disappeared. In the provenance app itself it does not display any app - even after "refresh library" ... 

My Apple TV has about 15 GB of free storage ... 

Any ideas? Can i provide you with additional information?
