### ISSUE TITLE
Multi disc games provenance

### ISSUE THREAD

**Issue by scedii04** [Provenance-Emu/Provenance#958]
HELP PLEASE

I am very noob and not techy when it comes to these stuff. So can anyone help me or give me a guode where I can watch and learn how to play multi disc on provenance? 

I dont know how to make m3u file (I am clueless I’m sorry)
Also the cue files im not sure if thats it but I downloaded FF8 on emuparadise and the only thing with the bin file is a VLC file. Im not sure if thats the .cue file.

Please help

**Comment by jasarien** [comment]
Please read the ROM Formatting Guide: https://github.com/Provenance-Emu/Provenance/wiki/Formatting-ROMs#multi-disc-games

Also, in future, please do not create an issue for technical support. Issues are for reporting bugs and feature requests. Please join our Discord server if you have other questions. The link was in the issue template that you deleted before writing your post.

**Comment by naannekh** [comment]
I also have issues about m3u file. Im using just an ipad and its really hard without computer. Can anyone help me with this without computer? I follow everything using documents and save the file .m3u but still not working :(

**Comment by sevdestruct** [comment]
@naannekh Please use our discord [help channel](https://discord.gg/3ka2E6) for these topics. As @jasarien posted above, Issues is for bug tracking not technical support.
