### ISSUE TITLE
N64 legend of zelda majora’s mask sound glitch

### ISSUE THREAD

**Issue by Abhijit-Kayande** [Provenance-Emu/Provenance#960]
Sound is not appropriate with this rom. I have build the app from my system using release scheme.

**Comment by sevdestruct** [comment]
@Abhijit-Kayande  can you please take this topic to the discord #help channel, there is a various few things it could be. If not please check FAQs wiki. There is a sound specific topic in there.

**Comment by JoeMatt** [comment]
if it's only this rom it's probably upstream and can't be fixed by us.

Check another version of mupen latest.
Also is this pal or NTSC?

Use the bug template next time.
