### ISSUE TITLE
Severe lag in landscape mode and lag when using full analogue 

### ISSUE THREAD

**Issue by Blitzwin** [Provenance-Emu/Provenance#961]
Okay i’m Not sure exactly why this is happening and i’m aware N64 support is still in beta but i’m Getting SEVERE lag in landscape mode in every single game, when it was working fine less than six hours ago. Not only that but I get ridiculous lag when ever I try to run in a circle which makes games like Super Mario 64, Zelda, Paper Mario completely unplayable

REPLACE_WITH_SUMMARY

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
You didn’t read any of the issue template or fill any of it in after posting. Try again.

**Comment by sevdestruct** [comment]
Please head to our discord help channel
