### ISSUE TITLE
False 'No Core Loaded' Error

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#964]
when launching a game from search getting no core loaded error after core loaded and game played. Visible when rotating phone or after quitting.

### Expected:  
no errors with successful core load

### Actual:  
false no core loaded error prompt

### Reproduce:  
1. Search for game (ie. Ninja Spirit on TG16)
2. launch game upon finding via search
3. rotate orientation or quit game after successful launch/play

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Is this with all medanfen cores? If so, it's a regression on a mednafen bug.

**Comment by sevdestruct** [comment]
I've seen it on a few systems, since posting this. Didn't make note if it was mednafen isolated. I'll pay closer attention, but think it's likely the case.

**Comment by JoeMatt** [comment]
Not happening for me on latest branch. Confirm still valid @sevdestruct

**Comment by sevdestruct** [comment]
Yeah, Resurfaced on build 2705, and happening consistently on any system for a while… but can't seem to reproduce, will try to snag a log if it does.

![image](https://user-images.githubusercontent.com/3118097/48973591-4b0e7780-eff7-11e8-932f-c18063bcf0e7.png)

![image](https://user-images.githubusercontent.com/3118097/48973592-58c3fd00-eff7-11e8-9133-c839743ffaa1.png)
