### ISSUE TITLE
Broken audio with PSX games on iPad Pro 9,7

### ISSUE THREAD

**Issue by Astrubale** [Provenance-Emu/Provenance#967]
PSX GAMES

### Expected:  
Audio fully working

### Actual:  
Audio not working at all

### Reproduce:  
1. Run a game
2. Audio not working

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ x] 1.4

#### APP SOURCE
- [ x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
PSX emulation has been improved for 1.5.
