### ISSUE TITLE
[Request] View Filename In Game Info

### ISSUE THREAD

**Issue by BaffleBlend** [Provenance-Emu/Provenance#970]
I already brought this up in the Discord, but I'll make it a ticket.

Sometimes, games get mislabeled or duplicated. This happens primarily in three situations from what I gather:
• If there's a hack/mod or alternate version of a game alongside the original (Example: a hack of Sonic 1 to play as Knuckles shows up as just plain Sonic 1)
• It's a lesser known or homebrew game with a similar title to a more notable one (Example: Tengen's recalled NES Tetris, frequently regarded as superior to the Nintendo version, shows up AS the Nintendo version)
• The archive the ROM is in contains more than one revision of the game, importing all of them at once by mistake (Example: if a game has had multiple revisions, or in cases where NA, PAL, and JP ROMs are bundled together—in some cases, both at once.) This situation is not only common but particularly frustrating because, unlike the other causes, there's little to no visual distinction when opening the ROM to see which one it is.

I would like the ability to view the ROM's filename in the Game Info option so I can check which version is which and easily know which to rename or delete.

**Comment by JoeMatt** [comment]
Added to dev
