### ISSUE TITLE
[Request] Quit Without Saving

### ISSUE THREAD

**Issue by BaffleBlend** [Provenance-Emu/Provenance#971]
Automatic save states are normally good, but there are some occasions when I don't want them, such as if I'm only opening a game to try it out or take a screenshot, if the game has no progression that would benefit from using automatic save states (such as puzzle or board games), if I've opened a game by mistake, or if a game has crashed or frozen due to its own glitches but Provenance itself is still running fine.

So, I would like a "Quit Without Saving" option alongside the "Save & Quit" option.

**Comment by JoeMatt** [comment]
It's not a bad idea, I just threw it into my last commit.

**Comment by jasarien** [comment]
Be aware, though, that autosaves are made every 5 mins as well.

**Comment by BaffleBlend** [comment]
True, but in most cases where I wouldn't want an autosave, the game hasn't been open for a full five minutes, and there's already an option to turn them off if needed.

**Comment by JoeMatt** [comment]
truest he autosaves are made on a timer anyway the way it's setup now, but I went ahead and added the feature.

I also replace the stock UI action sheet with a 3rd party toolkit, so you'll see a whole new redesign of the game menu now. It's not the final design but it's a start in the right direction.
