### ISSUE TITLE
Missing L2/R2 buttons on PS1/PSX emulator

### ISSUE THREAD

**Issue by Astrubale** [Provenance-Emu/Provenance#972]
REPLACE_WITH_SUMMARY

### Expected:  
All buttons avaiable

### Actual:  
Missing L2/R2 buttons (unable to play some games including Tomb Raider)

### Reproduce:  
1. Open a PS1/PSX game
2. You can see that L2/R2 buttons are missing

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
This has been resolved for 1.5

**Comment by Astrubale** [comment]
Did you included "Pete's PSX openGL2 plugin" for a better graphic? All
emulators are using that except this. Will be awesome if you can add it for
PS1/PSX emu.

Il ven 20 lug 2018, 11:57 James Addyman <notifications@github.com> ha
scritto:

**Comment by jasarien** [comment]
That is a separate issue. This is not a discussion forum. If you’d like to discuss other issues join the Discord. Links are on the main page.
