### ISSUE TITLE
“Show FPS count” slow down PSX games

### ISSUE THREAD

**Issue by Astrubale** [Provenance-Emu/Provenance#974]
If you enable “Show FPS count” it returns a strange count like 29fps while the game is running at 15 fps. If that option is enable it slow down PSX games that before were running without lags.
When disabling it you also must restart the app because if you don’t do so the lag persists even if fps aren’t showed anymore.

### Expected:  
When enabling “Show FPS count” in settings it just shows us the current frame rate while running a game.

### Actual:  
When enabling “Show FPS count” in settings for PSX games (other console games not tested) it reduces the frame rate (unplayable) and returns a strange count like 29fps (obviously not true). For restoring that you must disable it in settings and restart the app to get games running at the normal frame rate again.

### Reproduce:  
1. Enable FPS count in settings
2. Start a PSX game (you can see already the problems caused by it)
3. Disable FPS count in settings
4. Start a PSX game again (now fps count is absent but game still run at a riducoulus frame rate)
5. Restart the app
6. Start a PSX game (all back to normal)

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
This has been improved in the 1.5 beta branch. Please check whether your issues have been solved in the 1.5 branch before reporting bugs here.
