### ISSUE TITLE
Provenance; Loading Error.

### ISSUE THREAD

**Issue by jussstinkim** [Provenance-Emu/Provenance#975]
So I downloaded Valkyrie Profile to relive my childhood memories through Provenance on my iPhone 7 with the 11.2.1 software. I also jailbreaked my device quite recently just for your information. I followed every step with the link under the "Reproduce" section. I did exactly everything it told me just that its telling me to check if the game file isn't corrupt? Also told me if its supported Mednafen ROM format. If this was already answered or has a simple solution, please forgive me and my laziness. 

### Expected:  
I expected to run the game (Valkyrie Profile (PS1)) smoothly

### Actual:  
Instead "Failed to load game." appeared, along with "Check the file isn't corrupt and supported Mednafen ROM format"

### Reproduce:  
1. Followed every step in (https://github.com/Provenance-Emu/Provenance/wiki/Formatting-ROMs#multi-file-roms).
2. Imported game file through the Web Server
3. Added game file into "Imports" file.

# 
#### NOTES  
I am new to both Github and Provenance, please forgive me if this problem can be solved with a simple solution.
#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [x] I use 11.2.1
--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jussstinkim** [comment]
I also installed Provenance straight from Cydia, so neither Side-Loading or Xcode.

**Comment by jasarien** [comment]
We do not support any 3rd party builds including cydia. This is not the way to get Provenance. Your bug is likely old and already fixed because these 3rd party builds do not keep up to date with our source. Read the guide in the wiki.

**Comment by sevdestruct** [comment]
I've played Valkyrie Profile successfully. Even a patched Undubbed version and everything runs fine. Use official source.
