### ISSUE TITLE
steel series bluetooth controller

### ISSUE THREAD

**Issue by BigBills** [Provenance-Emu/Provenance#981]
Can anyone suggest why my controller isn't working with the provenance app?

REPLACE_WITH_SUMMARY

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [x] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
For app support please join the Discord. Issues are for bug reports and feature logs.
