### ISSUE TITLE
.n64 roms are not recognised by version 1.4

### ISSUE THREAD

**Issue by hectorox** [Provenance-Emu/Provenance#984]
REPLACE_WITH_SUMMARY

### Expected:  .n64 roms should be recognised and run
replaceWithExpectedResults

### Actual:  .n64 roms stuck in roms folder
replaceWithActualResults

### Reproduce:  Download a .n64 and you will see by yourself
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [☑️ ] 1.4

#### APP SOURCE
- [☑️ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [☑️ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ☑️] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [☑️ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by jasarien** [comment]
That’s because N64 was added in 1.5. 

1.4 does not have N64 support.

**Comment by hectorox** [comment]
Ah okay, Thank you for the information! Any chance to get a compiled version of provenance 1.5 beta?
I am not able to do that by myself...
