### ISSUE TITLE
N64 Game not starting (jap)

### ISSUE THREAD

**Issue by hectorox** [Provenance-Emu/Provenance#985]
REPLACE_WITH_SUMMARY

### Expected:  starting n64 game
replaceWithExpectedResults

### Actual:  After starting the game (Neon Genesis Evangelion 64) provenance freezes
replaceWithActualResults

### Reproduce:  try to run it, you should get the same
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [☑️ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [☑️ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [☑️ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [☑️ ] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [☑️ ] 11.x
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Can you take this game specific question to our Discord help channel, please?
