### ISSUE TITLE
8bitdo F30Pro Support (mismaps)

### ISSUE THREAD

**Issue by ha5696** [Provenance-Emu/Provenance#986]
(Edited by admin as a proper request)…
### Request
Please add support 8bitdo F30Pro. 

- [ ] Require documentation of the iCade key maps for this controller
- [ ] Fix mapping for N64 (analog and d-pad not responding)
- [ ] Check other systems for mismaps…
- [ ] Update to new unviersal mapping methodology

**Comment by sevdestruct** [comment]
no, this is not how to post issues, hiro.

**Comment by sevdestruct** [comment]
also this is already covered in #741

**Comment by sevdestruct** [comment]
closing, reopening #871 with additions
