### ISSUE TITLE
Provenance PSX buttons stuck

### ISSUE THREAD

**Issue by uberdan101** [Provenance-Emu/Provenance#988]
Greetings.  I finally got Legend of Dragoon installed on Provenance, but once gameplay begins it is impossible to actually play.  The up button on the digital on-screen pad is stuck, making it impossible to do anything.

### Reproduce:  
1. Install a multi-disc PSX game, particularly Legend of Dragoon.
2. Turn on the game without a separate controller.
3. Play it until you get to game play.
4. Get stuck.

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [x] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Just conducted a test, this is working on latest build. Update or defer to Discord server for help
