### ISSUE TITLE
Can someone help/explain how to get PS1 roms to work on provenance

### ISSUE THREAD

**Issue by PompeyFan** [Provenance-Emu/Provenance#992]
Sorry to me that guy but I think im missing something fairly simple as to why my PS1 roms are not showing up in my provenance library after 'extracting them' into the emulator.

Ive read through the guides and must admit I feel im doing it correctly but will happily admit im way out of my depth with all of this.

I did manage to install first time a version of pokemon fire red however ive got a feeling that worked as it is a Gameboy advance game and that maybe ps1, especially multi-disc games, require a little extra/

Basically the game I am trying to run is final fantasy 9. which has 4 discs.

I have downloaded a rom for each disc from a rom website.

as per the guide I have checked and the file for each disc has the ending to the file name of .7z which I belives means its been zipped the correct way?

however when I either 'open in provenance' or 'copy to provenance' it opens up the emulator and begins extracting. however once extracted nothing appears. no game tile, nothing.

When checking my provenance files I can see it does add the file to my imports so im not sure why it doesn't show?

I read you need to download the ps1 bios so I believe I have downloaded the correct ones. in the guide it says to download 3 for ps1 so I downloaded those, their files names are SCPH-5500 / SCPH-5501 / SCPH - 5502.

Now when I downloaded these nothing happened apart from them show in my imports.

I can see a separate file in the 'BIOS' sub folder in my provenance files named com.provenance.psx

Has this been added because I downloaded these files or was it always there as I cant remember. I must also add that when going into this file it was empty so I have copied the 3 downloaded files named above into this folder from the imports folder, if this is wrong please let me know and ill delete them from that folder and just leave them in imports.

on the main screen for provenance files I also have 3 files which I believe are for a game boy advance (assuming this is there as I have pokemon fire red installed), a game boy colour (again I did install pokemon crystal by mistake so its deleted but that is a GBC game) and com.provenance.psx.

Now I am assuming that folder is for ps1 but again not sure when or how it appeared (my guess is because of the bios I downloaded) but it is currently empty. Am I suppose to add my ps1 roms into here? I did try for just disc 1 of FF9 but still nothing appeared.

Lastly when I go to rename my FF9 disc 1 file (I havnt renamed it but wanted to see the whole file name) it ends with .bin

Now I read in the guide you need .cue also and also I think a m3u file? would these of been downloaded with my FF9 file fromt he rom website and are just hidden or not displayed in the imports section or are these files missing and that's why the game isn't loading?

sorry for the wall of text but I wanted to provide as much info as possible.

Thanks in advance 

REPLACE_WITH_SUMMARY

### Expected:  
replaceWithExpectedResults

### Actual:  
replaceWithActualResults

### Reproduce:  
1. replacewithStepsToReproduce
2. 
3. 

# 
#### NOTES  

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [ ] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (11.3)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by sevdestruct** [comment]
Stop opening new issues. This is for bug reporting and upcoming feature tracking. Take your help questions to Discord. https://discord.gg/4TK7PU5
