### ISSUE TITLE
Build error in Xcode

### ISSUE THREAD

**Issue by francomf** [Provenance-Emu/Provenance#994]
Getting this error when trying to build in Xcode. When I hit the play button it starts to build and then stalls somewhere around the middle. 

missing input '/Users/user/Provenance/Provenance/Version.swift' and no rule to build it

![image](https://user-images.githubusercontent.com/36484424/45587940-e2aa6800-b8da-11e8-9949-229e6ca2d75a.png)

#### APP VERSION
- [X] 1.5 *beta*
- [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [X] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [X] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [X] Apple TV

#### iOS/tvOS VERSION
- [ ] Latest (11.3)
- [X ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by medgno** [comment]
I've gotten a similar build error.

MacOS: 10.13.6, XCode: 9.4.1

<img width="786" alt="screen shot 2018-09-19 at 8 26 54 pm copy" src="https://user-images.githubusercontent.com/87882/45794519-fabc1780-bc4b-11e8-9dce-220068f86b2a.png">

**Comment by urherenow** [comment]
error: Build input file cannot be found: '/Users/.../projects/Provenance/Provenance/Version.swift'
that's what I'm getting on xcode 10 using the feature/xcode10 branch. I had JUST successfully built the regular 1.5 branch, although on BOTH, I had to let xcode make its own changes to PVGB.

There are also warnings like "Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'  "

**Comment by JoeMatt** [comment]
xcode 10 branch isn't up to date
You can use develop just fine in 10. The 10 branch has some 10 specific changes that break 9 so they're living there until we remove 9 support.
