### ISSUE TITLE
Xcode 10 build errors

### ISSUE THREAD

**Issue by lifeiscontent** [Provenance-Emu/Provenance#995]
I wanted to run a build of Provenance on Xcode 10 but it failed.

### Expected:  
for it to build

### Actual:  
```
~/Code/Provenance/PVLibrary/PVLibrary/CocoaLumberExtensions.swift:11:8: Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: ~/Code/Provenance/PVSupport/Carthage/Build/tvOS/CocoaLumberjackSwift.framework/Modules/CocoaLumberjackSwift.swiftmodule/arm64.swiftmodule
```

```
~/Library/Developer/Xcode/DerivedData/Provenance-gcsvatjiqexzwdgfsabczanxxhzd/Build/Products/Release-appletvos/PVLibrary.framework/Modules/module.modulemap:9:12: Header 'PVLibrary-Swift.h' not found
```

```
~/Code/Provenance/Provenance/Game Library/UI/PVGameLibraryCollectionViewCell.swift:12:8: Could not build Objective-C module 'PVLibrary'
```

```
~/Code/Provenance/TopShelf/ServiceProvider.swift:8:8: Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: ~/Code/Provenance/PVLibrary/Carthage/Build/tvOS/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule
```

### Reproduce:  
1. clone repo
2. checkout feature/xcode10
3. `open Provenance.xcworkspace`
4. set teams
5. run build
6. watch it fail

# 
#### NOTES  

could potentially just need dependency updates, but I'm not sure how to go about doing it.

#

#### APP VERSION
- [x] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [ ] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [ ] [Side-Loading](https://git.io/vpYzf)
- [x] [Building](https://git.io/vpYzv) *from Source*
  - [x] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [ ] iPhone
- [ ] iPad
- [x] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (12)
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment]
Standard error when you change Xcode versions. Clean Carthage build dirs and rebuild. Ask the help channel on discord for further help.

**Comment by mariotatis** [comment]
Same thing

Header 'PVLibrary-Swift.h' not found
Could not build Objective-C module 'PVLibrary'

'SteamController/SteamController.h' file not found

Failed to emit precompiled header 
/ProvenanceTV-Bridging-Header.h'

**Comment by JoeMatt** [comment]
This topic is closed and your error is not even close to the same as the original.

Ask for help on discord first, if a real error, make a new bug report.
