### ISSUE TITLE
Provenance doesn't work with IOS 12 on iPhone SE

### ISSUE THREAD

**Issue by daitx** [Provenance-Emu/Provenance#996]
Provenance doesn't work with IOS 12 on iPhone SE

### Expected:  
Provenance works with IOS 12 on iPhone SE

### Actual:  
Provenance doesn't work with IOS 12 on iPhone SE

### Reproduce:  
1. Upgrade from IOS 11.4 to IOS 12
2. Provenance cannot start, even after re-installation with Cydia Impactor

# 
#### NOTES  

#

#### APP VERSION
- [ ] 1.5 *beta*
  - [ ] latest build <sub><sup>*(as of writing)*</sup></sub>
- [x] 1.4

#### APP SOURCE
- [x] Provenance-Emu GitHub  *&nbsp;(Official)*
- [ ] Other  *&nbsp;(Unofficial)*

#### INSTALLED BY 
- [x] [Side-Loading](https://git.io/vpYzf)
- [ ] [Building](https://git.io/vpYzv) *from Source*
  - [ ] Xcode 9.3+
  - [ ] Xcode 9.2 *or lower*

#### PLATFORM
- [x] iPhone
- [ ] iPad
- [ ] Apple TV

#### iOS/tvOS VERSION
- [x] Latest (12)
- [ ] 11.3
- [ ] 10.x
- [ ] 9.x
- [ ] 8.x 

--------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by urherenow** [comment]
Did you go back to settings and trust the profile again?

**Comment by daitx** [comment]
> Did you go back to settings and trust the profile again?

I checked. It's still trusted. 
Even after I deleted the app, revoked the cert, reinstalled, re-trusted the new profile, still doesn't work

**Comment by JoeMatt** [comment]
1.4 won't support iOS 12. 1.5 does.

**Comment by daitx** [comment]
> 1.4 won't support iOS 12. 1.5 does.

Could you please share the ipa file for 1.5? Thanks.

**Comment by trungk18** [comment]
I installed the v1.4 on my iPhone 6S running iOS 12. It managed to load some of the PSX game but the button doesn't work. Where I can get some beta release as ipa file of version 1.5? 
I didn't have a crazy MAC machine for building from your source code.

**Comment by sevdestruct** [comment]
wiki -> FAQs
